# Libro Tercero. DE LOS JUICIOS ESPECIALES. {.unnumbered}

## Título I. DEL JUICIO EJECUTIVO EN LAS OBLIGACIONES DE DAR.

***1. Del procedimiento ejecutivo.***


**Art. 434 (456).** El juicio ejecutivo tiene lugar en las obligaciones de dar cuanto para reclamar su cumplimiento se hace valer alguno de los siguientes títulos:

1°. Sentencia firme, bien sea definitiva o interlocutoria;

2°. Copia autorizada de escritura pública;

3°. Acta de avenimiento pasada ante el tribunal competente y autorizada por un ministro de fe o por dos testigos de actuación;

4°. Instrumento privado, reconocido judicialmente o mandado tener por reconocido. Sin embargo, no será necesario este reconocimiento respecto del aceptante de una letra de cambio o subscriptor de un pagaré que no hayan puesto tacha de falsedad a su firma al tiempo de protestarse el documento por falta de pago, siempre que el protesto haya sido personal, ni respecto de cualquiera de los obligados al pago de una letra de cambio, pagaré o cheque, cuando, puesto el protesto en su conocimiento por notificación judicial, no alegue tampoco en ese mismo acto o dentro de tercero día tacha de falsedad.

Tendrá mérito ejecutivo, sin necesidad de reconocimiento previo, la letra de cambio, pagaré o cheque, respecto del obligado cuya firma aparezca autorizada por un notario o por el Oficial del Registro Civil en las comunas donde no tenga su asiento un notario.

5°. Confesión judicial;

6°. Cualesquiera títulos al portador, o nominativos, legítimamente emitidos, que representen obligaciones vencidas, y los cupones también vencidos de dichos títulos, siempre que los cupones confronten con los títulos, y éstos, en todo caso, con los libros talonarios.

Resultando conforme la confrontación, no será obstáculo a que se despache la ejecución la protesta de falsedad del título que en el acto haga el director o la persona que tenga la representación del deudor, quien podrá alegar en forma la falsedad como una de las excepciones del juicio; y

7°. Cualquiera otro título a que las leyes den fuerza ejecutiva.

**Art. 435 (457).** Si, en caso de no tener el acreedor título ejecutivo, quiere preparar la ejecución por el reconocimiento de firma o por la confesión de la deuda, podrá pedir que se cite al deudor a la presencia judicial, a fin de que practique la que corresponda de estas diligencias.

Y, si el citado no comparece, o sólo da respuestas evasivas, se dará por reconocida la firma o por confesada la deuda.

**Art. 436 (458).** Reconocida la firma, quedará preparada la ejecución, aunque se niegue la deuda.

**Art. 437 (459).** Para que proceda la ejecución, se requiere además que la obligación sea actualmente exigible.

**Art. 438 (460).** La ejecución puede recaer:

1°. Sobre la especie o cuerpo cierto que se deba y que exista en poder del deudor;

2°. Sobre el valor de la especie debida y que no exista en poder del deudor, haciéndose su avaluación por un perito que nombrará el tribunal; y

3°. Sobre cantidad líquida de dinero o de un género determinado cuya avaluación pueda hacerse en la forma que establece el número anterior.

Se entenderá cantidad líquida, no sólo la que actualmente tenga esta calidad, sino también la que pueda liquidarse mediante simples operaciones aritméticas con sólo los datos que el mismo título ejecutivo suministre.

El acreedor expresará en la demanda ejecutiva la especie o la cantidad líquida por la cual pide el mandamiento de ejecución.

Sin embargo, tratándose de moneda extranjera, no será necesario proceder a su avaluación, sin perjuicio de las reglas que para su liquidación y pago se expresan en otras disposiciones de este Código.

**Art. 439 (461).** Si del título aparece una obligación en parte líquida e ilíquida en otra, podrá procederse ejecutivamente por la primera, reservándose al acreedor su derecho para reclamar el resto en vía ordinaria.

**Art. 440 (462).** La avaluación que, en conformidad al artículo 438, se haga para determinar el monto de la ejecución, se entenderá sin perjuicio del derecho de las partes para pedir que se aumente o disminuya.

**Art. 441 (463).** El tribunal examinará el título y despachará o denegará la ejecución, sin audiencia ni notificación del demandado, aun cuando se haya éste apersonado en el juicio.

Las gestiones que en tal caso haga el demandado no embarazarán en manera alguna el procedimiento ejecutivo, y sólo podrán ser estimadas por el tribunal como datos ilustrativos para apreciar la procedencia o improcedencia de la acción.

Si denegado el mandamiento de ejecución, se interpone apelación de este fallo y ha lugar a ella, el tribunal elevará el proceso al superior, también sin notificación del demandado.

**Art. 442 (464).** El tribunal denegará la ejecución si el título presentado tiene más de tres años, contados desde que la obligación se haya hecho exigible; salvo que se compruebe la subsistencia de la acción ejecutiva por alguno de los medios que sirven para deducir esta acción en conformidad al artículo 434.

**Art. 443 (465).** El mandamiento de ejecución contendrá:

1°. La orden de requerir de pago al deudor. Este requerimiento debe hacérsele personalmente; pero si no es habido, se procederá en conformidad al artículo 44, expresándose en la copia a que dicho artículo se refiere, a más del mandamiento, la designación del día, hora y lugar que fije el ministro de fe para practicar el requerimiento. No concurriendo a esta citación el deudor, se hará inmediatamente y sin más trámite el embargo.

Cuando el deudor haya sido notificado personalmente o con arreglo al artículo 44 para otra gestión anterior al requerimiento, se procederá a éste y a los demás trámites del juicio, en conformidad a lo establecido en los artículos 48 a 53. La designación del domicilio, exigida por el artículo 49, deberá hacerse en tal caso por el deudor dentro de los dos días subsiguientes a la notificación, o en su primera gestión si alguna hace antes de vencido este plazo;

2°. La de embargar bienes del deudor en cantidad suficiente para cubrir la deuda con sus intereses y las costas, si no paga en el acto; y

3°. La designación de un depositario provisional que deberá recaer en la persona que, bajo su responsabilidad, designe el acreedor o en persona de reconocida honorabilidad y solvencia, si el acreedor no la ha indicado. El acreedor podrá designar como depositario al mismo deudor o pedir que no se designe depositario.

No podrá recaer esta designación en empleados o dependientes a cualquier título del tribunal ni en persona que desempeñe el cargo de depositario en tres o más juicios seguidos ante el mismo juzgado.

Si la ejecución recae sobre cuerpo cierto, o si el acreedor en la demanda ha señalado, para que se haga el embargo, bienes que la ley permita embargar, el mandamiento contendrá también la designación de ellos.

Siempre que en concepto del tribunal haya fundado temor de que el mandamiento sea desobedecido, podrá solicitar, a petición de parte, el auxilio de la fuerza pública para proceder a su ejecución.

**Art. 444 (466).** Si la ejecución recae sobre una empresa o establecimiento mercantil o industrial, o sobre cosa o conjunto de cosas que sean complemento indispensable para su explotación, podrá el juez, atendidas las circunstancias y la cuantía del crédito, ordenar que el embargo se haga efectivo, o en los bienes designados por el acreedor, o en otros bienes del deudor, o en la totalidad de la industria misma, o en las utilidades que ésta produzca, o en parte de cualquiera de ellas.

Embargada la industria o las utilidades, el depositario que se nombre tendrá las facultades y deberes de interventor judicial; y para ejercer las que correspondan al cargo de depositario, procederá en todo caso con autorización del juez de la causa.

Si la ejecución recae sobre el simple menaje de la casa habitación del deudor, el embargo se entenderá hecho permaneciendo las especies en poder del mismo deudor, con el carácter de depositario, previa facción de un inventario en que se expresen en forma individual y detallada el estado y la tasación aproximada de las referidas especies que practicará el ministro de fe ejecutor. La diligencia que deberá extenderse será firmada por el ministro de fe que la practique, por el acreedor, si concurre, y por el deudor, quien, en caso de substracción, incurrirá en la sanción prevista en el número 1° del artículo 471 del Código Penal.

**Art. 445 (467).** No son embargables:

1°. Los sueldos, las gratificaciones y las pensiones de gracia, jubilación, retiro y montepío que pagan el Estado y las Municipalidades.

Sin embargo, tratándose de deudas que provengan de pensiones alimenticias decretadas judicialmente, podrá embargarse hasta el 50% de las prestaciones que reciba el alimentante en conformidad al inciso anterior;

2°. Las remuneraciones de los empleados y obreros en la forma que determinan los artículos 40 y 153 del Código del Trabajo;

3°. Las pensiones alimenticias forzosas;

4°. Las rentas periódicas que el deudor cobre de una fundación o que deba a la liberalidad de un tercero, en la parte que estas rentas sean absolutamente necesarias para sustentar la vida del deudor, de su cónyuge o conviviente civil y de los hijos que viven con él y a sus expensas;

5°. Los fondos que gocen de este beneficio, en conformidad a la Ley Orgánica del Banco del Estado de Chile y en las condiciones que ella determine;

6°. Las pólizas de seguro sobre la vida y las sumas que, en cumplimiento de lo convenido en ellas, pague el asegurador. Pero, en este último caso, será embargable el valor de las primas pagadas por el que tomó la póliza;

7°. Las sumas que se paguen a los empresarios de obras públicas durante la ejecución de los trabajos. Esta disposición no tendrá efecto respecto de lo que se adeude a los artífices u obreros por sus salarios insolutos y de los créditos de los proveedores en razón de los materiales u otros artículos suministrados para la construcción de dichas obras;

8°. El bien raíz que el deudor ocupa con su familia, siempre que no tenga un avalúo fiscal superior a cincuenta unidades tributarias mensuales o se trate de una vivienda de emergencia, y sus ampliaciones, a que se refiere el artículo 5° del decreto ley N°2552, de 1979; los muebles de dormitorio, de comedor y de cocina de uso familiar y la ropa necesaria para el abrigo del deudor, su cónyuge o conviviente civil y los hijos que viven a sus expensas.

La inembargabilidad establecida en el inciso precedente no regirá para los bienes raíces respecto de los juicios en que sean parte el Fisco, Las Cajas de Previsión y demás organismos regidos por la ley del Ministerio de la Vivienda y Urbanismo;
 
9°. Los libros relativos a la profesión del deudor hasta el valor de cincuenta unidades tributarias mensuales y a elección del mismo deudor;

10°. Las máquinas e instrumentos de que se sirve el deudor para la enseñanza de alguna ciencia o arte, hasta dicho valor y sujetos a la misma elección;

11°. Los uniformes y equipos de los militares, según su arma y grado;

12°. Los objetos indispensables al ejercicio personal del arte u oficio de los artistas, artesanos y obreros de fábrica; y los aperos, animales de labor y material de cultivo necesarios al labrador o trabajador de campo para la explotación agrícola, hasta la suma de cincuenta unidades tributarias mensuales y a elección del mismo deudor;

13°. Los utensilios caseros y de cocina, y los artículos de alimento y combustible que existan en poder del deudor, hasta concurrencia de lo necesario para el consumo de la familia durante un mes;

14°. La propiedad de los objetos que el deudor posee fiduciariamente;

15°. Los derechos cuyo ejercicio es enteramente personal, como los de uso y habitación;

16°. Los bienes raíces donados o legados con la expresión de no embargables, siempre que se haya hecho constar su valor al tiempo de la entrega por tasación aprobada judicialmente; pero podrán embargarse por el valor adicional que después adquieran;

17°. Los bienes destinados a un servicio que no pueda paralizarse sin perjuicio del tránsito o de la higiene pública, como los ferrocarriles, empresas de agua potable o desagüe de las ciudades, etc.; pero podrá embargarse la renta líquida que produzcan, observándose en este caso lo dispuesto en el artículo anterior; y

18°. Los demás bienes que leyes especiales prohíban embargar.

Son nulos y de ningún valor los contratos que tengan por objeto la cesión, donación o transferencia en cualquier forma, ya sea a título gratuito u oneroso, de las rentas expresadas en el número 1° de este artículo o de alguna parte de ellas.

**Art. 446. (468).** Aunque pague el deudor antes del requerimiento, serán de su cargo las costas causadas en el juicio.

**Art. 447 (469).** Puede el acreedor concurrir al embargo y designar, si el mandamiento no lo hace, los bienes del deudor que hayan de embargarse, con tal que no excedan de los necesarios para responder a la demanda, haciéndose esta apreciación por el ministro de fe encargado de la diligencia, sin perjuicio de lo que resuelva el tribunal a solicitud de parte interesada.

**Art. 448. (470).** No designando el acreedor bienes para el embargo, se verificará éste en los que el deudor presente, si, en concepto del ministro de fe encargado de la diligencia, son suficientes o si, no siéndolo, tampoco hay otros conocidos.

**Art. 449. (471).** Si no designan bienes el acreedor ni el deudor, el ministro de fe guardará en el embargo el orden siguiente:

1° Dinero;
 
2° Otros bienes muebles;
 
3° Bienes raíces; y
 
4° Salarios y pensiones.

**Artículo 450.-** El embargo se entenderá hecho por la entrega real o simbólica de los bienes al depositario que se designe, aunque éste deje la especie en poder del mismo deudor.  A falta de depositario designado por el juez, hará las veces de tal el propio deudor hasta tanto se designe un depositario distinto.

El ministro de fe que practique el embargo deberá levantar un acta de la diligencia, la que señalará el lugar y hora en que éste se trabó, contendrá la expresión individual y detallada de los bienes embargados e indicará si fue necesario o no el auxilio de la fuerza pública para efectuarlo y de haberlo sido, la identificación del o de los funcionarios que intervinieron en la diligencia. Asimismo, dejará constancia de toda alegación que haga un tercero invocando la calidad de dueño o poseedor del bien embargado.

Tratándose del embargo de bienes muebles, el acta deberá indicar su especie, calidad y estado de conservación y todo otro antecedente o especificación necesarios para su debida singularización, tales como, marca, número de fábrica y de serie, colores y dimensiones aproximadas, según ello sea posible. En el embargo de bienes inmuebles, éstos se individualizarán por su ubicación y los datos de la respectiva inscripción de dominio.

El acta deberá ser suscrita por el ministro de fe que practicó la diligencia y por el depositario, acreedor o deudor que concurra al acto y que desee firmar.

Sin que ello afecte la validez del embargo, el ministro de fe deberá enviar carta certificada al ejecutado comunicándole el hecho del embargo, dentro de los dos días siguientes de la fecha de la diligencia o del día en que se reabran las oficinas de correo, si ésta se hubiere efectuado en domingo o festivo. El ministro de fe deberá dejar constancia en el proceso del cumplimiento de esta obligación, en los términos del artículo 46.

Toda infracción a las normas de este artículo hará responsable al ministro de fe de los daños y perjuicios que se originen y el tribunal, previa audiencia del afectado, deberá imponerle alguna de las medidas que se señalan en los números 2, 3 y 4 del artículo 532 del Código Orgánico de Tribunales.

**Art. 451. (473).** Los bienes embargados se pondrán a disposición del depositario provisional y éste, a su vez, los entregará al depositario definitivo que nombrarán las partes en audiencia verbal o el tribunal en caso de desacuerdo.

Si los bienes embargados se encuentran en territorios jurisdiccionales distintos o consisten en especies de distinta naturaleza, podrá nombrarse más de un depositario.

Cualquiera de las partes que ofrezca probar que el depositario no tiene responsabilidad bastante, será oída.

Si el embargo recae sobre dinero, alhajas, especies preciosas, o efectos públicos, el depósito deberá hacerse en un Banco o Caja Nacional de Ahorros a la orden del juez de la causa y el certificado del depósito se agregará a los autos.

**Art. 452.(474).** Si el deudor no concurre a la diligencia de embargo o si se niega a hacer la entrega al depositario, procederá a efectuarla el ministro de fe.

**Art. 453. (475).** Si el embargo recae sobre bienes raíces o derechos reales constituidos en ellos, no producirá efecto alguno legal respecto de terceros, sino desde la fecha en que se inscriba en el respectivo registro conservatorio en donde estén situados los situados los inmuebles.

El ministro de fe que practique el embargo, requerirá inmediatamente su inscripción y firmará con el conservador respectivo y retirará la diligencia en el plazo de veinticuatro horas.

**Art. 454. (476).** Cuando la cosa embargada se halle en poder de un tercero que se oponga a la entrega alegando el derecho de gozarla a otro título que el de dueño, no se hará alteración en este goce hasta el momento de la enajenación, ejerciendo mientras tanto el depositario sobre la cosa los mismos derechos que ejercía el deudor.

Lo cual se entiende sin perjuicio del derecho que corresponda al tenedor de la cosa embargada para seguir gozándola aún después de su enajenación.

**Art. 455. (477).** Verificado el embargo, el ministro de fe ejecutor entregará inmediatamente la diligencia en la secretaría, y el secretario pondrá testimonio del día en que la recibe.

En el caso del artículo 453, esta entrega se verificará inmediatamente después de practicada la inscripción de que dicho artículo trata.

El retiro de las especies no podrá decretarse sino hasta transcurridos que sean diez días desde la fecha de la traba de embargo, a menos que el juez, por resolución fundada, ordene otra cosa.

**Art. 456. (478).** Puede el acreedor pedir ampliación del embargo en cualquier estado del juicio, siempre que haya justo motivo para temer que los bienes embargados no basten para cubrir la deuda y las costas.

El haber recaído el embargo sobre bienes difíciles de realizar, será siempre justo motivo para la ampliación. Lo será también la introducción de cualquier tercería sobre los bienes embargados.

Pedida la ampliación después de la sentencia definitiva, no será necesario el pronunciamiento de nueva sentencia para comprender en la realización los bienes agregados al embargo.

**Art. 457. (479).** Puede el deudor en cualquier estado del juicio substituir el embargo, consignando una cantidad suficiente para el pago de la deuda y las costas, siempre que éste no recaiga en la especie o cuerpo cierto a que se refiere la ejecución.

**Art. 458. (480).** Se formará ramo separado con las diligencias relativas al embargo, a su ampliación y al procedimiento de apremio, que tiene por objeto realizar los bienes embargados y hacer pago al acreedor.

Se pondrá testimonio en el ramo principal, de la fecha en que se practique el embargo y la ampliación.

Este cuaderno se tramitará independientemente del cuaderno ejecutivo, sin que la marcha del uno se retarde por los recursos que en el otro se deduzcan.

**Art. 459. (481).** Si el deudor es requerido de pago en el lugar del asiento del tribunal, tendrá el término de cuatro días útiles para oponerse a la ejecución.

Este término se ampliará con cuatro días, si el requerimiento se hace dentro del territorio jurisdiccional en que se ha promovido el juicio, pero fuera de la comuna del asiento del tribunal.

**Art. 460. (482).** Si el requerimiento se hace en territorio jurisdiccional de otro tribunal de la República, la oposición podrá presentarse ante el el tribunal que haya ordenado cumplir el exhorto del que conoce en el juicio o ante este último tribunal. En el primer caso, los plazos serán los mismos que establece el artículo anterior. En el segundo, el ejecutado deberá formular su oposición en el plazo fatal de ocho días, más el aumento del término de emplazamiento en conformidad a la tabla de que trata el artículo 259.

El tribunal exhortado se limitará a remitir la solicitud de oposición al exhortante para que éste provea sobre ella lo que sea de derecho.

**Art. 461. (483).** Si se verifica el requerimiento fuera del territorio de la República, el término para deducir oposición será el que corresponda según la tabla a que se refiere el artículo 259, como aumento extraordinario del plazo para contestar una demanda.

**Art. 462. (484).** El término para deducir la oposición comienza a correr desde el día del requerimiento de pago.

Si el requerimiento se verifica dentro de la República, el ministro de fe hará saber al deudor, en el mismo acto, el término que la ley concede para deducir la oposición y dejará testimonio de este aviso en la diligencia. La omisión del ministro de fe le hará responsable de los perjuicios que puedan resultar, pero no invalidará el requerimiento.

**Art. 463. (485).** Los términos que se expresan en los cuatro artículos anteriores son fatales.

**Art. 464. (486).** La oposición del ejecutado sólo será admisible cuando se funde en alguna de las excepciones siguientes:

1a. La incompetencia del tribunal ante quien se haya presentado la demanda;
 
2a. La falta de capacidad del demandante o de personería o representación legal del que comparezca en su nombre;
 
3a. La litis pendencia ante tribunal competente, siempre que el juicio que le da origen haya sido promovido por el acreedor, sea por vía de demanda o de reconvención;

4a. La ineptitud de libelo por falta de algún requisito legal en el modo de formular la demanda, en conformidad a lo dispuesto en el artículo 254;
 
5a. El beneficio de excusión o la caducidad de la fianza;
 
6a. La falsedad del título;
 
7a. La falta de alguno de los requisitos o condiciones establecidos por las leyes para que dicho título tenga fuerza ejecutiva, sea absolutamente, sea con relación al demandado;
 
8a. El exceso de avalúo en los casos de los incisos 2° y 3° del artículo 438;
 
9a. El pago de la deuda;
 
10a. La remisión de la misma;
 
11a. La concesión de esperas o la prórroga del plazo;
 
12a. La novación;
 
13a. La compensación;
 
14a. La nulidad de la obligación;
 
15a. La pérdida de la cosa debida, en conformidad a lo dispuesto en el Título XIX, Libro IV del Código Civil;
 
16a. La transacción;
 
17a. La prescripción de la deuda o sólo de la acción ejecutiva; y
 
18a. La cosa juzgada.

Estas excepciones pueden referirse a toda la deuda o a una parte de ella solamente.	

**Art. 465. (487).** Todas las excepciones deberán oponerse en un mismo escrito, expresándose con claridad y precisión los hechos y los medios de prueba de que el deudor intente valerse para acreditarlas. No obstará para que se deduzca la excepción de incompetencia, el hecho de haber intervenido el demandado en las gestiones del demandante para preparar la acción ejecutiva.Deducida esta excepción, podrá el tribunal pronunciarse sobre ella desde luego, o reservarla para la sentencia definitiva. 	

**Art. 466. (488).** Del escrito de oposición se comunicará traslado al ejecutante, dándosele copia de él, para que dentro de cuatro días exponga lo que juzgue oportuno.

Vencido este plazo, haya o no hecho observaciones el demandante, se pronunciará el tribunal sobre la admisibilidad o inadmisibilidad de las excepciones alegadas.

Si las estima inadmisibles, o si no considera necesario que se rinda prueba para resolver, dictará desde luego sentencia definitiva. En caso contrario, recibirá a prueba la causa.

**Art. 467. (489).** El ejecutante podrá sólo dentro del plazo de cuatro días que concede el inciso 1° del artículo anterior, desistirse de la demanda ejecutiva, con reserva de su derecho para entablar acción ordinaria sobre los mismos puntos que han sido materia de aquélla.

Por el desistimiento perderá el derecho para deducir nueva acción ejecutiva, y quedarán ipso facto sin valor el embargo y demás resoluciones dictadas.

Responderá el ejecutante de los perjuicios que se hayan causado con la demanda ejecutiva, salvo lo que se resuelva en el juicio ordinario.

**Art. 468. (490).** Cuando haya de recibirse a prueba la causa, el término para rendirla será de diez días.

Podrá ampliarse este término hasta diez días más, a petición del acreedor. La prórroga deberá solicitarse antes de vencido el término legal, y correrá sin interrupción después de éste.

Por acuerdo de ambas partes, podrán concederse los términos extraordinarios que ellas designen.

**Art. 469. (491).** La prueba se rendirá del mismo modo que en el juicio ordinario, y el fallo que dé lugar a ella expresará los puntos sobre que deba recaer. Vencido el término probatorio, tendrán las partes seis días para hacer por escrito las observaciones que el examen de la prueba sugiera. Vencido este plazo, háyanse o no presentado escritos, y sin nuevo trámite, el tribunal citará a las partes para oír sentencia.

**Art. 470. (492).** La sentencia definitiva deberá pronunciarse dentro del término de diez días, contados desde que el pleito quede concluso.

**Art. 471. (493).** Si en la sentencia definitiva se manda seguir adelante en la ejecución, se impondrán las costas al ejecutado.

Y, por el contrario, si se absuelve al ejecutado, se condenará en las costas al ejecutante.

Si se admiten sólo en parte una o más excepciones, se distribuirán las costas proporcionalmente; pero podrán imponerse todas ellas al ejecutado cuando en concepto del tribunal haya motivo fundado.

**Art. 472. (494).** Si no se oponen excepciones, se omitirá la sentencia y bastará el mandamiento de ejecución para que el acreedor pueda perseguir la realización de los bienes embargados y el pago, de conformidad a las disposiciones del procedimiento de apremio.

**Art. 473. (495).** Si, deduciendo el ejecutado oposición legal, expone en el mismo acto que no tiene medios de justificarla en el término de prueba, y pide que se le reserve su derecho para el juicio ordinario y que no se haga pago al acreedor sin que caucione previamente las resultas de este juicio, el tribunal dictará sentencia de pago o remate y accederá a la reserva y caución pedidas.

**Art. 474. (496).** Si, en el caso del artículo precedente, no entabla el deudor su demanda ordinaria en el término de quince días, contado desde que se le notifique la sentencia definitiva, se procederá a ejecutar dicha sentencia sin previa caución, o quedará ésta ipso facto cancelada, si se ha otorgado.

**Art. 475. (497).** Si se interpone apelación de la sentencia de pago, no podrá procederse a la ejecución de esta sentencia, pendiente el recurso, sino en caso que el ejecutante caucione las resultas del mismo.

**Art. 476. (498).** Derogado.

**Art. 477. (499).** La acción ejecutiva rechazada por incompetencia del tribunal, incapacidad, ineptitud del libelo o falta de oportunidad en la ejecución, podrá renovarse con arreglo a los preceptos de este Título.

**Art. 478. (500).** La sentencia recaída en el juicio ejecutivo produce cosa juzgada en el juicio ordinario, tanto respecto del ejecutante como del ejecutado.

Con todo, si antes de dictarse sentencia en el juicio ejecutivo, el actor o el procesado piden que se les reserven para el ordinario sus acciones o excepciones, podrá el tribunal declararlo así, existiendo motivos calificados. Siempre se concederá la reserva respecto de las acciones y excepciones que no se refieran a la existencia de la obligación misma que ha sido objeto de la ejecución.

En los casos del inciso precedente, la demanda ordinaria deberá interponerse dentro del plazo que señala el artículo 474, bajo pena de no ser admitida después.


***2. De la administración de los bienes embargados y del procedimiento de apremio***

**Art. 479. (501).** La administración de los bienes embargados correrá a cargo del depositario.

Si son muebles podrá el depositario trasladarlos al lugar que crea más conveniente, salvo que el ejecutado caucione la conservación de dichos bienes donde se encuentren.

Lo cual se entiende sin perjuicio de lo dispuesto en el inciso 1° del artículo 450 y 4° del artículo 451.

**Art. 480. (502).** Toda cuestión relativa a la administración de los bienes embargados o a la venta de los que se expresan en el artículo 483, que se suscite entre el ejecutante o el ejecutado y el depositario, se substanciará en audiencias verbales que tendrán lugar con solo el que asista.

**Art. 481. (503).** Notificada que sea la sentencia de remate, se procederá a la venta de los bienes embargados, de conformidad a los artículos siguientes.

**Art. 482. (504).** Los bienes muebles embargados se venderán en martillo, siempre que sea posible, sin necesidad de tasación. La venta se hará por el martillero designado por el tribunal que corresponda.

**Art. 483. (505).** Venderá el depositario en la forma más conveniente, sin previa tasación, pero con autorización judicial, los bienes muebles sujetos a corrupción, o susceptibles de próximo deterioro, o cuya conservación sea difícil o muy dispendiosa.

**Art. 484. (506).** Los efectos de comercio realizables en el acto, se venderán sin previa tasación, por un corredor nombrado en la forma que establece el artículo 414.

**Art. 485. (507).** Los demás bienes no comprendidos en los tres artículos anteriores, se tasarán y venderán en remate público ante el tribunal que conoce de la ejecución, o ante el tribunal dentro de cuya jurisdicción estén situados los bienes, cuando así se resuelva a solicitud de partes y por motivos fundados.

**Art. 486. (508).** La tasación será la que figure en el rol de avalúos que esté vigente para los efectos de la contribución de haberes, a menos que el ejecutado solicite que se haga nueva tasación.

En este caso la tasación se practicará por peritos nombrados en la forma que dispone el artículo 414, haciéndose el nombramiento en la audiencia del segundo día hábil después de notificada la sentencia sin necesidad de nueva notificación.

En el caso que la designación de peritos deba hacerla el tribunal, no podrá recaer en empleados o dependientes a cualquier título del mismo tribunal.

Puesta en conocimiento de las partes la tasación, tendrán el término de tres días para impugnarla.

De la impugnación de cada parte se dará traslado a la otra por igual término.

**Art. 487. (509).** Transcurridos los plazos que expresa el artículo anterior, y aun cuando no hayan evacuado las partes el traslado de las impugnaciones, resolverá sobre ellas el tribunal, sea aprobando la tasación, sea mandando que se rectifique por el mismo o por otro perito, sea fijando el tribunal por sí mismo el justiprecio de los bienes. Estas resoluciones son inapelables.

Si el tribunal manda rectificar la tasación, expresará los puntos sobre que deba recaer la rectificación; y practicada ésta, se tendrá por aprobada, sin aceptarse nuevos reclamos.

**Art. 488. (510).** Aprobada la tasación, se señalará día y hora para la subasta.

**Artículo 489.-** El remate, con el señalamiento del día y hora en que debe tener lugar, se anunciará por medio de avisos publicados, a lo menos por cuatro veces en un diario de la comuna en que tenga su asiento el tribunal, o de la capital de la provincia o de la capital de la región, si en aquélla no lo hubiere. Los avisos podrán publicarse también en días inhábiles. El primero de los avisos deberá ser publicado con quince días de anticipación, como mínimo, sin descontar los inhábiles, a la fecha de la subasta.

Si los bienes están en otra comuna, el remate se anunciará también en ella o en la capital de la respectiva región, si fuere el caso, por el mismo tiempo y en la misma forma.

Los avisos serán redactados por el secretario y contendrán los datos necesarios para identificar los bienes que van a rematarse.

**Art. 490. (512).** Antes de verificarse el remate, puede el deudor libertar sus bienes pagando la deuda y las costas.

**Art. 491. (513).** El precio de los bienes que se rematen deberá pagarse de contado, salvo que las partes acuerden o que el tribunal, por motivos fundados, resuelva otra cosa.

Las demás condiciones para la subasta se propondrán por el ejecutante, con citación de la contraria.  La oposición que se formule será resuelta de plano por el tribunal, consultando la mayor facilidad y el mejor resultado de la enajenación.

**Art. 492. (514).** Si por un acreedor hipotecario de grado posterior se persigue una finca hipotecada contra el deudor personal que la posea, el acreedor o los acreedores de grado preferente, citados conforme al artículo 2428 del Código Civil, podrán, o exigir el pago de sus créditos sobre el precio del remate según sus grados, o conservar sus hipotecas sobre la finca subastada, siempre que sus créditos no estén devengados.

No diciendo nada, en el término del emplazamiento, se entenderá que optan por ser pagados sobre el precio de la subasta.

Si se ha dictado la resolución de reorganización que incluya los bienes del poseedor de la finca perseguida, o ha sido sometido a un procedimiento concursal de liquidación, se estará a lo prescrito en el artículo 2477 de dicho Código.

Los procedimientos a que den lugar las disposiciones anteriores, se verificarán en audiencias verbales con el interesado o los interesados que concurran.

**Art. 493. (515).** Salvo el caso de convenio expreso de las partes, no se admitirá postura que baje de los dos tercios de la tasación. 	

**Art. 494. (516).** Todo postor, para tomar parte en el remate, deberá rendir caución suficiente, calificada por el tribunal, sin ulterior recurso, para responder de que se llevará a efecto la compra de los bienes rematados. La caución será equivalente al diez por ciento de la valoración de dichos bienes y subsistirá hasta que se otorgue la escritura definitiva de compraventa, o se deposite a la orden del tribunal el precio o parte de él que deba pagarse de contado.

Si no se consigna el precio del remate en la oportunidad fijada en las bases, las que el secretario hará saber en el momento de la licitación, o el subastador no suscribe la escritura definitiva de compraventa, el remate quedará sin efecto y se hará efectiva la caución. El valor de ésta, deducido el monto de los gastos del remate, se abonará en un cincuenta por ciento al crédito y el cincuenta por ciento restante quedará a beneficio de la Junta de Servicios Judiciales.

Se concederán sólo en el efecto devolutivo las apelaciones que interponga el subastador de los bienes embargados.	

**Art. 495. (517).** El acta de remate de la clase de bienes a que se refiere el inciso 2° del artículo 1801 del Código Civil, se extenderá en el registro del secretario que intervenga en la subasta, y será firmada por el juez, el rematante y el secretario.

Esta acta valdrá como escritura pública, para el efecto del citado artículo del Código Civil; pero se extenderá sin perjuicio de otorgarse dentro de tercero día la escritura definitiva con inserción de los antecedentes necesarios y con los demás requisitos legales.

Los secretarios que no sean también notarios llevarán un registro de remates, en el cual asentarán las actas de que este artículo trata.

**Art. 496. (518).** En el acta de remate podrá el rematante indicar la persona para quien adquiere; pero mientras ésta no se presente aceptando lo obrado, subsistirá la responsabilidad del que ha hecho las posturas.

Subsistirá también la garantía constituida para tomar parte en la subasta, de conformidad al artículo 494.

**Art. 497. (519).** Para los efectos de la inscripción, no admitirá el conservador sino la escritura definitiva de compraventa. Dicha escritura será subscrita por el rematante y por el juez, como representante legal del vendedor, y se entenderá autorizado el primero para requerir y firmar por sí solo la inscripción en el Conservador, aun sin mención expresa de esta facultad.

**Art. 498. (520).** En todo caso, se dejará en el proceso un extracto del acta de remate.

**Art. 499. (521).** Si no se presentan postores en el día señalado, podra el acreedor solicitar cualesquiera de estas dos cosas, a su elección:

1a. Que se le adjudiquen por los dos tercios de la tasación los bienes embargados; y

2a. Que se reduzca prudencialmente por el tribunal el avalúo aprobado. La reducción no podrá exceder de una tercera parte de este avalúo.

**Art. 500. (522).** Si puestos a remate los bienes embargados por los dos tercios del nuevo avalúo, hecho de conformidad al número 2° del artículo anterior, tampoco se presentan postores, podrá el acreedor pedir cualquiera de estas tres cosas, a su elección:

1a. Que se le adjudiquen los bienes por los dichos dos tercios;

2a. Que se pongan por tercera vez a remate, por el precio que el tribunal designe; y

3a. Que se le entreguen en prenda pretoria.

Si la ejecución fuere en moneda extranjera, para hacer uso del derecho que confiere el número 1° del artículo anterior e igual número del presente artículo, el ejecutante deberá hacer liquidar su crédito en moneda nacional, al tipo medio de cambio libre que certifique un Banco de la plaza.

**Art. 501. (523).** Cuando el acreedor pida, conforme a lo dispuesto en el artículo anterior, que se le entreguen en prenda pretoria los bienes embargados, podrá el deudor solicitar que se pongan por última vez a remate. En este caso no habrá mínimum para las posturas.	

**Art. 502. (524).** Cuando haya de procederse a nuevo remate en los casos determinados por los tres artículos precedentes, se observará lo dispuesto en el artículo 489, reduciéndose a la mitad los plazos fijados para los avisos. No se hará, sin embargo, reducción alguna de estos plazos, si han transcurrido más de tres meses desde el día designado para el anterior remate hasta aquel en que se solicite la nueva subasta.

**Art. 503. (525).** La entrega de los bienes en prenda pretoria se hará bajo inventario solemne.

**Art. 504. (526).** El acreedor a quien se entreguen bienes muebles o inmuebles en prenda pretoria, deberá llevar cuenta exacta, y en cuanto sea dable documentada, de los productos de dichos bienes. Las utilidades líquidas que de ellos obtenga se aplicarán al pago del crédito, a medida que se perciban.

Para calcular las utilidades se tomarán en cuenta, a más de los otros gastos de legítimo abono, el interés corriente de los capitales propios que el acreedor invierta y la cantidad que el tribunal fije como remuneración de los servicios que preste como administrador. No tendrá, sin embargo, derecho a esta remuneración el acreedor que no rinda cuenta fiel de su administración, o que se haga responsable de dolo o culpa grave.

**Art. 505. (527).** Salvo estipulación en contrario, podrá el deudor, en cualquier tiempo, pedir los bienes dados en prenda pretoria pagando la deuda y las costas, incluso todo lo que el acreedor tenga derecho a percibir de conformidad a lo dispuesto en el último inciso del artículo precedente.

Podrá también el acreedor, en cualquier tiempo, poner fin a la prenda pretoria y solicitar su enajenación o el embargo de otros bienes del deudor, de conformidad a las reglas de este Título.

**Art. 506. (528).** El acreedor que tenga bienes en prenda pretoria, deberá rendir cuenta de su administración, cada año si son bienes inmuebles y cada seis meses si se trata de muebles, bajo la pena, si no lo hace, de perder la remuneración que le habría correspondido, de conformidad al inciso final del artículo 504, por los servicios prestados durante el año.

**Art. 507. (529).** Salvo lo dispuesto en los cuatro artículos precedentes, la prenda pretoria queda sujeta a las reglas del Título XXXIX, Libro IV del Código Civil.

Cuando se constituya en bienes muebles, tendrá además, sobre ellos, el que los reciba, los derechos y privilegios de un acreedor prendario. 	

**Art. 508. (530).** Si los bienes embargados consisten en el derecho de gozar una cosa o percibir sus frutos, podrá pedir el acreedor que se dé en arrendamiento o que se entregue en prenda pretoria este derecho.

El arrendamiento se hará en remate público, fijadas previamente por el tribunal, con audiencia verbal de las partes, las condiciones que hayan de tenerse como mínimum para las posturas.

Se anunciará al público el remate con anticipación de veinte días, en la forma y en los lugares expresados por el artículo 489.

**Art. 509. (531).** Los fondos que resulten de la realización de los bienes embargados se consignarán directamente por los compradores, o por los arrendatarios en el caso del artículo anterior, a la orden del tribunal que conozca de la ejecución, en la forma dispuesta en el artículo 507 del Código Orgánico de Tribunales.

Si se ha interpuesto apelación de la sentencia, no podrá procederse al pago al ejecutante, pendiente el recurso, sino en caso de que caucione las resultas del mismo.	

**Art. 510. (532).** Ejecutoriada la sentencia definitiva y realizados los bienes embargados, se hará la liquidación del crédito y se determinarán, de conformidad al artículo 471, las costas que deben ser de cargo al deudor, incluyéndose las causadas después de la sentencia.

Lo dispuesto en este artículo tendrá también aplicación en el caso previsto en el inciso 2° del artículo 509.

**Art. 511. (533).** Practicada la liquidación a que se refiere el artículo precedente, se ordenará hacer pago al acreedor con el dinero embargado o con el que resulte de la realización de los bienes de otra clase comprendidos en la ejecución.

Si la ejecución fuere en moneda extranjera, el tribunal pondrá a disposición del depositario los fondos embargados en moneda diferente a la adeudada sobre los cuales hubiere recaído el embargo y los provenientes de la realización de bienes del ejecutado en cantidad suficiente, a fin de que, por intermedio de un Banco de la plaza, se conviertan en la moneda extranjera que corresponda. Esta diligencia podrá también ser cometida al secretario.

**Art. 512. (534).** Si el embargo se ha trabado sobre la especie misma que se demanda, una vez ejecutoriada la sentencia de pago, se ordenará su entrega al ejecutante.

**Art. 513. (535).** Sin estar completamente reintegrado el ejecutante, no podrán aplicarse las sumas producidas por los bienes embargados a ningún otro objeto que no haya sido declarado preferente por sentencia ejecutoriada.

Las costas procedentes de la ejecución gozarán de preferencia aun sobre el crédito mismo.

**Art. 514. (536).** Luego que expire por cualquiera causa el cargo del depositario, éste rendirá cuenta de su administración en la forma que la ley establece para los tutores y curadores. Podrá, sin embargo, el tribunal, a solicitud de parte, ordenarle que rinda cuentas parciales antes de la terminación del depósito.

Presentada la cuenta, general o parcial, por el depositario, tendrán las partes el término de seis días para examinarla; y si se hacen reparos, se tramitarán como un incidente. 	

**Art. 515. (537).** El depositario deberá consignar a la orden del tribunal, en la forma expresada en el artículo 509, los fondos líquidos que obtenga correspondientes al depósito, tan pronto como lleguen a su poder; y abonará intereses corrientes por los que no haya consignado oportunamente.

**Art. 516. (538).** Al pronunciarse sobre la aprobación de la cuenta, fijará el tribunal la remuneración del depositario, si hay lugar a ella, teniendo en consideración la responsabilidad y trabajo que el cargo le haya impuesto.

La preferencia establecida por el inciso 2° del artículo 513 se extiende a la remuneración del depositario.

**Art. 517. (539).** No tienen derecho a remuneración:

1°. El depositario que, encargado de pagar el salario o pensión embargados, haya retenido a disposición del tribunal la parte embargable de dichos salarios o pensión; y
 
2°. El que se haga responsable de dolo o culpa grave.	

***3. De las tercerías.***

**Artículo 518.-** En el juicio ejecutivo sólo son admisibles las tercerías cuando el reclamante pretende:

1°. Dominio de los bienes embargados;

2°. Posesión de los bienes embargados;

3°. Derecho para ser pagado preferentemente; o

4°. Derecho para concurrir en el pago a falta de otros bienes.

En el primer caso la tercería se llama de dominio, en el segundo de posesión, en el tercero de prelación y en el cuarto de pago.

**Art. 519. (541).** Se substanciará en la forma establecida para las tercerías de dominio la oposición que se funde en el derecho del comunero sobre la cosa embargada.

Se tramitará como incidente la reclamación del ejecutado para que se excluya del embargo alguno de los bienes a que se refiere el artículo 445.

**Art. 520. (542).** Podrán también ventilarse conforme al procedimiento de las tercerías los derechos que haga valer el ejecutado invocando una calidad diversa de aquella en que se le ejecuta. Tales serían, por ejemplo, los casos siguientes:

1°. El del heredero a quien se ejecute en este carácter para el pago de las deudas hereditarias o testamentarias de otra persona cuya herencia no haya aceptado;
 
2°. El de aquél que, sucediendo por derecho de representación, ha repudiado la herencia de la persona a quien representa y es perseguido por el acreedor de ésta;
 
3°. El del heredero que reclame del embargo de sus bienes propios efectuado por acción de acreedores hereditarios o testamentarios que hayan hecho valer el beneficio de separación de que trata el Título XII del Libro III del Código Civil, y no traten de pagarse del saldo a que se refiere el artículo 1383 del mismo Código. Al mismo procedimiento se sujetará la oposición cuando se deduzca por los acreedores personales del heredero; y
 
4°. El del heredero beneficiario cuyos bienes personales sean embargados por deudas de la herencia, cuando esté ejerciendo judicialmente alguno de los derechos que conceden los artículos 1261 a 1263 inclusive del Código Civil.

El ejecutado podrá, sin embargo, hacer valer su derecho en estos casos por medio de la excepción que corresponda contra la acción ejecutiva, si a ello ha lugar.

**Artículo 521.-** La tercería de dominio se seguirá en ramo separado con el ejecutante y el ejecutado, por los trámites del juicio ordinario, pero sin escrito de réplica y dúplica. Las tercerías de posesión, de prelación y de pago se tramitarán como incidente.

El tercerista tendrá el mismo derecho que el artículo 457 concede al deudor principal.

**Artículo 522.-** La interposición de una tercería no suspenderá en caso alguno el procedimiento ejecutivo. El procedimiento de apremio se suspende únicamente en el caso contemplado en el inciso primero del artículo 523 y, tratándose de una tercería de posesión, sólo si se acompañan a ella antecedentes que constituyan a lo menos presunción grave de la posesión que se invoca.

**Art. 523. (545).** No se dará curso a la tercería de dominio si no contiene las enunciaciones que indica el artículo 254; ni se suspenderá por su interposición el procedimiento de apremio, salvo que se apoye en instrumento público otorgado con anterioridad a la fecha de la presentación de la demanda ejecutiva.

En los demás casos el remate se llevará a cabo, entendiéndose que la subasta recaerá sobre los derechos que el deudor tenga o pretenda tener sobre la cosa embargada.

Las resoluciones que se dicten son apelables y la apelación se concederá en el efecto devolutivo.

**Art. 524. (546).** En el caso del inciso 1° del artículo 519, podrá el acreedor dirigir su acción sobre la parte o cuota que en la comunidad corresponda al deudor para que se enajene sin previa liquidación, o exigir que con intervención suya se liquide la comunidad. En este segundo caso, podrán los demás comuneros oponerse a la liquidación, si existe algún motivo legal que la impida, o si, de procederse a ella, ha de resultar grave perjuicio.

**Art. 525. (547).** Si la tercería es de prelación, seguirá el procedimiento de apremio hasta que quede terminada la realización de los bienes embargados.

Verificado el remate, el tribunal mandará consignar su producto hasta que recaiga sentencia firme en la tercería.

**Art. 526. (548).** Si se han embargado o se embargan bienes no comprendidos en la tercería, seguirá sin restricción alguna respecto de ellos el procedimiento de apremio.

**Art. 527. (549).** Si no teniendo el deudor otros bienes que los embargados, no alcanzan a cubrirse con ellos los créditos del ejecutante y del tercerista, ni se justifica derecho preferente para el pago, se distribuirá el producto de los bienes entre ambos acreedores, proporcionalmente al monto de los créditos ejecutivos que hagan valer.

**Art. 528. (550).** Cuando la acción del segundo acreedor se deduzca ante diverso tribunal, podrá pedir se dirija oficio al que esté conociendo de la primera ejecución para que retenga de los bienes realizados la cuota que proporcionalmente corresponda a dicho acreedor.

Si existe depositario en la primera ejecución, no valdrá el nombramiento en las otras ejecuciones. El ejecutante que a sabiendas de existir depositario, o no pudiendo menos de saberlo, hace retirar las especies embargadas en la segunda ejecución por el nuevo depositario, será sancionado con las penas asignadas al delito de estafa.

**Art. 529. (551).** El tercerista de pago podrá solicitar la remoción del depositario alegando motivo fundado; y, decretada la remoción, se designará otro de común acuerdo por ambos acreedores, o por el tribunal si no se avienen.

Podrá también el tercerista intervenir en la realización de los bienes, con las facultades de coadyuvante. Con las mismas facultades podrá obrar el primer acreedor en la ejecución que ante otro tribunal deduzca el segundo.


	
## Título II. DEL PROCEDIMIENTO EJECUTIVO EN LAS OBLIGACIONES DE HACER Y DE NO HACER


**Art. 530. (557).** Hay acción ejecutiva en las obligaciones de hacer, cuando, siendo determinadas y actualmente exigibles, se hace valer para acreditarlas algún título que traiga aparejada ejecución de conformidad al artículo 434.

**Art. 531. (558).** Las reglas del párrafo 1° del Título anterior tendrán cabida en el procedimiento de que trata el presente Título, en cuanto sean aplicables y no aparezcan modificadas por los artículos siguientes.

**Art. 532. (559).** Si el hecho debido consiste en la suscripción de un instrumento o en la constitución de una obligación por parte del deudor, podrá proceder a su nombre el juez que conozca del litigio, si, requerido aquél, no lo hace dentro del plazo que le señale el tribunal.

**Art. 533. (560).** Cuando la obligación consista en la ejecución de una obra material, el mandamiento ejecutivo contendrá:

1°. La orden de requerir al deudor para que cumpla la obligación; y

2°. El señalamiento de un plazo prudente para que dé principio al trabajo.

**Art. 534. (561).** A más de las excepciones expresadas en el artículo 464, que sean aplicables al procedimiento de que trata este Título, podrá oponer el deudor la de imposibilidad absoluta para la ejecución actual de la obra debida.

**Art. 535. (562).** Si no se oponen excepciones, se omitirá la sentencia de pago, y bastará el mandamiento ejecutivo para que el acreedor haga uso de su derecho de conformidad a las disposiciones de los artículos siguientes.

**Art. 536. (563).** El acreedor podrá solicitar que se le autorice para llevar a cabo por medio de un tercero, y a expensas del deudor, el hecho debido, si a juicio de aquél es esto posible, siempre que no oponiendo excepciones el deudor se niegue a cumplir el mandamiento ejecutivo; y cuando desobedezca la sentencia que deseche las excepciones opuestas o deje transcurrir el plazo a que se refiere el número 2° del artículo 533, sin dar principio a los trabajos.

Igual solicitud podrá hacerse cuando, comenzada la obra, se abandone por el deudor sin causa justificada.

**Art. 537. (564).** Siempre que haya de procederse de conformidad al artículo anterior, presentará el demandante, junto con su solicitud, un presupuesto de lo que importe la ejecución de las obligaciones que reclama.

Puesto en noticia del demandado el presupuesto, tendrá el plazo de tres días para examinarlo, y si nada observa dentro de dicho plazo, se considerará aceptado.

Si se deducen objeciones, se hará el presupuesto por medio de peritos, procediéndose en la forma que establecen los artículos 486 y 487 para la estimación de los bienes en el caso de remate.

**Art. 538. (565).** Determinado el valor del presupuesto del modo que se establece en el artículo anterior, será obligado el deudor a consignarlo dentro de tercero día a la orden del tribunal, para que se entreguen al ejecutante los fondos necesarios, a medida que el trabajo lo requiera.

**Art. 539. (566).** Agotados los fondos consignados, podrá el acreedor solicitar aumento de ellos, justificando que ha habido error en el presupuesto o que han sobrevenido circunstancias imprevistas que aumentan el costo de la obra.

**Art. 540. (567).** Una vez concluida la obra, deberá el acreedor rendir cuenta de la inversión de los fondos suministrados por el deudor.

**Art. 541. (568).** Si el deudor no consigna a la orden del tribunal los fondos decretados, se procederá a embargarle y enajenar bienes suficientes para hacer la consignación, con arreglo a lo establecido en el Título precedente, pero sin admitir excepciones para oponerse a la ejecución.

**Art. 542. (569).** Si el acreedor no puede o no quiere hacerse cargo de la ejecución de la obra debida, de conformidad a las disposiciones que preceden, podrá usar de los demás recursos que la ley concede para el cumplimiento de las obligaciones de hacer, con tal que no haya el deudor consignado los fondos exigidos para la ejecución de la obra, ni se hayan rematado bienes para hacer la consignación en el caso del artículo 541.

**Art. 543. (570).** Cuando se pida apremio contra el deudor, podrá el tribunal imponerle arresto hasta por quince días o multa proporcional, y repetir estas medidas para obtener el cumplimiento de la obligación.

Cesará el apremio si el deudor paga las multas impuestas y rinde además caución suficiente, a juicio del tribunal, para asegurar la indemnización completa de todo perjuicio al acreedor.

**Art. 544. (571).** Las disposiciones que preceden se aplicarán también a la obligación de no hacer cuando se convierta en la de destruir la obra hecha, con tal que el título en que se apoye consigne de un modo expreso todas las circunstancias requeridas por el inciso 2° del artículo 1555 del Código Civil, y no pueda tener aplicación el inciso 3° del mismo artículo.

En el caso en que tenga aplicación este último inciso, se procederá en forma de incidente.


## Título III. DE LOS EFECTOS DEL DERECHO LEGAL DE RETENCION

**Art. 545. (697).** Para que sea eficaz el derecho de retención que en ciertos casos conceden las leyes, es necesario que su procedencia se declare judicialmente a petición del que pueda hacerlo valer.

Podrá solicitarse la retención como medida precautoria del derecho que garantiza, y, en tal caso, se procederá conforme a lo dispuesto en los artículos 299, 300 y 302.

**Art. 546. (698).** Los bienes retenidos por resolución ejecutoriada serán considerados, según su naturaleza, como hipotecados o constituidos en prenda para los efectos de su realización y de la preferencia a favor de los créditos que garantizan. El decreto judicial que declare procedente la retención de inmuebles deberá inscribirse en el Registro de Hipotecas.

**Art. 547. (699).** De la misma preferencia establecida en el artículo anterior gozarán las cauciones legales que se presten en substitución de la retención.

**Art. 548. (700).** Podrá el juez, atendidas las circunstancias y la cuantía del crédito, restringir la retención a una parte de los bienes muebles que se pretenda retener, que basten para garantizar el crédito mismo y sus accesorios.

	
## Título IV. DE LOS INTERDICTOS

***1. Definiciones y reglas generales***

**Art. 549. (701).** Los interdictos o juiciosNOTA 36 posesorios sumarios pueden intentarse:

1°. Para conservar la posesión de bienes raíces o de derechos reales constituidos en ellos;

2°. Para recuperar esta misma posesión;

3°. Para obtener el restablecimiento en la posesión o mera tenencia de los mismos bienes, cuando dicha posesión o mera tenencia hayan sido violentamente arrebatadas;

4°. Para impedir una obra nueva;

5°. Para impedir que una obra ruinosa o peligrosa cause daño; y

6°. Para hacer efectivas las demás acciones posesorias especiales que enumera el Título XIV, Libro II del Código Civil.

En el primer caso, el interdicto se llama querella de amparo; en el segundo, querella de restitución; en el tercero, querella de restablecimiento; en el cuarto, denuncia de obra nueva; en el quinto, denuncia de obra ruinosa; y en el último, interdicto especial.

**Art. 550. (703).** Las apelaciones en los juicios posesorios se concederán sólo en el efecto devolutivo, salvo que la ley expresamente las mande otorgar en ambos efectos o que el fallo apelado no dé lugar al interdicto; y en todo caso su tramitación se ajustará a las reglas establecidas para los incidentes.


***2. De las querellas posesorias en particular.***

**Art. 551. (704).** El que intente querella de amparo expresará en su demanda, a más de las circunstancias enumeradas en el artículo 254, las siguientes:

 1°. Que personalmente o agregando la de sus antecesores, ha estado en posesión tranquila y no interrumpida durante un año completo del derecho en que pretende ser amparado; y
 
 2°. Que se le ha tratado de turbar o molestar su posesión o que en el hecho se le ha turbado o molestado por medio de actos que expresará circunstanciadamente.

Si pide seguridades contra el daño que fundadamente teme, especificará las medidas o garantías que solicite contra el perturbador.

Deberán también expresarse en la querella los medios probatorios de que intente valerse el querellante; y, si son declaraciones de testigos, el nombre, profesión u oficio y residencia de éstos.

Si la querella es de restitución en lugar de la circunstancia del número 2° de este artículo, expresará que ha sido despojado de la posesión por medio de actos que indicará clara y precisamente.

Y si es de restablecimiento, la violencia con que ha sido despojado de la posesión o tenencia en que pretende ser restablecido.

**Art. 552. (705).** Presentada la querella, señalará el tribunal el quinto día hábil después de la notificación al querellado, para una audiencia, a la cual deberán concurrir las partes con sus testigos y demás medios probatorios.

Esta audiencia tendrá lugar con sólo la parte que asista.

**Art. 553. (706).** La notificación de la querella se practicará en conformidad a lo que dispone el Título VI del Libro I; pero en el caso del artículo 44 se hará la notificación en la forma indicada en el inciso 2° de dicho artículo, aunque el querellado no se encuentre en el lugar del juicio.

En estos casos, si el querellado no se ha hecho parte en primera instancia antes del pronunciamiento de la sentencia definitiva, se pondrá ésta en conocimiento del defensor de ausentes, quien podrá deducir y seguir los recursos a que haya lugar.

**Art. 554. (707).** Cuando el querellado quiera rendir prueba testimonial, deberá indicar el nombre, profesión u oficio y residencia de los testigos, en una lista que entregará en la secretaría y se agregará al proceso por lo menos antes de las doce del día que preceda al designado para la audiencia.

No se examinarán testigos que no estén mencionados en dichas listas, salvo acuerdo expreso de las partes.

**Art. 555. (708).** Cada parte sólo puede presentar hasta cuatro testigos sobre cada uno de los hechos que deben ser acreditados.

**Art. 556. (709).** Se interrogará a los testigos acerca de los hechos mencionados en la demanda, y de los que indiquen las partes en la audiencia, si el tribunal los estima pertinentes.

**Art. 557. (710).** Las tachas deberán oponerse a los testigos antes de su examen; y si no puede rendirse en la misma audiencia la prueba para justificarlas y el tribunal lo estima necesario para resolver el juicio, señalará una nueva audiencia con tal objeto, la cual deberá verificarse dentro de los tres días subsiguientes a la terminación del examen de los testigos de la querella.

**Art. 558. (711).** Cuando no alcance a rendirse toda la prueba en una sola audiencia, continuará el tribunal recibiéndola en los días hábiles inmediatos hasta concluir.

**Art. 559. (712).** Las reglas establecidas para el examen de los testigos y para sus tachas en el párrafo 3°, título XI del Libro II de este Código, son aplicables a la querella de amparo, en cuanto no aparezcan modificadas por los artículos precedentes. No se podrá en ningún caso hacer el examen de los testigos por otro tribunal que el que conozca de la querella.

**Art. 560. (713).** De todo lo obrado en la audiencia se levantará acta, expresándose con claridad y precisión lo expuesto por las partes y las pruebas presentadas.
	
**Artículo 561.-** Concluida la audiencia de prueba, el tribunal en el mismo acto citará a las partes para oír sentencia, la que deberá dictar de inmediato o, a lo más, en el plazo de los tres días subsiguientes.

**Art. 562. (715).** Si se da lugar a la querella, se condenará en costas al demandado.

En el caso contrario, al actor.

**Art. 563. (716).** Cualquiera que sea la sentencia, queda siempre a salvo a los que resulten condenados el ejercicio de la acción ordinaria que corresponda con arreglo a derecho, pudiendo comprenderse en dicha acción el resarcimiento de las costas y perjuicios que hayan pagado o que se les hayan causado con la querella.

No será admisible ninguna otra demanda que tienda a enervar lo resuelto en el interdicto. 	

**Art. 564. (721).** La sentencia pronunciada en la querella de restablecimiento deja a salvo a las partes, no sólo el ejercicio de la acción ordinaria en conformidad al artículo 563, sino también el de las acciones posesorias que les correspondan.


***3. De la denuncia de obra nueva.***

**Art. 565. (722).** Presentada la demanda para la suspensión de una obra nueva denunciable, el juez decretará provisionalmente dicha suspensión y mandará que se tome razón del estado y circunstancias de la obra y que se aperciba al que la esté ejecutando con la demolición o destrucción, a su costa, de lo que en adelante se haga. En la misma resolución mandará el tribunal citar al denunciante y al denunciado para que concurran a la audiencia del quinto día hábil después de la notificación del demandado, debiendo en ella presentarse los documentos y demás medios probatorios en que las partes funden sus pretensiones.

**Art. 566. (723).** No es necesaria la notificación del denunciado para llevar a efecto la suspensión decretada.

Bastará para esta suspensión la notificación del que esté dirigiendo o ejecutando la obra.

**Art. 567. (724).** Suspendida la obra, y mientras esté pendiente el interdicto, sólo podrá hacerse en ella lo que sea absolutamente indispensable para que no se destruya lo edificado.

Es necesaria la autorización del tribunal para ejecutar las obras a que se refiere el inciso precedente. El tribunal se pronunciará sobre esta autorización con la urgencia que el caso requiera, y procederá de plano, o, en caso de duda y para mejor proveer, oyendo el dictamen de un perito nombrado por él, el cual no podrá ser recusado.

**Art. 568. (725).** Si las partes quieren rendir prueba testimonial, se sujetarán a lo prevenido a este respecto en el párrafo 2° de este título.

Si alguna de las partes lo pide, y en concepto del tribunal son necesarios conocimientos periciales, se oirá el dictamen de un perito, que se expedirá dentro de un breve plazo que aquél señalará.

**Art. 569. (726).** Concluida la audiencia o presentado que sea el dictamen del perito, en su caso, el tribunal citará a las partes a oír sentencia, la que deberá dictar en el plazo de los tres días subsiguientes.

En la sentencia se ratificará la suspensión provisional decretada o se mandará alzarla, dejando a salvo, en todo caso, al vencido el ejercicio de las acciones ordinarias que le competan, para que se declare el derecho de continuar la obra o de hacerla demoler.

Podrá, sin embargo, el tribunal, a petición de parte, ordenar en la misma sentencia la demolición, cuando estime que el mantenimiento aún temporal de la obra ocasiona grave perjuicio al denunciante y dé éste suficiente caución para responder por los resultados del juicio ordinario.

La sentencia que ordene la demolición será apelable en ambos efectos.

En todo caso, la sentencia llevará condenación de costas.

**Art. 570. (727).** Si se ratifica la suspensión de la obra, podrá el vencido pedir autorización para continuarla, llenando las condiciones siguientes:

1a. Acreditar que de la suspensión de la obra se le siguen graves perjuicios;

2a. Dar caución suficiente para responder de la demolición de la obra y de la indemnización de los perjuicios que de continuarla puedan seguirse al contendor, en caso que a ello sea condenado por sentencia firme; y

3a. Deducir, al mismo tiempo de pedir dicha autorización, demanda ordinaria para que se declare su derecho de continuar la obra.

La primera de las condiciones expresadas y la calificación de la caución, serán materia de un incidente.


***4. De la denuncia de obra ruinosa***

**Art. 571. (728).** Si se pide la demolición o enmienda de una obra ruinosa o peligrosa, o el afianzamiento o extracción de árboles mal arraigados o expuestos a ser derribados por casos de ordinaria ocurrencia, el tribunal practicará, a la mayor brevedad, asociado de un perito nombrado por él mismo y con notificación de las partes y asistencia de la que concurra, una inspección personal de la construcción o árboles denunciados. Podrá también cada parte, si lo estima conveniente, asociarse para este acto de un perito; y en el acta que de lo obrado se levante se harán constar las opiniones o informes periciales, las observaciones conducentes que hagan los interesados y lo que acerca de ello note el juez que practica la diligencia.

Cuando el reconocimiento haya de practicarse a más de cinco kilómetros de distancia de los límites urbanos de la población en que funciona el tribunal, podrá éste cometer la diligencia al juez inferior que corresponda o a otro ministro de fe, quienes procederán asociados del perito que el tribunal designe y en la forma que dispone el inciso anterior.

**Artículo 572.-** Con el mérito de la diligencia ordenada por el artículo precedente, el tribunal en el acto citará a las partes a oír sentencia, la que deberá dictar de inmediato o en el plazo de los tres días subsiguientes, sea denegando lo pedido por el querellante, sea decretando la demolición, enmienda, afianzamiento o extracción a que haya lugar.

Cuando la diligencia de reconocimiento no haya sido practicada por el tribunal, podrá éste, como medida para mejor resolver, disponer que se rectifique o amplíe en los puntos que estime necesarios.

**Art. 573. (730).** Es aplicable a la denuncia de obra ruinosa lo dispuesto en el artículo 553.

**Art. 574. (731).** En la misma sentencia que ordena la demolición, enmienda, afianzamiento o extracción, puede el tribunal decretar desde luego las medidas urgentes de precaución que considere necesarias, y además que se ejecuten dichas medidas, sin que de ello pueda apelarse. 	

**Art. 575. (732).** Sin perjuicio de lo dispuesto en el artículo precedente, la apelación de la sentencia definitiva en este interdicto se concederá en ambos efectos.

**Art. 576. (733).** Cuando se dé lugar al interdicto, no se entenderá reservado el derecho de ejercer en vía ordinaria ninguna acción que tienda a dejar sin efecto lo resuelto.
	

***5. De los interdictos especiales***

**Art. 577. (734).** Si se pide la destrucción o modificación de la obras a que se refieren los artículos 936 y 937 del Código Civil, se procederá en la forma dispuesta por los artículos 571, 572, 573 y 574 del presente Código.

**Art. 578. (735).** Si por parte del querellado se alega que el interdicto no es admisible por haber transcurrido tiempo bastante para constituir un derecho de servidumbre, se dará a esta oposición la tramitación de un incidente y se recibirá a prueba, sin perjuicio de practicarse la inspección por el tribunal.

Para recibir esta prueba, el tribunal señalará la audiencia correspondiente al quinto día hábil después de la última notificación y a ella deberán concurrir las partes con sus testigos y demás medios probatorios. Dicha audiencia tendrá lugar con sólo el interesado que asista.

La parte que quiera rendir prueba testimonial deberá entregar en secretaría, para que se agregue al proceso antes de las doce del día que preceda al de la audiencia, una lista de los testigos de que piensa valerse, con expresión de su nombre, profesión u oficio y residencia.

Son aplicables en este caso las disposiciones de los artículos 555 a 561 inclusive.

**Art. 579. (736).** Las acciones que se conceden por los artículos 939, 941 y 942 del Código Civil, se sujetarán al procedimiento establecido en los artículos 571, 572, 573 y 574 del presente Código.

Si se alega la excepción a que se refiere el inciso final del artículo 941 del Código Civil, se procederá como lo dispone el artículo precedente.

**Art. 580. (737).** Si se pide la suspensión de las obras de que tratan los artículos 874, 875, 878 y 944 del Código Civil, el tribunal procederá como en el caso de la denuncia de obra nueva.

**Art. 581. (739).** Las sentencias que se dicten en los interdictos de que trata este párrafo dejan a salvo su derecho a las partes para deducir en vía ordinaria las acciones que por la ley les correspondan.

	
***6. Disposiciones comunes a los dos párrafos precedentes***

**Art. 582. (740).** Si la denuncia, en los casos a que se refieren los dos párrafos precedentes, se deduce por acción popular y se reclama la recompensa que establece el artículo 948 del Código Civil, se pronunciará sobre ella el tribunal en la misma sentencia que dé lugar al interdicto; pero la cuantía de esta recompensa la fijará prudencialmente dentro de los límites que señala dicho artículo, oyendo en audiencia verbal a los interesados, después de la ejecución de la sentencia.


**Art. 583. (741).** Lo dispuesto en los párrafos 4° y 5° de este Título se entiende sin perjuicio de las medidas administrativas o de policía a que haya lugar según las leyes.



## Título V. DE LA CITACION DE EVICCION

**Art. 584. (742).** La citación de evicción deberá hacerse antes de la contestación de la demanda.

Para que se ordene la citación de evicción deberán acompañarse antecedentes que hagan aceptable la solicitud.

**Art. 585. (743).** Decretada la citación, se suspenderán los trámites del juicio por el término de diez días si la persona a quien debe citarse reside en el territorio jurisdiccional en que se sigue el pleito. Si se encuentra en otro territorio jurisdiccional o fuera del territorio de la República, se aumentará dicho término en la forma establecida en el artículo 259.

Vencidos estos plazos sin que el demandado haya hecho practicar la citación, podrá el demandante pedir que se declare caducado el derecho de aquél para exigirla y que continúen los trámites del juicio, o que se le autorice para llevarla a efecto a costa del demandado.

**Art. 586. (744).** Las personas citadas de evicción tendrán para comparecer al juicio el término de emplazamiento que corresponda en conformidad a los artículos 258 y siguientes, suspendiéndose mientras tanto el procedimiento. Si a petición de ellas se hace igual citación a otras personas gozarán también éstas del mismo derecho.

**Art 587. (745).** Si comparecen al juicio las personas citadas, se observará lo dispuesto en el artículo 1844 del Código Civil, continuando los trámites de aquél según el estado que a la sazón tengan. En caso contrario, vencido el término de emplazamiento, continuará sin más trámite el procedimiento.



## Título VI. DE LOS JUICIOS ESPECIALES DEL CONTRATO DE ARRENDAMIENTO

***1. Del desahucio, del lanzamiento y de la retención***

**Art. 588. (746).** El desahucio de la cosa arrendada puede efectuarse judicial o extrajudicialmente.

La prueba del desahucio extrajudicial se sujetará a las reglas generales del Título XXI, Libro IV del Código Civil y a los procedimientos que establece el presente Código.

El desahucio judicial se efectuará notificando al arrendador o arrendatario, de conformidad al artículo 553, el decreto en que el juez manda poner en conocimiento de uno u otro la noticia anticipada a que se refiere el artículo 1951 del Código Civil.

**Art. 589. (747).** Cuando el arrendador o el arrendatario desahuciado reclame contra este desahucio, citará el tribunal a las partes para la audiencia del quinto día hábil después de la última notificación, a fin de que concurran con sus medios de prueba y expongan lo conveniente a sus derechos.

**Art. 590. (748).** Esta reclamación sólo podrá entablarse dentro de los diez días subsiguientes a la noticia del desahucio.

**Art. 591. (749).** La reclamación se notificará al que hace el desahucio en la forma que dispone el artículo 553, debiendo intervenir el defensor de ausentes en los casos y para los efectos que allí se expresan.

**Art. 592. (750).** La audiencia señalada tendrá lugar con sólo la parte que concurra.

Si ha de rendirse prueba testimonial, se procederá de conformidad con lo dispuesto en los artículos 554 y 560, inclusive.

**Artículo 593.-**   En el acta que se levante, a más de las pruebas acompañadas, se mencionarán con brevedad las alegaciones de las partes. Sin otro trámite el tribunal citará a las partes para oír sentencia la que dictará inmediatamente o, a más tardar, dentro de tercero día.

**Art. 594. (752).** Si la reclamación aparece interpuesta fuera del plazo que concede el artículo 590 o si los fundamentos en que se apoya no son legales, o no resultan comprobados, será desechada por el tribunal, manteniéndose el desahucio y designándose en la misma sentencia el día en que deba hacerse la restitución de la cosa arrendada.

En caso contrario, se declarará sin lugar el desahucio.

**Art. 595. (753).** Si, ratificado el desahucio, llega el día señalado para la restitución sin que el arrendatario haya desalojado la finca arrendada, éste será lanzado de ella a su costa, previa orden del tribunal notificada en la forma establecida por el artículo 48.

**Art. 596. (754).** Si el arrendatario desahuciado retarda la restitución de la cosa mueble arrendada, o si se trata de un desahucio de arrendamiento de servicios, se procederá a la ejecución de la sentencia de conformidad a las reglas generales.

**Art. 597. (755).** Cuando el arrendatario desahuciado reclame indemnizaciones, haciendo valer el derecho de retención que otorga el artículo 1937 del Código Civil, deberá interponer su reclamo dentro del plazo de diez días que concede el artículo 590 del presente Código, y se tramitará y fallará en la misma forma que la oposición al desahucio. El tribunal, sin perjuicio de lo que se establezca sobre el desahucio, resolverá si hay o no lugar a la retención solicitada.

**Art. 598. (756).** Si el arrendatario pretendiera burlar el derecho de retención que concede al arrendador el artículo 1942 del Código Civil extrayendo los objetos a que dicho artículo se refiere, podrá el arrendador solicitar el auxilio de cualquier funcionario de policía para impedir que se saquen esos objetos de la propiedad arrendada.

El funcionario de policía prestará este auxilio sólo por el término de dos días, salvo que transcurrido este plazo le exhiba el arrendador copia autorizada de la orden de retención expedida por el tribunal competente.

**Art. 599. (757).** Los gastos hechos por el arrendatario en la cosa arrendada con posterioridad al desahucio no le autorizarán para pedir su retención.

**Art. 600. (758).** Si, ratificado el desahucio y llegado el momento de la restitución, existe retención decretada a favor del arrendatario, y el arrendador no ha caucionado el pago de las indemnizaciones debidas, no podrá éste pedir lanzamiento sin que previamente pague dichas indemnizaciones o asegure su pago a satisfacción del tribunal.

**Art. 601. (759).** Si hay labores o plantíos que el arrendatario reclame como de su propiedad, o mejoras útiles cuyos materiales puede separar y llevarse sin detrimento de la cosa arrendada, se extenderá diligencia expresiva de la clase, extensión y estado de las cosas reclamadas.

Esta reclamación no será un obstáculo para el lanzamiento.

**Art. 602. (760).** En los casos a que se refiere el artículo precedente, se procederá al avalúo de las labores, plantíos o materiales reclamados, por peritos nombrados en la forma que expresa el artículo 414.

**Art. 603. (761).** Practicada esta diligencia, podrá el arrendatario reclamar el abono de la cantidad en que haya sido apreciado lo que crea corresponderle, o que se le permita separar y llevarse los materiales.

Esta reclamación se tramitará como incidente.

**Art. 604. (762).** El procedimiento establecido en este párrafo se observará también cuando se exija la restitución de la cosa arrendada por la expiración del tiempo estipulado para la duración del arrendamiento, o por la extinción del derecho del arrendador.

El plazo para oponerse a la restitución o para hacer valer el derecho de retención por indemnizaciones debidas, correrá desde que el que pide la terminación del arrendamiento haga saber a la otra parte su intención de exigirla.

Cuando se trate de bienes inmuebles, la misma sentencia que deseche la reclamación, ordenará además el lanzamiento, si está vencido el plazo del contrato; salvo que existan retenciones decretadas a favor del arrendatario por no haberse otorgado las cauciones a que se refiere el artículo 600.

**Art. 605. (763).** Cuando la terminación del arrendamiento resulte de sentencia judicial, en los casos previstos por la ley, podrá adoptarse el procedimiento del artículo anterior o el que corresponda para la ejecución de dicha sentencia, a elección de la parte a quien ella favorezca.

**Art. 606. (764).** Las sentencias en que se ratifique el desahucio o se ordene el lanzamiento, las que den lugar a la retención, y las que dispongan la restitución de la cosa arrendada, en los casos de los dos artículos anteriores, sólo serán apelables en el efecto devolutivo, y la apelación se tramitará como en los incidentes.


***2. De la terminación inmediata del arrendamiento.***

**Art. 607. (765).** Cuando la ley autorice al arrendador para pedir la terminación inmediata del arrendamiento, como en los casos previstos por los artículos 1972 y 1973 del Código Civil, señalará el tribunal la audiencia del quinto día hábil después de la notificación del demandado, a fin de que concurran las partes con sus medios de prueba y expongan lo conveniente a su derecho. Tendrá lugar la audiencia con sólo el interesado que asista.

Si ha de rendirse prueba testimonial, se procederá con arreglo a lo establecido en los dos últimos incisos del artículo 578.

**Art. 608. (766).** Es aplicable a la notificación de la demanda en este caso lo dispuesto por el artículo 553.

**Art. 609. (767).** Cuando el tribunal lo estime necesario podrá, antes de dictar sentencia, nombrar un perito que informe sobre los hechos alegados o practicar una inspección personal.

**Art. 610. (768).** Terminada la audiencia o practicadas las diligencias a que se refiere el artículo anterior, el tribunal citará de inmediato a las partes para oír sentencia, la que dictará, a más tardar, dentro de tercero día.

**Art. 611. (769).** Cuando la terminación del arrendamiento se pida por falta de pago de la renta, de conformidad a lo dispuesto por el artículo 1977 del Código Civil, la segunda de las reconvenciones a que dicho artículo se refiere, se practicará ocurriendo al tribunal respectivo, quien citará a las partes a una audiencia inmediata y procederá en lo demás con arreglo a lo establecido en los artículos precedentes.

Al ejercitarse la acción a que se refiere el inciso precedente podrá deducirse también la de cobro de las rentas insolutas en que aquélla se funde y la de los consumos de luz, gas, energía eléctrica, agua potable, riego u otras prestaciones análogas que se adeuden.

Tales peticiones se substanciarán y fallarán conjuntamente con la cuestión principal.

Demandadas estas prestaciones, se entenderán comprendidas en la acción las de igual naturaleza a las reclamadas que se devenguen durante la tramitación del juicio hasta la expiración del plazo que se haya fijado para la restitución o para el pago.

**Art. 612. (770).** El arrendador que pretenda hacer uso de los derechos concedidos por el artículo 1979 del Código Civil, se ajustará a lo establecido en el Título XI de este Libro sobre el procedimiento sumario.

**Art. 613. (771).** En los casos de los artículos 1989 y 2009 del Código Civil, la terminación del arrendamiento se someterá a las disposiciones del artículo 604.

**Art. 614. (772).** Cuando las sentencias dictadas en los casos de que trata el presente párrafo dieren lugar a la terminación del arrendamiento, sólo serán apelables en el efecto devolutivo, y el recurso se tramitará como en los incidentes.	


***3. Disposiciones comunes a los dos párrafos precedentes.***

**Art. 615. (773).** Las sentencias que se pronuncien en conformidad a los dos párrafos precedentes no privarán a las partes del ejercicio de las acciones ordinarias a que tengan derecho, sobre las mismas cuestiones resueltas por aquéllas.

**Art. 616. Derogado.



## Título VII. DE LOS JUICIOS SOBRE CONSENTIMIENTO PARA EL MATRIMONIO

**Art. 617.** Derogado.

**Art. 618.** Derogado.

**Art. 619.** Derogado.

**Art. 620.** Derogado.

**Art. 621.** Derogado.

**Art. 622.** Derogado.

**Art. 623.** Derogado.

**Art. 624.** Derogado.

**Art. 625.** Derogado.

**Art. 626.** Derogado.

**Art. 627.** Derogado.



## Título VII. IDEL JUICIO ARBITRAL

***1. Del juicio seguido ante árbitros de derecho.***

**Art. 628. (785).** Los árbitros de derecho se someterán, tanto en la tramitación como en el pronunciamiento de la sentencia definitiva, a las reglas que la ley establece para los jueces ordinarios, según la naturaleza de la acción deducida.

Sin embargo, en los casos en que la ley lo permita, podrán concederse al árbitro de derecho las facultades de arbitrador, en cuanto al procedimiento, y limitarse al pronunciamiento de la sentencia definitiva la aplicación estricta de la ley. La tramitación se ajustará en tal caso a las reglas del párrafo siguiente.

Por motivos de manifiesta conveniencia podrán los tribunales autorizar la concesión al árbitro de derecho de las facultades de que trata el inciso anterior, aun cuando uno o más de los interesados en el juicio sean incapaces.

**Art. 629. (786).** En los juicios arbitrales se harán las notificaciones personalmente o por cédula, salvo que las partes unánimemente acuerden otra forma de notificación.

**Art. 630. (787).** Si los árbitros son dos o más, todos ellos deberán concurrir al pronunciamiento de la sentencia y a cualquier acto de substanciación del juicio, a menos que las partes acuerden otra cosa.

No poniéndose de acuerdo los árbitros, se reunirá con ellos el tercero, si lo hay, y la mayoría pronunciará resolución.

**Art. 631. (788).** En caso de no resultar mayoría en el pronunciamiento de la sentencia definitiva o de otra clase de resoluciones, siempre que ellas no sean apelables, quedará sin efecto el compromiso, si éste es voluntario. Si es forzoso, se procederá a nombrar nuevos árbitros.

Cuando pueda deducirse el recurso, cada opinión se estimará como resolución distinta, y se elevarán los antecedentes al tribunal de alzada, para que resuelva como sea de derecho sobre el punto que haya motivado el desacuerdo de los árbitros.

**Art. 632. (789).** Toda la substanciación de un juicio arbitral se hará ante un ministro de fe designado por el árbitro, sin perjuicio de las implicancias o recusaciones que puedan las partes reclamar; y si está inhabilitado o no hay ministro de fe en el lugar del juicio, ante una persona que, en calidad de actuario, designe el árbitro.

Cuando el árbitro deba practicar diligencia fuera del lugar en que se siga el compromiso, podrá intervenir otro ministro de fe o un actuario designado en la forma que expresa el inciso anterior y que resida en el lugar donde dichas diligencias han de practicarse.

**Art. 633. (790).** No podrá el árbitro compeler a ningún testigo a que concurra a declarar ante él.

Sólo podrá tomar las declaraciones de los que voluntariamente se presten a darlas en esta forma.

Cuando alguno se niegue a declarar, se pedirá por conducto del árbitro al tribunal ordinario correspondiente que practique la diligencia, acompañándole los antecedentes necesarios para este objeto.

Los tribunales de derecho podrán cometer esta diligencia al árbitro mismo asistido por un ministro de fe.

**Art. 634. (791).** Para el examen de testigos y para cualquiera otra diligencia fuera del lugar del juicio, se procederá en la forma dispuesta por el inciso 2° del artículo precedente, dirigiéndose por el árbitro la comunicación que corresponda al tribunal que deba entender en dichas diligencias.

**Art. 635. (792).** Para la ejecución de la sentencia definitiva se podrá ocurrir al árbitro que la dictó, si no está vencido el plazo por que fue nombrado, o al tribunal ordinario correspondiente, a elección del que pida su cumplimiento.

Tratándose de otra clase de resoluciones, corresponde al árbitro ordenar su ejecución.

Sin embargo, cuando el cumplimiento de la resolución arbitral exija procedimientos de apremio o el empleo de otras medidas compulsivas, o cuando haya de afectar a terceros que no sean parte en el compromiso, deberá ocurrirse a la justicia ordinaria para la ejecución de lo resuelto.


***2. Del juicio seguido ante arbitradores***

**Art. 636. (793).** El arbitrador no está obligado a guardar en sus procedimientos y en su fallo otras reglas que las que las partes hayan expresado en el acto constitutivo del compromiso.

Si las partes nada han dicho a este respecto, se observarán las reglas establecidas en los artículos que siguen.

**Art. 637. (794).** El arbitrador oirá a los interesados; recibirá y agregará al proceso los instrumentos que le presenten; practicará las diligencias que estime necesarias para el conocimiento de los hechos, y dará su fallo en el sentido que la prudencia y la equidad le dicten.

Podrá oír a los interesados por separado, si no le es posible reunirlos.

**Art. 638. (795).** Si el arbitrador cree necesario recibir la causa a prueba, decretará este trámite.

Es aplicable a este caso lo dispuesto en los artículos 633 y 634.

**Art. 639. (796).** El arbitrador practicará solo o con asistencia de un ministro de fe, según lo estime conveniente, los actos de substanciación que decrete en el juicio, y consignará por escrito los hechos que pasen ante él y cuyo testimonio le exijan los interesados, si son necesarios para el fallo.

Las diligencias probatorias concernientes al juicio de compromiso que se practiquen ante los tribunales ordinarios se someterán a las reglas establecidas para éstos.

**Art. 640. (797).** La sentencia del arbitrador contendrá:

1°. La designación de las partes litigantes;

2°. La enunciación breve de las peticiones deducidas por el demandante;

3°. La misma enunciación de la defensa alegada por el demandado;

4°. Las razones de prudencia o de equidad que sirven de fundamento a la sentencia; y

5°. La decisión del asunto controvertido.

La sentencia expresará, además, la fecha y el lugar en que se expide; llevará al pie la firma del arbitrador, y será autorizada por un ministro de fe o por dos testigos en su defecto. 	

**Art. 641. (798).** Si son dos o más los arbitradores, deberán todos ellos concurrir al pronunciamiento de la sentencia y a cualquier otro acto de substanciación, salvo que las partes acuerden otra cosa.

Cuando no haya acuerdo entre los arbitradores, se llamará al tercero, si lo hay; y la mayoría formará resolución.

No pudiendo obtenerse mayoría en el pronunciamiento de la sentencia definitiva o de otra clase de resoluciones, quedará sin efecto el compromiso si no puede deducirse apelación. Habiendo lugar a este recurso, se elevarán los antecedentes a los arbitradores de segunda instancia, para que resuelvan como estimen conveniente sobre la cuestión que motiva el desacuerdo.

**Art. 642. (799).** Sólo habrá lugar a la apelación de la sentencia del arbitrador cuando las partes, en el instrumento en que constituyen el compromiso, expresen que se reservan dicho recurso para ante otros árbitros del mismo carácter y designen las personas que han de desempeñar este cargo.
	
**Art. 643. (800).** La ejecución de la sentencia de los arbitradores se sujetará a lo dispuesto en el artículo 635.


***3. Disposición común a los dos párrafos precedentes***

**Art. 644. (801).** Los expedientes fallados por árbitros o arbitradores se archivarán en la comuna o agrupación de comunas donde se haya constituido el compromiso, en el oficio del funcionario a quien correspondería su custodia si se hubiera seguido el juicio ante los tribunales ordinarios.



## Título IX. DE LOS JUICIOS SOBRE PARTICIÓN DE BIENES

**Art. 645. (802).** Derogado.

**Art. 646. (803).** Cuando haya de nombrarse partidor, cualquiera de los comuneros ocurrirá al tribunal que corresponda, pidiéndole que cite a todos los interesados a fin de hacer la designación, y se procederá a ella en la forma establecida para el nombramiento de peritos.

Si hay partidor nombrado por los interesados o por el difunto en el caso del artículo 1324 del Código Civil, y es necesaria la aprobación judicial del nombramiento en conformidad a la ley, bastará el fallo que la conceda para que el partidor pueda ejercer sus funciones, previa su aceptación y el juramento legal.

**Art. 647. (804).** El término que la ley, el testador o las partes concedan al partidor para el desempeño de su cargo se contará desde que éste sea aceptado, deduciendo el tiempo durante el cual, por la interposición de recursos o por otra causa, haya estado totalmente interrumpida la jurisdicción del partidor.

**Art. 648. (805).** Se extenderán a los partidores las reglas establecidas respecto de los árbitros en el Título precedente, en cuanto no aparezcan modificadas por las del presente Título y sean aplicables a las cuestiones que aquéllos deben resolver. Sin embargo, las partes mayores de edad y libres administradores de sus bienes, podrán darles el carácter de arbitradores.

Los actos de los partidores serán en todo caso autorizados por un secretario de los Tribunales Superiores de Justicia, o por un notario o secretario de un juzgado de letras.

**Art. 649. (806).** Las materias sometidas al conocimiento del partidor se ventilarán en audiencias verbales, consignándose en las respectivas actas sus resultados; o por medio de solicitudes escritas, cuando la naturaleza e importancia de las cuestiones debatidas así lo exijan. Las resoluciones que se dicten con tal objeto serán inapelables. 	

**Art. 650. (807).** Cuando se designen días determinados para las audiencias ordinarias, se entenderá que en ellas pueden celebrarse válidamente acuerdos sobre cualquiera de los asuntos comprendidos en el juicio, aun cuando no estén presentes todos los interesados, a menos que se trate de revocar acuerdos ya celebrados, o que sea necesario el consentimiento unánime en conformidad a la ley o a los acuerdos anteriores de las partes.

Modificada la designación de día para las audiencias ordinarias, no producirá efecto mientras no se notifique a todos los que tengan derecho de concurrir.	

**Art. 651. (808).** Entenderá el partidor en todas las cuestiones relativas a la formación e impugnación de inventarios y tasaciones, a las cuentas de los albaceas, comuneros y administradores de los bienes comunes, y en todas las demás que la ley especialmente le encomiende, o que, debiendo servir de base para la repartición, no someta la ley de un modo expreso al conocimiento de la justicia ordinaria.

Lo cual se entiende sin perjuicio de la intervención de la justicia ordinaria en la formación de los inventarios, y del derecho de los albaceas, comuneros, administradores y tasadores para ocurrir también a ella en cuestiones relativas a sus cuentas y honorarios, siempre que no hayan aceptado el compromiso, o que éste haya caducado o no esté constituido aún.

**Art. 652. (809).** Podrá el partidor fijar plazo a las partes para que formulen sus peticiones sobre las cuestiones que deban servir de base a la partición.

Cada cuestión que se promueva será tramitada separadamente, con audiencia de todos los que en ella tengan intereses, sin entorpecer el curso de las demás y sin que se paralice en unas la jurisdicción del partidor por los recursos que en otras se deduzcan. Podrán, sin embargo, acumularse dos o más de dichas cuestiones cuando sea procedente la acumulación en conformidad a las reglas generales.

Las cuestiones parciales podrán fallarse durante el juicio divisorio o reservarse para la sentencia final.

**Art. 653. (810).** Mientras no se haya constituido el juicio divisorio o cuando falte el árbitro que debe entender en él, corresponderá a la justicia ordinaria decretar la forma en que han de administrarse pro indiviso los bienes comunes y nombrar a los administradores, si no se ponen de acuerdo en ello los interesados.

Organizado el compromiso y mientras subsista la jurisdicción del partidor, a él corresponderá entender en estas cuestiones, y continuar conociendo en las que se hayan ya promovido o se promuevan con ocasión de las medidas dictadas por la justicia ordinaria para la administración de los bienes comunes.	

**Art. 654. (811).** Para acordar o resolver lo conveniente sobre la administración pro indiviso, se citará a todos los interesados a comparendo, el cual se celebrará con sólo los que concurran. No estando todos presentes, sólo podrán acordarse, por mayoría absoluta de los concurrentes, que represente a lo menos la mitad de los derechos de la comunidad, o por resolución del tribunal a falta de mayoría, todas o algunas de las medidas siguientes:

1a. Nombramiento de uno o más administradores, sea de entre los mismos interesados o extraños;
 
2a. Fijación de los salarios de los administradores y de sus atribuciones y deberes;
 
3a. Determinación del giro que deba darse a los bienes comunes durante la administración pro indiviso y del máximum de gastos que puedan en ella hacerse; y 4a. Fijación de las épocas en que deba darse cuenta a los interesados, sin perjuicio de que ellos puedan exigirlas extraordinariamente, si hay motivo justificado, y vigilar la administración sin embarazar los procedimientos de los administradores. 	

**Art. 655. (812).** Para poner término al goce gratuito de alguno o algunos de los comuneros sobre la cosa común, bastará la reclamación de cualquiera de los interesados; salvo que este goce se funde en algún título especial.

**Art. 656. (813).** Los terceros acreedores que tengan derechos que hacer valer sobre los bienes comprendidos en la partición, podrán ocurrir al partidor o a la justicia ordinaria, a su elección.

**Art. 657. (814).** Para adjudicarse o licitar los bienes comunes, se apreciarán por peritos nombrados en la forma ordinaria.

Podrá, sin embargo, omitirse la tasación, si el valor de los bienes se fija por acuerdo unánime de las partes, o de sus representantes, aun cuando haya entre aquéllas incapaces, con tal que existan en los autos antecedentes que justifiquen la apreciación hecha por las partes, o que se trate de bienes muebles, o de fijar un mínimum para licitar bienes raíces con admisión de postores extraños.

**Art. 658. (815).** Para proceder a la licitación pública de los bienes comunes bastará su anuncio por medio de avisos en un diario de la comuna o de la capital de la provincia o de la capital de la región, si en aquélla no lo hubiere.

Cuando entre los interesados haya incapaces, la publicación de avisos se hará por cuatro veces a lo menos, mediando entre la primera publicación y el remate un espacio de tiempo que no baje de quince días. Si por no efectuarse el remate, es necesario hacer nuevas publicaciones, se procederá en conformidad a lo establecido en el artículo 502. Los avisos podrán publicarse también en días inhábiles, los que no se descontarán para el cómputo del plazo señalado en el inciso anterior.

Si los bienes están en otra comuna, el remate se anunciará también en ella, por el mismo tiempo y en la misma forma.

**Art. 659. (816).** En las enajenaciones que se efectúen por conducto del partidor se considerará a éste representante legal de los vendedores, y en tal carácter suscribirá los instrumentos que, con motivo de dichas enajenaciones, haya necesidad de otorgar. Podrá también autorizar al comprador o adjudicatario o a un tercero para que por sí solo suscriba la inscripción de la transferencia en el conservador respectivo.

Todo acuerdo de las partes o resolución del partidor que contenga adjudicación de bienes raíces se reducirá a escritura pública, y sin esta solemnidad no podrá efectuarse su inscripción en el conservador.

**Art. 660. (817).** Salvo acuerdo unánime de las partes, los comuneros que durante el juicio divisorio reciban bienes en adjudicación, por un valor que exceda del ochenta por ciento de lo que les corresponda percibir, pagarán de contado dicho exceso. La fijación provisional de éste se hará prudencialmente por el partidor.

**Art. 661. (818).** Los valores que reciban los comuneros durante la partición a cuenta de sus derechos devengarán el interés que las partes fijen, o el legal cuando tal fijación no se haya hecho, sin perjuicio de lo que en casos especiales dispongan las leyes.

**Art. 662. (819).** En las adjudicaciones de propiedades raíces que se hagan a los comuneros durante el juicio divisorio o en la sentencia final, se entenderá constituida hipoteca sobre las propiedades adjudicadas, para asegurar el pago de los alcances que resulten en contra de los adjudicatarios, siempre que no se pague de contado el exceso a que se refiere el artículo 660. Al inscribir el conservador el título de adjudicación, inscribirá a la vez la hipoteca por el valor de los alcances.

Podrá reemplazarse esta hipoteca por otra caución suficiente calificada por el partidor.

**Art. 663. (820).** Los resultados de la partición se consignarán en un laudo o sentencia final, que resuelva o establezca todos los puntos de hecho y de derecho que deben servir de base para la distribución de los bienes comunes, y en una ordenata o liquidación, en que se hagan los cálculos numéricos necesarios para dicha distribución. 	

**Art. 664. (821).** Se entenderá practicada la notificación del laudo y ordenata desde que se notifique a las partes el hecho de su pronunciamiento, salvo el caso previsto en el artículo 666. Los interesados podrán imponerse de sus resoluciones en la oficina del actuario y deducir los recursos a que haya lugar dentro del plazo de quince días.

**Art. 665. (822).** En el laudo podrá hacer el partidor la fijación de su honorario, y cualquiera que sea su cuantía, habrá derecho para reclamar de ella. La reclamación se interpondrá en la misma forma y en el mismo plazo que la apelación, y será resuelta por el tribunal de alzada en única instancia.	

**Art. 666. (823).** Cuando la partición deba ser aprobada por la justicia ordinaria, el término para apelar será también de quince días, y se contará desde que se notifique la resolución del juez que apruebe o modifique el fallo del partidor.


	
## Título X. DE LOS JUICIOS SOBRE DISTRIBUCIÓN DE AGUAS

**Art. 667.** Derogado.

**Art. 668.** Derogado.

**Art. 669.** Derogado.

**Art. 670.** Derogado.

**Art. 671.** Derogado.

**Art. 672.** Derogado.

**Art. 673.** Derogado.

**Art. 674.** Derogado.

**Art. 675.** Derogado.

**Art. 676.** Derogado.

**Art. 677.** Derogado.

**Art. 678.** Derogado.

**Art. 679.** Derogado.



## Título XI. DEL PROCEDIMIENTO SUMARIO

**Art. 680. (838).** El procedimiento de que trata este Título se aplicará en defecto de otra regla especial a los casos en que la acción deducida requiera, por su naturaleza, tramitación rápida para que sea eficaz.

Deberá aplicarse, además, a los siguientes casos:

1°. A los casos en que la ley ordene proceder sumariamente, o breve y sumariamente, o en otra forma análoga;

2°. A las cuestiones que se susciten sobre constitución, ejercicio, modificación o extinción de servidumbres naturales o legales y sobre las prestaciones a que ellas den lugar;

3°. A los juicios sobre cobro de honorarios, excepto el caso del artículo 697;

4°. A los juicios sobre remoción de guardadores y a los que se susciten entre los representantes legales y sus representados;

5°. Derogado;

6°. A los juicios sobre depósito necesario y comodato precario;

7°. A los juicios en que se deduzcan acciones ordinarias a que se hayan convertido las ejecutivas a virtud de lo dispuesto en el artículo 2515 del Código Civil;

8°. A los juicios en que se persiga únicamente la declaración impuesta por la ley o el contrato, de rendir una cuenta, sin perjuicio de lo dispuesto en el artículo 696; y

9°. A los juicios en que se ejercite el derecho que concede el artículo 945 del Código Civil para hacer cegar un pozo.

10. A los juicios en que se deduzcan las acciones civiles derivadas de un delito o cuasidelito, de conformidad con lo dispuesto en el artículo 59 del Código Procesal Penal y siempre que exista sentencia penal condenatoria ejecutoriada.

**Art. 681. (839).** En los casos del inciso 1° del artículo anterior, iniciado el procedimiento sumario podrá decretarse su continuación conforme a las reglas del juicio ordinario, si existen motivos fundados para ello.

Por la inversa, iniciado un juicio como ordinario, podrá continuar con arreglo al procedimiento sumario, si aparece la necesidad de aplicarlo.

La solicitud en que se pida la substitución de un procedimiento a otro se tramitará como incidente.

**Art. 682. (840).** El procedimiento sumario será verbal; pero las partes podrán, si quieren, presentar minutas escritas en que se establezcan los hechos invocados y las peticiones que se formulen.

**Art. 683. (841).** Deducida la demanda, citará el tribunal a la audiencia del quinto día hábil después de la última notificación, ampliándose este plazo, si el demandado no está en el lugar del juicio, con todo el aumento que corresponda en conformidad a lo previsto en el artículo 259.

A esta audiencia concurrirá el defensor público, cuando deba intervenir conforme a la ley, o cuando el tribunal lo juzgue necesario. Con el mérito de lo que en ella se exponga, se recibirá la causa a prueba o se citará a las partes para oír sentencia.

**Art. 684. (842).** En rebeldía del demandado, se recibirá a prueba la causa, o, si el actor lo solicita con fundamento plausible, se accederá provisionalmente a lo pedido en la demanda.

En este segundo caso, podrá el demandado formular oposición dentro del término de cinco días, contados desde su notificación, y una vez formulada, se citará a nueva audiencia, procediéndose como se dispone en el artículo anterior, pero sin que se suspenda el cumplimiento provisional de lo decretado con esta calidad, ni se altere la condición jurídica de las partes.
	
**Artículo 685.-**  No deduciéndose oposición, el tribunal recibirá la causa a prueba, o citará a las partes para oír sentencia, según lo estime de derecho.

**Art. 686. (844).** La prueba, cuando haya lugar a ella, se rendirá en el plazo y en la forma establecida para los incidentes.

**Artículo 687.-** Vencido el término probatorio, el tribunal, de inmediato, citará a las partes para oír sentencia.

**Artículo 688.-**  Las resoluciones en el procedimiento sumario deberán dictarse, a más tardar, dentro de segundo día.
La sentencia definitiva deberá dictarse en el plazo de los diez días siguientes a la fecha de la resolución que citó a las partes para oír sentencia.

**Art. 689. (847).** Cuando haya de oírse a los parientes, se citará en términos generales a los que designa el artículo 42 del Código Civil, para que asistan a la primera audiencia o a otra posterior, notificándose personalmente a los que puedan ser habidos. Los demás podrán concurrir aun cuando sólo tengan conocimiento privado del acto.

Compareciendo los parientes el tribunal les pedirá informe verbal sobre los hechos que considere conducentes.

Si el tribunal nota que no han concurrido algunos parientes cuyo dictamen estime de influencia y que residan en el lugar del juicio, podrá suspender la audiencia y ordenar que se les cite determinadamente.

**Art. 690. (848).** Los incidentes deberán promoverse y tramitarse en la misma audiencia, conjuntamente con la cuestión principal, sin paralizar el curso de ésta. La sentencia definitiva se pronunciará sobre la acción deducida y sobre los incidentes, o sólo sobre éstos cuando sean previos o incompatibles con aquélla.

**Art. 691. (849).** La sentencia definitiva y la resolución que dé lugar al procedimiento sumario en el caso del inciso 2° del artículo 681, serán apelables en ambos efectos, salvo que, concedida la apelación en esta forma, hayan de eludirse sus resultados.

Las demás resoluciones, inclusa la que acceda provisionalmente a la demanda, sólo serán apelables en el efecto devolutivo.

La tramitación del recurso se ajustará en todo caso a las reglas establecidas para los incidentes.

**Art. 692. (850).** En segunda instancia, podrá el tribunal de alzada, a solicitud de parte, pronunciarse por vía de apelación sobre todas las cuestiones que se hayan debatido en primera para ser falladas en definitiva, aun cuando no hayan sido resueltas, en el fallo apelado.

	
## Título XII. JUICIOS SOBRE CUENTAS

**Art. 693. (851).** El que deba rendir una cuenta la presentará en el plazo que la ley designe o que se establezca por convenio de las partes o por resolución judicial.

**Art. 694. (852).** Presentada la cuenta, se pondrá en conocimiento de la otra parte, concediéndole el tribunal un plazo prudente para su examen. Si, vencido el plazo, no se ha formulado observación alguna, se dará la cuenta por aprobada.

En caso de haber observaciones, continuará el juicio sobre los puntos observados con arreglo al procedimiento que corresponda según las reglas generales, considerándose la cuenta como demanda y como contestación las observaciones.

**Art. 695. (853).** Si el obligado a rendir cuenta no la presenta en los plazos a que se refiere el artículo 693, podrá formularla la otra parte interesada. Puesta en noticia del primero, se tendrá por aprobada si no la objeta dentro del plazo que el tribunal le conceda para su examen.

Si se formulan observaciones, continuará el juicio como en el caso del inciso 2° del artículo anterior.

En la apreciación de la prueba, el tribunal estimará siempre la omisión del que debe presentar la cuenta como una presunción grave para establecer la verdad de las partidas objetadas.

**Art. 696. (854).** Lo establecido en el inciso 1° del artículo anterior se entenderá sin perjuicio del derecho que corresponda para exigir por acción ejecutiva el cumplimiento de la obligación de presentar la cuenta, cuando dicha acción sea procedente.



## Título XIII. DE LOS JUICIOS SOBRE PAGO DE CIERTOS HONORARIOS

**Art. 697. (859).** Cuando el honorario proceda de servicios profesionales prestados en juicio, el acreedor podrá, a su arbitrio, perseguir su estimación y pago con arreglo al procedimiento sumario, o bien interponiendo su reclamación ante el tribunal que haya conocido en la primera instancia del juicio.

En este último caso la petición será substanciada y resuelta en la forma prescrita para los incidentes.

	

## Título XIV. DE LOS JUICIOS DE MENOR Y DE MINIMA CUANTIA

***1. De los juicios de menor cuantía***

**Art. 698.** Los juicios de más de diez unidades tributarias mensuales y que no pasen de quinientas unidades tributarias mensuales, y que no tengan señalado en la ley un procedimiento especial, se someterán al procedimiento ordinario de que trata el Libro II con las modificaciones siguientes:

1a. Se omitirán los escritos de réplica y dúplica.

Si se deduce reconvención, se dará traslado de ella al demandante por seis días, y con lo que éste exponga o en su rebeldía, se recibirá la causa a prueba;

2a. El término para contestar la demanda será de ocho días, que se aumentará de conformidad a la tabla de emplazamiento. Este aumento no podrá exceder de veinte días, y no regirá para estos juicios la disposición del inciso 2° del artículo 258.

En el caso del artículo 308, el plazo para contestar la demanda será de seis días;

3a. Se citará a la audiencia de conciliación para un día no anterior al tercero ni posterior al décimo contado desde la fecha de notificación de la resolución.

4a. El término de prueba será de quince días y podrá aumentarse, extraordinariamente, de conformidad a lo dispuesto en el número anterior;

5a. El término a que se refiere el artículo 430 será de seis días;

6a. La sentencia se dictará dentro de los quince días siguientes al de la última notificación de la resolución que cita a las partes para oírla; y 

7a. Deducida apelación contra resoluciones que no se refieran a la competencia o a la inhabilidad del tribunal, ni recaigan en incidentes sobre algún vicio que anule el proceso, el juez tendrá por interpuesto el recurso para después de la sentencia que ponga término al juicio. El apelante deberá reproducirlo dentro de los cinco días subsiguientes al de la notificación de la sentencia y en virtud de esta reiteración, lo concederá el tribunal.

En los casos de excepción a que se refiere el inciso anterior de este número, como también en los incidentes sobre medidas prejudiciales o precautorias, el recurso se concederá al tiempo de su interposición.

**Art. 699.** La apelación de la sentencia definitiva se tramitará como en los incidentes y se verá conjuntamente con las apelaciones que se hayan concedido en conformidad al inciso 1° del N° 5° del artículo anterior.

Los alegatos no podrán exceder de 15 minutos, salvo que el tribunal acuerde prorrogar este tiempo hasta el doble.

**Art. 700.** Derogado.

**Art. 701.** El tribunal destinará, por lo menos, un día de cada semana a la vista preferente de estas causas.

**Art. 702.** La sentencia deberá dictarse dentro del plazo de 15 días, contado desde el término de la vista de la causa.


***2. De los juicios de mínima cuantía***

**Art. 703.** Se aplicará el procedimiento de que trata este párrafo a los juicios cuya cuantía no exceda de diez unidades tributarias mensuales, y que por su naturaleza no tengan señalado en la ley un procedimiento especial.

**Art. 704.** El procedimiento será verbal, pero las partes podrán presentar minutas escritas en que se establezcan los hechos invocados y las peticiones que se formulen.

La demanda se interpondrá verbalmente o por escrito. En el primer caso se dejará constancia, en un acta que servirá de cabeza al proceso, del nombre, profesión u oficio y domicilio del demandante, de los hechos que éste exponga y de sus circunstancias esenciales, de los documentos que acompañe y de las peticiones que formule.

El acta terminará con una resolución en que se cite a las partes para que comparezcan personalmente, o representadas por mandatarios con facultad especial para transigir, en el día y hora que se designe. El tribunal fijará para esta audiencia un día determinado que no podrá ser anterior al tercer día hábil desde la fecha de la resolución y cuidará de que medie un tiempo prudencial entre la notificación del demandado y la celebración de la audiencia.

Inmediatamente deberá entregarse al demandante copia autorizada del acta y de su proveído, con lo cual se entenderá notificado de las resoluciones que contenga.

**Art. 705.** La demanda y la primera resolución de cualquiera gestión anterior a ésta se notificará personalmente al demandado por medio de un receptor, si lo hay, y no habiéndolo o si está inhabilitado, por medio de un vecino de la confianza del tribunal, que sea mayor de edad y sepa leer y escribir o por un miembro del Cuerpo de Carabineros. Deberá entregarse copia íntegra del acta y del proveído a que se refiere el artículo anterior.

Las mismas personas podrán practicar la notificación establecida en el artículo 44 cuando ella sea procedente.

**Art. 706.** La sentencia definitiva, la resolución que reciba la causa a prueba y las resoluciones que ordenen la comparecencia personal de las partes se notificarán por cédula, en conformidad al artículo 48, por alguna de las personas indicadas en el artículo anterior.

Para estos efectos, el demandante al tiempo de su presentación y el demandado en su primera comparecencia, deberán designar su domicilio en la forma indicada en el inciso 2° del artículo 49.

Se hará saber al demandante cuando presente su demanda y al demandado al tiempo de notificarlo, la disposición precedente. Se pondrá testimonio de esta diligencia en los autos.

La misma regla se observará con respecto a los mandatarios que constituyan las partes. El domicilio deberá designarse al tiempo de presentarse o constituirse el poder.

Si la demanda ha sido notificada personalmente al demandado, y éste no designa domicilio, se tendrá por tal el que se haya señalado en la demanda y si aquélla ha sido notificada en la forma prevista en el artículo 44, se considerará como domicilio la morada en que se haya practicado dicha notificación. Lo dispuesto en este inciso tendrá lugar siempre que el domicilio en donde se practicó la notificación esté dentro de la jurisdicción del tribunal correspondiente; en caso contrario, regirá lo dispuesto en el artículo siguiente.

**Art. 707.** Las demás resoluciones se notificarán en la forma dispuesta en el artículo 50, aunque las partes no hayan fijado domicilio al cual deban dirigírseles las cartas a que se refiere el inciso 2° del artículo 46; pero dichas resoluciones deberán notificarse por carta certificada en el domicilio a que se refiere el artículo anterior cuando el juicio se tramite ante jueces inferiores. En este último caso, a falta de ese domicilio, se entenderán notificadas desde que se extiendan en el proceso las respectivas resoluciones.

La carta certificada deberá contener exclusivamente el aviso de haberse dictado resolución en la causa. 	

**Art. 708.** Para practicar notificaciones en estos juicios serán hábiles las horas comprendidas entre las seis y las veinte horas de todos los días del año. 	

**Artículo 709.-** El plazo para que se declare abandonado el procedimiento en estos juicios, será de tres meses.

**Art. 710.** La audiencia de contestación se celebrará con la parte que asista. En caso de inconcurrencia del demandado, podrá el tribunal suspender la audiencia si estima que la demanda no le ha sido notificada mediando el tiempo prudencial a que se refiere el artículo 704; o si habiéndosele notificado en la forma prevista en el artículo 44 haya motivo para creer que la copia correspondiente no ha llegado con oportunidad a su poder. En tales casos deberá dictarse una resolución fundada en la cual se señalará nuevo día y hora para la celebración de la audiencia. 	

**Art. 711.** En la audiencia de contestación el demandado deberá oponer las excepciones dilatorias y perentorias que pueda hacer valer en contra de la demanda.

El tribunal después de oír al demandado llamará a las partes a avenimiento y producido éste, se consignará en un acta.

En la misma audiencia el tribunal entregará a cada parte copia íntegra autorizada de la referida acta.

El avenimiento pondrá fin al juicio y tendrá la autoridad de cosa juzgada.

Si no se produce avenimiento, el tribunal se limitará a dejar constancia de este hecho.

**Art. 712.** Todas las excepciones se tramitarán conjuntamente y se fallarán en la sentencia definitiva, pero el tribunal podrá acoger, desde luego, o tramitar separadamente en conformidad al artículo 723, las dilatorias de incompetencia, de falta de capacidad o de personería del demandante, o aquella en que se reclame del procedimiento siempre que aparezcan manifiestamente admisibles.

**Art. 713.** El demandado podrá también deducir reconvención en la audiencia de contestación cuando el tribunal sea competente para conocer de ella y siempre que no esté sometida a un procedimiento especial y tenga por objeto enervar la acción deducida o esté íntimamente ligada con ella. En caso contrario no se admitirá a tramitación.

Es aplicable a la reconvención lo dispuesto en el artículo anterior.

La reconvención se tramitará conjuntamente con la demanda.

**Art. 714.** La práctica de toda diligencia probatoria deberá solicitarse en la audiencia de contestación so pena de no ser admitida después, sin perjuicio de que el tribunal pueda de oficio, para mejor resolver, en cualquier estado de la causa, decretar todas las diligencias y actuaciones conducentes a la comprobación de los hechos discutidos, debiendo emplear para ello el mayor celo posible.

Los instrumentos sólo podrán presentarse conjuntamente con la demanda o en las audiencias de contestación o de prueba y las partes deberán formular las observaciones y las impugnaciones que procedan en la audiencia en que se acompañen o en la inmediatamente siguiente. Los incidentes a que den lugar las observaciones e impugnaciones deberán tramitarse y probarse al mismo tiempo que la cuestión principal. Los que se formulen en la audiencia de prueba se deberán probar en esa misma audiencia, salvo que el tribunal por motivos fundados fije una nueva audiencia para ello.

**Art. 715.** Contestada la demanda o en rebeldía del demandado, el juez resolverá si debe o no recibirse la causa a prueba. En caso afirmativo fijará los puntos sobre los cuales debe recaer y señalará una audiencia próxima para recibirla. En caso contrario, citará a las partes para oír sentencia, la que deberá dictar a más tardar en el plazo de los ocho días subsiguientes.  La resolución que reciba la causa a prueba es inapelable.

**Art. 716.** Si las partes desean rendir prueba testimonial, deberán, en la audiencia de contestación o dentro de los tres días siguientes a la notificación de la resolución que reciba la causa a prueba, hacer anotar en el proceso el nombre, profesión u oficio y domicilio de los testigos que ofrezcan presentar y si los testigos deben o no ser citados por el tribunal. En la audiencia indicada el juez hará saber a las partes estas circunstancias.

Sólo podrán declarar cuatro testigos por cada parte sobre cada uno de los puntos de prueba que fije el juez.

**Art. 717.** La declaración de testigos se presentará bajo juramento, en presencia de las partes que asistan, quienes podrán dirigir preguntas al deponente por conducto del juez.

Antes de la declaración de cada testigo, la parte contra quien deponga podrá deducir las tachas de los artículos 357 y 358, que a su juicio le inhabiliten para declarar. El juez, si lo estima necesario, proveerá lo conducente al establecimiento de las inhabilidades invocadas, las que apreciará en conciencia en la sentencia definitiva.

Las inhabilidades que se hagan valer en contra de los testigos no obstan a su examen; pero el tribunal podrá desechar de oficio a los que, según su criterio, aparezcan notoriamente inhábiles.

**Art. 718.** La confesión judicial de la partes podrá pedirse por una sola vez en el juicio y deberá solicitarse en la audiencia de contestación. También podrá pedirse, en la audiencia de prueba, siempre que se encuentre presente la persona que deba declarar.

Lo dicho en el inciso anterior es sin perjuicio de lo dispuesto en el inciso 1° del artículo 714.

Decretada la confesión, el juez la tomará de inmediato si está presente la parte que deba prestarla. En caso contrario, procederá a tomarla en la audiencia de prueba o en otra que señale para este solo efecto. Si el absolvente se niega a declarar o da respuestas evasivas, el juez podrá dar por confesados los hechos materia de la respectiva pregunta.

Si el absolvente no concurre el día y hora fijados y siempre que al pedir la diligencia la parte haya acompañado pliego de posiciones, se darán éstas por absueltas en rebeldía, sin necesidad de nueva citación, teniéndose al absolvente por confeso de todos aquellos hechos que estén categóricamente afirmados en dicho pliego, y que a juicio del tribunal sean verosímiles.

La comparecencia se verificará ante el tribunal de la causa si la parte se encuentra en el lugar del juicio; en caso contrario, ante el juez competente del lugar en que resida, pero no se podrá ejercitar este derecho si existe en el juicio mandatario con facultad de absolver posiciones a menos que el tribunal estime absolutamente necesaria la diligencia para el fallo. 	

**Art. 719.** Cuando hayan de practicarse diligencias probatorias fuera de la sala de despacho, podrá el tribunal proceder por sí solo o con notificación de las partes, según lo estime conveniente.

**Art. 720.** Siempre que el tribunal decrete informe de peritos, designará preferentemente para el cargo al empleado público, municipal o de institución semifiscal que estime competente, quien estará obligado a desempeñarlo gratuitamente.

Los informes periciales se presentarán por escrito, pero el juez podrá pedir informes verbales que se consignarán en los autos con las firmas de quienes los emitan. De ellos deberá darse cuenta en la audiencia de prueba siempre que sea posible.

**Art. 721.** De todo lo obrado en la primera audiencia y en las demás que se celebren, se levantará acta firmada por el juez, las partes asistentes, los testigos que hayan declarado y el secretario, si lo hay, o en defecto de éste, un ministro de fe o una persona que, en calidad de actuario, nombre el tribunal.

Si alguno de los comparecientes no sabe o no puede firmar estampará su impresión digital, y si se niega a firmar, se dejará constancia de ello.

Las resoluciones se extenderán en el mismo expediente.

**Art. 722.** Sin perjuicio de lo dispuesto en el artículo 715, el tribunal citará a las partes para oír sentencia y la dictará dentro de los sesenta días contados desde la celebración de la audiencia de contestación, salvo que lo impidan circunstancias insuperables, de las cuales dejará constancia en la sentencia y de ello dará cuenta oportunamente en estados mensuales a que se refiere el artículo 586 N° 4° del Código Orgánico de Tribunales.

**Art. 723.-** Los incidentes deberán formularse y tramitarse en las audiencias de contestación y prueba y su fallo se reservará para la sentencia definitiva, la que será inapelable.

Podrá el tribunal, atendida la naturaleza del incidente, tramitarlo separadamente, con audiencia verbal de la parte contraria, y decretar las diligencias adecuadas a su acertada resolución.

De igual modo, podrán tramitarse los incidentes especiales de que tratan los artículos 79, 80 y 81; los Títulos X, XI, XII, XIII, XIV, XV y XVI del Libro Primero y los Títulos IV y V del Libro Segundo.

Las resoluciones que se dicten en todo procedimiento incidental, cualquiera sea su naturaleza, serán inapelables.

**Art. 724.** La prueba se apreciará en la forma ordinaria. Pero podrá el tribunal, en casos calificados, estimarla conforme a conciencia, y según la impresión que le haya merecido la conducta de las partes durante el juicio y la buena o mala fe con que hayan litigado en él.

**Art. 725.** La sentencia definitiva deberá expresar:

 1°. La individualización de los litigantes;
 
 2°. La enunciación brevísima de las peticiones del demandante y de las defensas del demandado y de sus fundamentos respectivos;
 
 3°. Un análisis somero de la prueba producida;
 
 4°. Las razones de hecho y de derecho, que sirven de fundamento al fallo; y
 
 5°. La decisión del asunto.

Si en la sentencia se da lugar a una excepción dilatoria, se abstendrá el tribunal de pronunciarse sobre la cuestión principal.

Deberá dejarse copia íntegra de la sentencia definitiva y de todo avenimiento o transacción que ponga término al juicio en el libro de sentencias que se llevará con este objeto.

**Art. 726.** La regulación de las costas, cuando haya lugar a ellas, se hará en la sentencia misma.

**Art. 727.** Derogado.

**Art. 728.** Derogado.

**Art. 729.** Si la acción es ejecutiva y legalmente procedente, el acta a que se refiere el artículo 704, terminará con la orden de despachar mandamiento de ejecución en contra del deudor.

El mandamiento dispondrá el embargo de bienes suficientes y designará un depositario que podrá ser el mismo deudor. El depositario nombrado tendrá carácter de definitivo.

Si la acción deducida no procede como ejecutiva, el tribunal lo declarará así y dará curso a la demanda en conformidad al procedimiento ordinario de mínima cuantía.

**Art. 730.** El requerimiento de pago se efectuará en la forma prescrita en el artículo 705. En el caso del inciso 2°, el encargado de la notificación deberá indicar, en la copia respectiva, el lugar, día y hora que designe para la traba de embargo, a la que procederá sin otro trámite. De la diligencia se levantará acta individualizando suficientemente los bienes embargados y el lugar en que se encuentran. Si el deudor no está presente, quien practique la diligencia dejará copia del acta en el domicilio de aquél.

**Art. 731.** La misma persona que practique el requerimiento, podrá efectuar el embargo, en su caso.

Si el depositario es el deudor, aunque no esté presente, se entenderá que ha quedado en posesión de la cosa embargada al trabarse el embargo. El encargado de la diligencia indicará en el acta el lugar en que ordinariamente deberá mantenerse aquélla.

**Art. 732.** El deudor depositario incurrirá en las penas contempladas en el artículo 471 del Código Penal cuando con perjuicio del acreedor falte a sus obligaciones de depositario, desobedezca o entorpezca las resoluciones judiciales para la inspección de los bienes embargados, o abandone, destruya o enajene dichos bienes.

Se presumirá que el deudor depositario ha faltado a sus obligaciones con perjuicio del acreedor cuando, sin permiso escrito de éste o autorización del juez, cambie la cosa embargada del lugar a que se refiere el artículo anterior.

**Art. 733.** El ejecutado tendrá el plazo fatal de cuatro días más el término de emplazamiento a que se refiere el artículo 259 contados desde el requerimiento, para oponerse a la demanda.

La oposición sólo podrá fundarse en algunas de las excepciones indicadas en los artículos 464 y 534.

El tribunal citará, en este caso, a las partes a una audiencia próxima y se procederá como se dispone en el artículo 710 y siguientes, hasta dictar sentencia mandando llevar adelante la ejecución o absolviendo al demandado.

La citación se notificará al ejecutado en el acto mismo de formular su oposición y el ejecutante en la forma prescrita en el artículo 706.

Si las excepciones opuestas no son legales, se procederá como lo dispone el artículo 472.

**Art. 734.** Los bienes embargados serán tasados por el juez, quien podrá, si lo estima necesario, oír peritos designados en conformidad al artículo 720.

**Art. 735.** Establecido el valor de los bienes embargados, el juez ordenará que se rematen, previa citación de las partes.

Si se trata de bienes raíces o de derechos reales constituidos en ellos, deberán, además, publicarse tres avisos en un diario de la comuna en que se encuentre situado el inmueble o, si allí no lo hubiere, en uno de la capital de la provincia o de la capital de la respectiva región.

Los remates se efectuarán solamente en los días 1° y 15 de cada mes, o en el día siguiente hábil si alguna de esas fechas corresponde a día inhábil.

Las posturas empezarán por los dos tercios de la tasación.

**Art. 736.** Cuando se enajenen bienes raíces, el acta de remate se extenderá en el libro copiador de sentencias y será subscrita por el juez y el secretario, si lo hay, y en su defecto por una persona que en calidad de actuario nombre el tribunal.

La escritura definitiva se otorgará en el registro de un notario y será subscrita por el juez ante quien se haya hecho el remate y por el subastador, o en defecto de aquél, por la persona a quien él comisione con tal objeto en el acta de remate.

**Art. 737.** Regirán también en el juicio de mínima cuantía las disposiciones del Título XIX del Libro I; pero las peticiones de las partes, las notificaciones y el procedimiento de apremio deberán ajustarse a las reglas de este Título. La oposición del demandado cuando sea procedente en conformidad al artículo 234, se proveerá citando a las partes a una audiencia próxima para que concurran a ella con todos sus medios de prueba.

**Art. 738.** En los casos no previstos por los artículos precedentes, serán aplicables las reglas del juicio ejecutivo de mayor cuantía si la cuestión deducida es también ejecutiva.


	
## Título XV. DEL JUICIO SOBRE ARREGLO DE LA AVERÍA COMÚN

**Art. 739.** Derogado.

**Art. 740.** Derogado.

**Art. 741.** Derogado.

**Art. 742.** Derogado.

**Art. 743.** Derogado.

**Art. 744.** Derogado.

**Art. 745.** Derogado.

**Art. 746.** Derogado.

**Art. 747.** Derogado.



## Título XVI. DE LOS JUICIOS DE HACIENDA

**Art. 748. (922).** Los juicios en que tenga interés el Fisco y cuyo concimiento corresponda a los tribunales ordinarios, se substanciarán siempre por escrito, con arreglo a los trámites establecidos para los juicios del fuero ordinario de mayor cuantía, salvo las modificaciones que en los siguientes artículos se expresan.

**Art. 749. (923).** Se omitirán en el juicio ordinario los escritos de réplica y dúplica, siempre que la cuantía del negocio no pase de quinientas unidades tributarias mensuales.

**Art. 750. (924).** Derogado.

**Art. 751. (925).** Toda sentencia definitiva pronunciada en primera instancia en juicios de hacienda y de que no se apele, se elevará en consulta a la Corte de Apelaciones respectiva, previa notificación de las partes, siempre que sea desfavorable al interés fiscal. Se entenderá que lo es, tanto la que no acoja totalmente la demanda del Fisco o su reconvención, como la que no deseche en todas sus partes la demanda deducida contra el Fisco o la reconvención promovida por el demandado.

Recibidos los autos, el tribunal revisará la sentencia en cuenta para el solo efecto de ponderar si ésta se encuentra ajustada a derecho.  Si no mereciere reparos de esta índole, la aprobará sin más trámites. De lo contrario, retendrá el conocimiento del negocio y, en su resolución, deberá señalar los puntos que le merecen duda, ordenando traer los autos en relación.  La vista de la causa se hará en la misma sala y se limitará estrictamente a los puntos de derecho indicados en la resolución.

Las consultas serán distribuidas por el Presidente de la Corte, mediante sorteo, entre las salas en que ésta esté dividida.

**Art. 752. (926).** Toda sentencia que condene al Fisco a cualquiera prestación, deberá cumplirse dentro de los sesenta días siguientes a la fecha de recepción del oficio a que se refiere el inciso segundo, mediante decreto expedido a través del Ministerio respectivo.

Ejecutoriada la sentencia, el tribunal remitirá oficio al ministerio que corresponda, adjuntando fotocopia o copia autorizada de la sentencia de primera y de segunda instancia, con certificado de estar ejecutoriada.

Se certificará en el proceso el hecho de haberse remitido el oficio y se agregará al expediente fotocopia o copia autorizada del mismo. La fecha de recepción de éste se acreditará mediante certificado de ministro de fe que lo hubiese entregado en la Oficina de Partes del Ministerio o, si hubiese sido enviado por carta certificada, transcurridos tres días desde su recepción por el correo.

En caso que la sentencia condene al Fisco a prestaciones de carácter pecuniario, el decreto de pago deberá disponer que la Tesorería incluya en el pago el reajuste e intereses que haya determinado la sentencia y que se devenguen hasta la fecha de pago efectivo. En aquellos casos en que la sentencia no hubiese dispuesto el pago de reajuste y siempre  que la cantidad ordenada pagar no se solucione dentro de los sesenta días establecidos en el inciso primero, dicha cantidad se reajustará en conformidad con la variación que haya experimentado el Indice de Precios al Consumidor entre el mes anterior a aquel en que quedó ejecutoriada la sentencia y el mes anterior al del pago efectivo.



## Título XVII. DE LOS JUICIOS DE NULIDAD DE MATRIMONIO Y DE DIVORCIO

**Art. 753.** Derogado.

**Art. 754.** Derogado.

**Art. 755.** Derogado.

**Art. 756.** Derogado.

**Art. 757.** Derogado.



## Título XVIII. DE LA ACCION DE DESPOSEIMIENTO CONTRA TERCEROS POSEEDORES DE LA FINCA HIPOTECADA O ACENSUADA.

**Art. 758. (932).** Para hacer efectivo el pago de la hipoteca, cuando la finca gravada se posea por otro que el deudor personal, se notificará previamente al poseedor, señalándole un plazo de diez días para que pague la deuda o abandone ante el juzgado la propiedad hipotecada.

**Art. 759. (933).** Si el poseedor no efectúa el pago o el abandono en el plazo expresado en el artículo anterior, podrá desposeérsele de la propiedad hipotecada para hacer con ella pago al acreedor.

Esta acción se someterá a las reglas del juicio ordinario o a las del ejecutivo, según sea la calidad del título en que se funde, procediéndose contra el poseedor en los mismos términos en que podría hacerse contra el deudor personal.

**Art. 760. (934).** Efectuado el abandono o el desposeimiento de la finca perseguida, se procederá conforme a lo dispuesto en los artículos 2397 y 2424 del Código Civil, sin necesidad de citar al deudor personal. Pero si éste comparece a la incidencia, será oído en los trámites de tasación y de subasta.

**Art. 761. (935).** Si el deudor personal no es oído en el trámite de tasación esta diligencia deberá hacerse por peritos que nombrará el juez de la causa en la forma prescrita por este Código. La tasación, en este caso, no impide que el deudor personal pueda objetar la determinación del saldo de la obligación principal por el cual se le demande, si comprueba en el juicio correspondiente que se ha procedido en fraude de sus derechos.

**Art. 762. (936).** Lo dispuesto en el artículo 492 se aplicará también al caso en que se persiga la finca hipotecada contra terceros poseedores.

**Art. 763. (937).** La acción del censualista sobre la finca acensuada se rige por las disposiciones del presente Título.



## Título XIX. DEL RECURSO DE CASACION

***1. Disposiciones generales***

**Art. 764.** El recurso de casación se concede para invalidar una sentencia en los casos expresamente señalados por la ley.

**Art. 765.** El recurso de casación es de dos especies: de casación en el fondo y de casación de la forma.

Es de casación en el fondo en el caso del artículo 767.

Es de casación en la forma en los casos del artículo 768.

**Art. 766.** El recurso de casación en la forma se concede contra las sentencias definitivas, contra las interlocutorias cuando ponen término al juicio o hacen imposible su continuación y, excepcionalmente, contra las sentencias interlocutorias dictadas en segunda instancia sin previo emplazamiento de la parte agraviada, o sin señalar día para la vista de la causa.

Procederá, asimismo, respecto de las sentencias que se dicten en los juicios o reclamaciones regidos por leyes especiales, con excepción de aquéllos que se refieran a la constitución de las juntas electorales y a las reclamaciones de los avalúos que se practiquen en conformidad a la Ley N° 17.235, sobre Impuesto Territorial y de los demás que prescriban las leyes.

**Artículo 767.-**  El recurso de casación en el fondo tiene lugar contra sentencias definitivas inapelables y contra sentencias interlocutorias inapelables cuando ponen término al juicio o hacen imposible su continuación, dictadas por Cortes de Apelaciones o por un tribunal arbitral de segunda instancia constituído por árbitros de derecho en los casos en que estos árbitros hayan conocido de negocios de la competencia de dichas Cortes, siempre que se hayan pronunciado con infracción de ley y esta infracción haya influido substancialmente en lo dispositivo de la sentencia.

**Art. 768.** El recurso de casación en la forma ha de fundarse precisamente en alguna de las causas siguientes:

1a. En haber sido la sentencia pronunciada por un tribunal incompetente o integrado en contravención a lo dispuesto por la ley;

2a. En haber sido pronunciada por un juez, o con la concurrencia de un juez legalmente implicado, o cuya recusación esté pendiente o haya sido declarada por tribunal competente;

3a. En haber sido acordada en los tribunales colegiados por menor número de votos o pronunciadas por menor número de jueces que el requerido por la ley o con la concurrencia de jueces que no asistieron a la vista de la causa, y viceversa;

4a. En haber sido dada ultra petita, esto es, otorgando más de lo pedido por las partes, o extendiéndola a puntos no sometidos a la decisión del tribunal, sin perjuicio de la facultad que éste tenga para fallar de oficio en los casos determinados por la ley;

5a. En haber sido pronunciada con omisión de cualquiera de los requisitos enumerados en el artículo 170;

6a. En haber sido dada contra otra pasada en autoridad de cosa juzgada, siempre que ésta se haya alegado oportunamente en el juicio;

7a. En contener decisiones contradictorias;

8a. En haber sido dada en apelación legalmente declarada desistida, y

9a. En haberse faltado a algún trámite o diligencia declarados esenciales por la ley o a cualquier otro requisito por cuyo defecto las leyes prevengan expresamente que hay nulidad.

En los negocios a que se refiere el inciso segundo del artículo 766 sólo podrá fundarse el recurso de casación en la forma en alguna de las causales indicadas en los números 1°, 2°, 3°, 4°, 6°, 7° y 8° de este artículo y también en el número 5° cuando se haya omitido en la sentencia la decisión del asunto controvertido.

No obstante lo dispuesto en este artículo, el tribunal podrá desestimar el recurso de casación en la forma, si de los antecedentes aparece de manifiesto que el recurrente no ha sufrido un perjuicio reparable sólo con la invalidación del fallo o cuando el vicio no ha influido en lo dispositivo del mismo.

El tribunal podrá limitarse, asimismo, a ordenar al de la causa que complete la sentencia cuando el vicio en que se funda el recurso sea la falta de pronunciamiento sobre alguna acción o excepción que se haya hecho valer oportunamente en el juicio.

**Art. 769.** Para que pueda ser admitido el recurso de casación en la forma es indispensable que el que lo entabla haya reclamado de la falta, ejerciendo oportunamente y en todos sus grados los recursos establecidos por la ley.

No es necesaria esta reclamación cuando la ley no admite recurso alguno contra la resolución en que se haya cometido la falta, ni cuando ésta haya tenido lugar en el pronunciamiento mismo de la sentencia que se trata de casar, ni cuando dicha falta haya llegado al conocimiento de la parte después de pronunciada la sentencia.

Es igualmente innecesario para interponer este recurso contra la sentencia de segunda instancia por las causales cuarta, sexta y séptima del artículo 768, que se haya reclamado contra la sentencia de primera instancia, aun cuando hayan afectado también a ésta los vicios que lo motivan.

La reclamación a que se refiere el inciso primero de este artículo deberá hacerse por la parte o su abogado antes de verse la causa, en el caso del número 1° del artículo 768.

**Artículo 770.-** El recurso de casación deberá interponerse dentro de los quince días siguientes a la fecha de notificación de la sentencia contra la cual se recurre, sin perjuicio de lo establecido en el artículo 791.  En caso que se deduzca recurso de casación de forma y de fondo en contra de una misma resolución, ambos recursos deberán interponerse simultáneamente y en un mismo escrito.

El recurso de casación en la forma contra sentencia de primera instancia deberá interponerse dentro del plazo concedido para deducir el recurso de apelación, y si también se deduce este último recurso, conjuntamente con él.

**Art. 771.** El recurso debe interponerse por la parte agraviada ante el tribunal que haya pronunciado la sentencia que se trata de invalidar y para ante aquel a quien corresponde conocer de él conforme a la ley.

**Art. 772.** El escrito en que se deduzca el recurso de casación en el fondo deberá:
1) Expresar en qué consiste el o los errores de derecho de que adolece la sentencia recurrida, y
2) Señalar de qué modo ese o esos errores de derecho influyen sustancialmente en lo dispositivo del fallo.

Si el recurso es en la forma, el escrito mencionará expresamente el vicio o defecto en que se funda y la ley que concede el recurso por la causal que se invoca.

En uno y otro caso, el recurso deberá ser patrocinado por abogado habilitado, que no sea procurador del número.

**Art. 773.** El recurso de casación no suspende la ejecución de la sentencia, salvo cuando su cumplimiento haga imposible llevar a efecto la que se dicte si se acoge el recurso, como sería si se tratare de una sentencia que declare la nulidad de un matrimonio o permita el de un menor.

La parte vencida podrá exigir que no se lleve a efecto la sentencia mientras la parte vencedora no rinda fianza de resultas a satisfacción del tribunal que haya dictado la sentencia recurrida, salvo que el recurso se interponga por el demandado contra la sentencia definitiva pronunciada en el juicio ejecutivo, en los juicios posesorios, en los de desahucio y en los de alimentos.

El recurrente deberá ejercer este derecho conjuntamente con interponer el recurso de casación y en solicitud separada que se agregará a la carpeta electrónica a que se refiere el artículo 29. El tribunal a quo se pronunciará de plano y en única instancia a su respecto y fijará el monto de la caución antes de enviar la comunicación correspondiente al tribunal superior.

En este caso, se formará cuaderno electrónico separado con las piezas necesarias.

El tribunal a quo conocerá también en única instancia en todo lo relativo al otorgamiento y subsistencia de la caución.

**Art. 774.** Interpuesto el recurso, no puede hacerse en él variación de ningún género.

Por consiguiente, aun cuando en el progreso del recurso se descubra alguna nueva causa en que haya podido fundarse, la sentencia recaerá únicamente sobre las alegadas en tiempo y forma.

**Art. 775. (949).** No obstante lo dispuesto en los artículos 769 y 774, pueden los tribunales, conociendo por vía de apelación, consulta o casación o en alguna incidencia, invalidar de oficio las sentencias cuando los antecedentes del recurso manifiesten que ellas adolecen de vicios que dan lugar a la casación en la forma, debiendo oír sobre este punto a los abogados que concurran a alegar en la vista de la causa e indicar a los mismos los posibles vicios sobre los cuales deberán alegar.

Si el defecto que se advierte es la omisión del fallo sobre alguna acción o excepción que se haya hecho valer en el juicio, el tribunal superior podrá limitarse a ordenar al de la causa que complete la sentencia, dictando resolución sobre el punto omitido, y entre tanto, suspenderá el fallo del recurso.

**Art. 776.** Presentado el recurso, el tribunal examinará si ha sido interpuesto en tiempo y si ha sido patrocinado por abogado habilitado. En el caso que el recurso se interpusiere ante un tribunal colegiado, el referido examen se efectuará en cuenta.

Si el recurso reúne estos requisitos, dará cumplimiento a lo establecido en el inciso primero del artículo 197.

Inciso Eliminado.

**Art. 777.** Derogado.

**Artículo 778.-**  Si el recurso no cumple con los requisitos establecidos en el inciso primero del artículo 776, el tribunal lo declarará inadmisible, sin más trámite.

En contra del fallo que se dicte, sólo podrá interponerse el recurso de reposición, el que deberá fundarse en error de hecho y deducirse en el plazo de tercero día. La resolución que resuelva la reposición será inapelable.

**Art. 779.** Es aplicable al recurso de casación lo dispuesto en el artículo 200.

Inciso Eliminado.

**Artículo 780.-**  Interpuesto el recurso de casación en el fondo, cualquiera de las partes podrá solicitar, dentro del plazo para hacerse parte en el tribunal ad quem, que el recurso sea conocido y resuelto por el pleno del tribunal. La petición sólo podrá fundarse en el hecho que la Corte Suprema, en fallos diversos, ha sostenido distintas interpretaciones sobre la materia de derecho objeto del recurso.

**Artículo 781.-** Elevado un proceso en casación de forma, el tribunal examinará en cuenta si la sentencia objeto del recurso es de aquéllas contra las cuales lo concede la ley y si éste reúne los requisitos que establecen los artículos 772, inciso segundo, y 776, inciso primero.

Si el tribunal encuentra mérito para considerarlo inadmisible, lo declarará sin lugar desde luego, por resolución fundada.

En caso de no declarar inadmisible desde luego el recurso, ordenará traer los autos en relación, sin más trámite. Asimismo, podrá decretar autos en relación, no obstante haber declarado la inadmisibilidad del recurso, cuando estime posible una casación de oficio.

La resolución por la que el tribunal de oficio declare la inadmisibilidad del recurso, sólo podrá ser objeto del recurso de reposición, el que deberá ser fundado e interponerse dentro de tercero día de notificada la resolución.

**Artículo 782.-** Elevado un proceso en casación de fondo, el tribunal examinará en cuenta si la sentencia objeto del recurso es de aquéllas contra las cuales lo concede la ley y si éste reúne los requisitos que se establecen en los incisos primeros de los artículos 772 y 776.

La misma sala, aun cuando se reúnan los requisitos establecidos en el inciso precedente, podrá rechazarlo de inmediato si, en opinión unánime de sus integrantes, adolece de manifiesta falta de fundamento.

Esta resolución deberá ser, a lo menos, someramente fundada y será susceptible del recurso de reposición que establece el inciso final del artículo 781.

En el mismo acto el tribunal deberá pronunciarse sobre la petición que haya formulado el recurrente, en cuanto a que el recurso sea visto por el pleno de la Corte Suprema, de conformidad a lo establecido en el artículo 780. La resolución que deniegue esta petición será susceptible del recurso de reposición que se establece en el inciso final del artículo 781.

Es aplicable al recurso de casación de fondo lo dispuesto en los incisos segundo, tercero y cuarto del artículo 781.

**Art. 783.** En la vista de la causa se observarán las reglas establecidas para las apelaciones.

La duración de las alegaciones de cada abogado se limitará, a una hora en los recursos de casación en la forma y a dos horas en los de casación en el fondo. En los demás asuntos que conozca la Corte Suprema, las alegaciones sólo podrán durar media hora.

El tribunal podrá, sin embargo, por unanimidad, prorrogar por igual tiempo la duración de las alegaciones. Con todo, si se tratare de una materia distinta de la casación, el tribunal podrá prorrogar el plazo por simple mayoría.

Las partes podrán, hasta el momento de verse el recurso, consignar en escrito firmado por un abogado, que no sea procurador del número, las observaciones que estimen convenientes para el fallo del recurso.

**Art. 784.** El recurso de casación se sujetará, además, a las disposiciones especiales de los Párrafos 2°, 3° y 4° de este Título, según sea la naturaleza del juicio en que se haya pronunciado la sentencia recurrida.

**Art. 785.** Cuando la Corte Suprema invalide una sentencia por casación en el fondo, dictará acto continuo y sin nueva vista, pero separadamente, sobre la cuestión materia del juicio que haya sido objeto del recurso, la sentencia que crea conforme a la ley y al mérito de los hechos tales como se han dado por establecidos en el fallo recurrido, reproduciendo los fundamentos de derecho de la resolución casada que no se refieran a los puntos que hayan sido materia del recurso y la parte del fallo no afectada por éste.

En los casos en que desechare el recurso de casación en el fondo por defectos en su formalización, podrá invalidar de oficio la sentencia recurrida, si se hubiere dictado con infracción de ley y esta infracción haya influido substancialmente en lo dispositivo de la sentencia. La Corte deberá hacer constar en el fallo de casación esta circunstancia y los motivos que la determinan, y dictará sentencia de reemplazo con arreglo a lo que dispone el inciso precedente.

**Art. 786.** En los casos de casación en la forma, la misma sentencia que declara la casación determinará el estado en que queda el proceso, el cual se remitirá para su conocimiento al tribunal correspondiente.

Este tribunal es aquel a quien tocaría conocer del negocio en caso de recusación del juez o jueces que pronunciaron la sentencia casada.

Si el vicio que diere lugar a la invalidación de la sentencia fuere alguno de los contemplados en las causales 4a, 5a, 6a y 7a del artículo 768, deberá el mismo tribunal, acto continuo y sin nueva vista, pero separadamente, dictar la sentencia que corresponda con arreglo a la ley.

Lo dispuesto en el inciso precedente regirá, también, en los casos del inciso primero del artículo 776, si el tribunal respectivo invalida de oficio la sentencia por alguna de las causales antes señaladas.

**Art. 787.** Derogado


***2. Disposiciones especiales del recurso de casación contra sentencias pronunciadas en juicios de mínima cuantía.***
 
**Art. 788. (962).** En los juicios de mínima cuantía sólo hay lugar al recurso de casación en la forma, en los casos de los números 1°, 2°, 4°, 6°, 7° y 9° del artículo 768.

**Art. 789. (963).** En estos juicios sólo se considerarán diligencias o trámites esenciales, el emplazamiento del demandado en la forma prescrita por la ley para que conteste la demanda y el acta en que deben consignarse las peticiones de las partes y el llamado a conciliación.

**Art. 790. (964).** El recurso se interpondrá verbalmente o por escrito sin previo anuncio y sólo se hará mención expresa de la causa en que se funde. Si se interpone verbalmente, se dejará de ella testimonio en un acta que firmarán el juez y el recurrente.

**Art. 791. (965).** El recurso de casación se interpondrá
en el plazo fatal de cinco días.

**Art. 792. (966).** Derogado.

**Art. 793.** Elevado el proceso a un tribunal colegiado o encontrando éste admisible el recurso en el caso del artículo 781, mandará que se traigan sobre él los autos en relación.

Regirán también en este caso las disposiciones del inciso 2° del artículo 699 y los artículos 701 y 702.

**Art. 794.** Si la causal alegada necesita probarse, se abrirá un término con tal objeto y se rendirá la prueba según las reglas establecidas para los incidentes.

	
***3. Disposiciones especiales de los recursos de casación contra sentencias pronunciadas en primera o en única instancia en juicios de mayor o menor cuantía y en juicios especiales.***

**Art. 795. (967).** En general, son trámites o diligencias esenciales en la primera o en la única instancia en los juicios de mayor o de menor cuantía y en los juicios especiales:

1°. El emplazamiento de las partes en la forma prescrita por la ley;

2°. El llamado a las partes a conciliación, en los casos en que corresponda conforme a la ley;

3°. El recibimiento de la causa a prueba cuando proceda con arreglo a la ley;

4°. La práctica de diligencias probatorias cuya omisión podría producir indefensión;

5°. La agregación de los instrumentos presentados oportunamente por las partes, con citación o bajo el apercibimiento legal que corresponda respecto de aquélla contra la cual se presentan;

6°. La citación para alguna diligencia de prueba; y

7°. La citación para oír sentencia definitiva, salvo que la ley no establezca este trámite.

**Art. 796. (968).** En los juicios de mayor cuantía seguidos ante arbitradores son trámites esenciales los que las partes expresen en el acto constitutivo del compromiso, y, si nada han expresado acerca de esto, sólo los comprendidos en los números 1° y 5° del artículo precedente.

**Art. 797. (969).** Regirán también para los recursos de casación, en los juicios de menor cuantía, lo dispuesto en el inciso 2° del artículo 699, y en los artículos 701 y 702.

**Art. 798.** El recurso de casación en la forma contra la sentencia de primera instancia se verá conjuntamente con la apelación. Deberá dictarse una sola sentencia para fallar la apelación y desechar la casación en la forma.

Cuando se dé lugar a este último recurso, se tendrá como no interpuesto el recurso de apelación.

Si sólo se ha interpuesto recurso de casación en la forma, se mandarán traer los autos en relación.

**Art. 799. (970).** Cuando la causa alegada necesite de prueba, el tribunal abrirá para rendirla un término prudencial que no exceda de treinta días.


***4. Disposiciones especiales de los recursos decasación contra sentencias pronunciadas en segundainstancia en juicios de mayor o de menor cuantía y enjuicios especiales***

**Art. 800. (971).** En general, son trámites o diligencias esenciales en la segunda instancia de los juicios de mayor o de menor cuantía y en los juicios especiales:

1°. El emplazamiento de las partes, hecho antes de que el superior conozca del recurso;

2°. La agregación de los instrumentos presentados oportunamente por las partes, con citación o bajo el apercibimiento legal que corresponda respecto de aquélla contra la cual se presentan;

3°. La citación para oír sentencia definitiva;

4°. La fijación de la causa en tabla para su vista en los tribunales colegiados, en la forma establecida en el artículo 163, y

5°. Los indicados en los números 3°, 4° y 6° del artículo 795, en caso de haberse aplicado lo dispuesto en el artículo 207.

**Art. 801. (972).** Derogado.

**Art. 802. (973).** Derogado.  	
Artículo 803.- El recurrente, hasta antes de la vista del recurso, podrá designar un abogado para que lo defienda ante el tribunal ad-quem, que podrá ser o no el mismo que patrocinó el recurso.

**Art. 804. (975).** Derogado.

**Art. 805. (976).** Tratándose de un recurso de casación en el fondo, cada parte podrá presentar por escrito, y aun impreso, un informe en derecho hasta el momento de la vista de la causa.

No se podrá sacar los autos de la secretaría para estos informes.

En la vista de la causa no se podrá hacer alegación alguna extraña a las cuestiones que sean objeto del recurso, ni se permitirá la lectura de escritos o piezas de los autos, salvo que el presidente lo autorice para esclarecer la cuestión debatida.

El tribunal dictará sentencia dentro de los cuarenta días siguientes a aquel en que haya terminado la vista.

**Art. 806. (977).** Cuando el recurso sea de casación en la forma, dispondrá el tribunal que se traigan los autos en relación, y fallará la causa en el término de veinte días contados desde aquél en que terminó la vista.

**Art. 807. (978).** En el recurso de casación en el fondo, no se podrán admitir ni decretar de oficio para mejor proveer pruebas de ninguna clase que tiendan a establecer o esclarecer los hechos controvertidos en el juicio en que haya recaído la sentencia recurrida.

Si la casación es en la forma, tendrá lugar lo dispuesto en el artículo 799.

**Art. 808. (979).** Si contra una misma sentencia se interponen recursos de casación en la forma y en el fondo, éstos se tramitarán y verán conjuntamente y se resolverán en un mismo fallo.

Si se acoge el recurso de forma, se tendrá como no interpuesto el de fondo.

**Art. 809.** Derogado.

## Título XX DEL RECURSO DE REVISION

**Art. 810. (981).** La Corte Suprema de Justicia podrá rever una sentencia firme en los casos siguientes:

1°. Si se ha fundado en documentos declarados falsos por sentencia ejecutoria, dictada con posterioridad a la sentencia que se trata de rever;
 
2°. Si pronunciada en virtud de pruebas de testigos, han sido éstos condenados por falso testimonio dado especialmente en las declaraciones que sirvieron de único fundamento a la sentencia;
 
3°. Si la sentencia firme se ha ganado injustamente en virtud de cohecho, violencia u otra maquinación fraudulenta, cuya existencia haya sido declarada por sentencia de término; y
 
4°. Si se ha pronunciado contra otra pasada en autoridad de cosa juzgada y que no se alegó en el juicio en que la sentencia firme recayó.

El recurso de revisión no procede respecto de las sentencias pronunciadas por la Corte Suprema, conociendo en los recursos de casación o de revisión.

**Art. 811. (982).** El recurso de revisión sólo podrá interponerse dentro de un año, contado desde la fecha de la última notificación de la sentencia objeto del recurso.

Si se presenta pasado este plazo, se rechazará de plano.

Sin embargo, si al terminar el año no se ha aún fallado el juicio dirigido a comprobar la falsedad de los documentos, el perjurio de los testigos o el cohecho, violencia u otra maquinación fraudulenta a que se refiere el artículo anterior, bastará que el recurso se interponga dentro de aquel plazo, haciéndose presente en él esta circunstancia, y debiendo proseguirse inmediatamente después de obtenerse sentencia firme en dicho juicio.

**Art. 812. (983).** Derogado.

**Art. 813. (984).** Presentado el recurso, el tribunal ordenará que se traigan a la vista todos los antecedentes del juicio en que recayó la sentencia impugnada y citará a las partes a quienes afecte dicha sentencia para que comparezcan en el término de emplazamiento a hacer valer su derecho.Los trámites posteriores al vencimiento de este término se seguirán conforme a lo establecido para la substanciación de los incidentes, oyéndose al fiscal judicial antes de la vista de la causa.

**Art. 814. (985).** Por la interposición de este recurso no se suspenderá la ejecución de la sentencia impugnada.Podrá, sin embargo, el tribunal, en vista de las circunstancias, a petición del recurrente, y oído el fiscal judicial, ordenar que se suspenda la ejecución de la sentencia, siempre que aquél dé fianza bastante para satisfacer el valor de lo litigado y los perjuicios que se causen con la inejecución de la sentencia, para el caso de que el recurso sea desestimado.

**Art. 815. (986).** Si el tribunal estima procedente la revisión por haberse comprobado, con arreglo a la ley, los hechos en que se funda, lo declarará así, y anulará en todo o en parte la sentencia impugnada.

En la misma sentencia que acepte el recurso de revisión declarará el tribunal si debe o no seguirse nuevo juicio. En el primer caso determinará, además, el estado en que queda el proceso, el cual se remitirá para su conocimiento al tribunal de que proceda.

Servirán de base al nuevo juicio las declaraciones que se hayan hecho en el recurso de revisión, las cuales no podrán ser ya discutidas.

**Art. 816. (987).** Cuando el recurso de revisión se declare improcedente, se condenará en las costas del juicio al que lo haya promovido y se ordenará que sean devueltos al tribunal que corresponda los autos mandados traer a la vista.



