# Libro Primero. DISPOSICIONES COMUNES A TODO PROCEDIMIENTO. {.unnumbered}


## Título I. REGLAS GENERALES.

**Artículo 1°** Las disposiciones de este Código rigen el procedimiento de las contiendas civiles entre partes y de los actos de jurisdicción no contenciosa, cuyo conocimiento corresponda a los Tribunales de Justicia.

**Art. 2°** El procedimiento es `ordinario` o extraordinario. Es ordinario el que se somete a la tramitación común ordenada por la ley, y extraordinario el que se rige por las disposiciones especiales que para determinados casos ella establece.

**Art. 3°** Se aplicará el procedimiento ordinario en todas las gestiones, trámites y actuaciones que no estén sometidos a una regla especial diversa, cualquiera que sea su naturaleza.



## Título II. DE LA COMPARECENCIA EN JUICIO.

**Artículo 4°. (5).** Toda persona que deba comparecer en juicio a su propio nombre o como representante legal de otra, deberá hacerlo en la forma que determine la ley.

**Art. 5° (6°).** Si durante el juicio fallece alguna de las partes que obre por sí misma, quedará suspenso por este hecho el procedimiento, y se pondrá su estado en noticia de los herederos para que comparezcan a hacer uso de su derecho en un plazo igual al de emplazamiento para contestar demandas, que conceden los artículos 258 y 259.

**Art. 6° (7°).** El que comparezca en juicio a nombre de otro, en desempeño de un mandato o en ejercicio de un cargo que requiera especial nombramiento, deberá exhibir el título que acredite su representación.

Para obrar como mandatario se considerará poder suficiente: 1° El constituido por escritura pública otorgada ante notario o ante oficial del Registro Civil a quien la ley confiera esta facultad; 2° el que conste de un acta extendida ante un juez de letras o ante un juez árbitro, y subscrita por todos los otorgantes; y 3° el que conste de una declaración escrita del mandante, autorizada por el secretario del tribunal que esté conociendo de la causa.

Podrá, sin embargo, admitirse la comparecencia al juicio de una persona que obre sin poder en beneficio de otra, con tal que ofrezca garantía de que el interesado aprobará lo que se haya obrado en su nombre. El tribunal, para aceptar la representación, calificará las circunstancias del caso y la garantía ofrecida, y fijará un plazo para la ratificación del interesado.

Los agentes oficiosos deberán ser personas capacitadas para comparecer ante el respectivo tribunal, en conformidad a la Ley Orgánica del Colegio de Abogados, o, en caso contrario, deberán hacerse representar en la forma que esa misma ley establece.

**Art. 7° (8°).** El poder para litigar se entenderá conferido para todo el juicio en que se presente, y aun cuando no exprese las facultades que se conceden, autorizará al procurador para tomar parte, del mismo modo que podría hacerlo el poderdante, en todos los trámites e incidentes del juicio y en todas las cuestiones que por vía de reconvención se promuevan, hasta la ejecución completa de la sentencia definitiva, salvo lo dispuesto en el artículo 4° o salvo que la ley exija intervención personal de la parte misma. Las cláusulas en que se nieguen o en que se limiten las facultades expresadas, son nulas. Podrá, asimismo, el procurador delegar el poder obligando al mandante, a menos que se le haya negado esta facultad.

Sin embargo, no se entenderán concedidas al procurador, sin expresa mención, las facultades de desistirse en primera instancia de la acción deducida, aceptar la demanda contraria, absolver posiciones, renunciar los recursos o los términos legales, transigir, comprometer, otorgar a los árbitros facultades de arbitradores, aprobar convenios y percibir.

**Art. 8°. (9°).** El gerente o administrador de sociedades civiles o comerciales, o el presidente de las corporaciones o fundaciones con personalidad jurídica, se entenderán autorizados para litigar a nombre de ellas con las facultades que expresa el inciso 1° del artículo anterior, no obstante cualquiera limitación establecida en los estatutos o actos constitutivos de la sociedad o corporación.

**Art. 9°. (10).** Si durante el curso del juicio termina por cualquiera causa el carácter con que una persona representa por ministerio de la ley derechos ajenos, continuará no obstante la representación y serán válidos los actos que ejecute, hasta la comparecencia de la parte representada, o hasta que haya testimonio en el proceso de haberse notificado a ésta la cesación de la representación y el estado del juicio. El representante deberá gestionar para que se practique esta diligencia dentro del plazo que el tribunal designe, bajo pena de pagar una multa de un cuarto a un sueldo vital y de abonar los perjuicios que resulten.

**Art. 10 (11).** Todo procurador legalmente constituido conservará su carácter de tal mientras en el proceso no haya testimonio de la expiración de su mandato.

Si la causa de la expiración del mandato es la renuncia del procurador, estará éste obligado a ponerla en conocimiento de su mandante, junto con el estado del juicio, y se entenderá vigente el poder hasta que haya transcurrido el término de emplazamiento desde la notificación de la renuncia al mandante.

**Art. 11 (12).** Cuando se ausente de la República alguna persona dejando procurador autorizado para obrar en juicio o encargado con poder general de administración, todo el que tenga interés en ello podrá exigir que tome la representación del ausente dicho procurador, justificando que ha aceptado el mandato expresamente o ha ejecutado una gestión cualquiera que importe aceptación.

Este derecho comprende aun la facultad de hacer notificar las nuevas demandas que se entablen contra el ausente, entendiéndose autorizado el procurador para aceptar la notificación, a menos que se establezca lo contrario de un modo expreso en el poder.

Si el poder para obrar en juicio se refiere a uno o más negocios determinados, sólo podrá hacerse valer el derecho que menciona el inciso precedente respecto del negocio o negocios para los cuales se ha conferido el mandato.

**Art. 12 (13).** En los casos de que trata el artículo 19, el procurador común será nombrado por acuerdo de las partes a quienes haya de representar.

El nombramiento deberá hacerse dentro del término razonable que señale el tribunal.

**Art. 13 (14).** Si por omisión de todas las partes o por falta de avenimiento entre ellas no se hace el nombramiento dentro del término indicado en el artículo anterior, lo hará el tribunal que conozca de la causa, debiendo, en este caso, recaer el nombramiento en un procurador del número o en una de las partes que haya concurrido.

Si la omisión es de alguna o algunas de las partes, el nombramiento hecho por la otra u otras valdrá respecto de todas.

**Art. 14 (15).** Una vez hecho por las partes o por el tribunal el nombramiento de procurador común, podrá revocarse por acuerdo unánime de las mismas partes, o por el tribunal a petición de alguna de ellas, si en este caso hay motivos que justifiquen la revocación.

Los procedimientos a que dé lugar esta medida se seguirán en cuaderno separado y no suspenderán el curso del juicio.

Sea que se acuerde por las partes o que se decrete por el tribunal, la revocación no comenzará a producir sus efectos mientras no quede constituido el nuevo procurador.

**Art. 15 (16).** El procurador común deberá ajustar, en lo posible, su procedimiento a las instrucciones y a la voluntad de las partes que representa; y, en los casos en que éstas no estén de acuerdo, podrá proceder por sí solo y como se lo aconseje la prudencia, teniendo siempre en mira la más fiel y expedita ejecución del mandato.

**Art. 16 (17).** Cualquiera de las partes representadas por el procurador común que no se conforme con el procedimiento adoptado por él, podrá separadamente hacer las alegaciones y rendir las pruebas que estime conducentes, pero sin entorpecer la marcha regular del juicio y usando los mismos plazos concedidos al procurador común. Podrá, asimismo, solicitar dichos plazos o su ampliación, o interponer los recursos a que haya lugar, tanto sobre las resoluciones que recaigan en estas solicitudes, como sobre cualquiera sentencia interlocutoria o definitiva.



## Título III. DE LA PLURALIDAD DE ACCIONES O DE PARTES

**Art. 17 (18).** En un mismo juicio podrán entablarse dos o más acciones con tal que no sean incompatibles.

Sin embargo, podrán proponerse en una misma demanda dos o más acciones incompatibles para que sean resueltas una como subsidiaria de otra.

**Art. 18 (19).** En un mismo juicio podrán intervenir como demandantes o demandados varias personas siempre que se deduzca la misma acción, o acciones que emanen directa e inmediatamente de un mismo hecho, o que se proceda conjuntamente por muchos o contra muchos en los casos que autoriza la ley.

**Art. 19 (20).** Si son dos o más las partes que entablan una demanda o gestión judicial y deducen las mismas acciones, deberán obrar todas conjuntamente, constituyendo un solo mandatario.

La misma regla se aplicará a los demandados cuando sean dos o más y opongan idénticas excepciones o defensas.

**Art. 20 (21).** Si son distintas entre sí las acciones de los demandantes o las defensas de los demandados, cada uno de ellos podrá obrar separadamente en el juicio, salvo las excepciones legales.

Se concederá la facultad de gestionar por separado en los casos del artículo anterior desde que aparezca haber incompatibilidad de intereses entre las partes que litigan conjuntamente.

**Art. 21 (22).** Si la acción ejercida por alguna persona corresponde también a otra u otras personas determinadas, podrán los demandados pedir que se ponga la demanda en conocimiento de las que no hayan ocurrido a entablarla, quienes deberán expresar en el término de emplazamiento si se adhieren a ella.

Si las dichas personas se adhieren a la demanda, se aplicará lo dispuesto en los artículos 12 y 13; si declaran su resolución de no adherirse, caducará su derecho; y si nada dicen dentro del término legal, les afectará el resultado del proceso, sin nueva citación. En este último caso podrán comparecer en cualquier estado del juicio, pero respetando todo lo obrado con anterioridad.

**Art. 22 (23).** Si durante la secuela del juicio se presenta alguien reclamando sobre la cosa litigada derechos incompatibles con los de las otras partes, admitirá el tribunal sus gestiones en la forma establecida por el artículo 16 y se entenderá que acepta todo lo obrado antes de su presentación, continuando el juicio en el estado en que se encuentre.

**Art. 23 (24).** Los que, sin ser partes directas en el juicio, tengan interés actual en sus resultados, podrán en cualquier estado de él intervenir como coadyuvantes, y tendrán en tal caso los mismos derechos que concede el artículo 16 a cada una de las partes representadas por un procurador común, continuando el juicio en el estado en que se encuentre.

Se entenderá que hay interés actual siempre que exista comprometido un derecho y no una mera expectativa, salvo que la ley autorice especialmente la intervención fuera de estos casos.

Si el interés invocado por el tercero es independiente del que corresponde en el juicio a las dos partes, se observará lo dispuesto en el artículo anterior.

**Art. 24 (25).** Las resoluciones que se dicten en los casos de los dos artículos anteriores producirán respecto de las personas a quienes dichos artículos se refieren los mismos efectos que respecto de las partes principales.



## Título IV. DE LAS CARGAS PECUNIARIAS A QUE ESTAN SUJETOS LOS LITIGANTES

**Art. 25 (26).** Todo litigante está obligado a pagar a los oficiales de la administración de justicia los derechos que los aranceles judiciales señalen para los servicios prestados en el proceso.

Cada parte pagará los derechos correspondientes a las diligencias que haya solicitado, y todas por cuotas iguales los de las diligencias comunes, sin perjuicio del reembolso a que haya lugar cuando por la ley o por resolución de los tribunales corresponda a otras personas hacer el pago.

**Art. 26 (27).** Los derechos de cada diligencia se pagarán tan pronto como ésta se evacue; pero la falta de pago no podrá entorpecer en ningún caso la marcha del juicio.

**Art. 27 (28).** Cuando litiguen varias personas conjuntamente, cada una de ellas responderá solidariamente del pago de los derechos que a todas afecten en conformidad a los artículos anteriores, sin perjuicio de que las demás reembolsen a la que haya pagado la cuota que les corresponda, a prorrata de su interés en el juicio.

**Artículo 28.-** Los procuradores judiciales responderán personalmente del pago de las costas procesales generadas durante el ejercicio de sus funciones, que sean de cargo de sus mandantes, sin perjuicio de la responsabilidad de éstos.



## Título V. DE LA FORMACION DEL PROCESO, DE SU CUSTODIA Y DE SU COMUNICACION A LAS PARTES

**Artículo 29.-** Se formará la carpeta electrónica con los escritos, documentos, resoluciones, actas de audiencias y actuaciones de toda especie que se presenten o verifiquen en el juicio. Estos antecedentes serán registrados y conservados íntegramente en orden sucesivo conforme a su fecha de presentación o verificación a través de cualquier medio que garantice la fidelidad, preservación y reproducción de su contenido, lo que se regulará mediante auto acordado de la Corte Suprema.

La carpeta electrónica estará disponible en el portal de internet del Poder Judicial, salvo que la ley establezca lo contrario o habilite al tribunal para restringir su publicidad, o la de alguna parte de ella.

Ninguna pieza de la carpeta electrónica podrá eliminarse sin que previamente lo decrete el tribunal que conoce de la causa.

**Artículo 30.-** Los escritos y documentos se presentarán por vía electrónica conforme se dispone en los artículos 5º y 6º, respectivamente, de la Ley General sobre Tramitación Electrónica de los Procedimientos Judiciales.

Los escritos se encabezarán con una suma que indique su contenido o el trámite de que se trata.

**Art. 31 (32).** Derogado.

**Art. 32 (33).** Entregado un escrito al secretario, deberá éste en el mismo día estampar en cada foja la fecha y su media firma, o un sello autorizado por la respectiva Corte de Apelaciones y que designe la oficina y la fecha de la presentación. Deberá, además, dar recibo de los documentos que se le entreguen, siempre que lo exija la parte que los presenta, sin que pueda cobrar derecho alguno por los servicios a que este artículo se refiere.

**Artículo 33.-** Los secretarios letrados de los juzgados civiles podrán dictar por sí solos las sentencias interlocutorias, autos y decretos, providencias o proveídos, salvo cuando ello pudiere importar poner término al juicio o hacer imposible su continuación. La reposición que sea procedente en contra de estas resoluciones, en su caso, será resuelta por el juez.

**Art. 34 (35).** Todas las piezas que deben formar la carpeta electrónica se irán agregando sucesivamente según el orden de su presentación. El sistema de tramitación electrónica del Poder Judicial numerará automáticamente cada pieza de la carpeta electrónica en cifras y letras. Se exceptúan las piezas que, por su naturaleza, no puedan agregarse o que por motivos fundados se manden reservar fuera del proceso.

**Art. 35 (36).** Derogado.

**Artículo 36.-** Las piezas que se presenten al tribunal se mantendrán bajo su custodia y responsabilidad. Éstas no podrán retirarse sino por las personas y en los casos expresamente contemplados en la ley. Corresponderá al tribunal velar por el estricto cumplimiento de lo establecido en el artículo 393 del Código Orgánico de Tribunales.

**Artículo 37.-** Cuando los tribunales pidan o hayan de oír dictamen por escrito del respectivo fiscal judicial o de los defensores públicos, les enviarán comunicación de la carpeta electrónica a la que deben acceder electrónicamente.

Si estos funcionarios retardan dicho dictamen, podrá el tribunal señalarles un plazo razonable para que lo envíen o agreguen a la carpeta electrónica.

En aquellos casos en que otro tribunal requiera la remisión del expediente original o de algún cuaderno o pieza del proceso, el trámite se cumplirá enviando la correspondiente comunicación de la carpeta electrónica a la que deben acceder a través del sistema de tramitación electrónica del Poder Judicial. Lo mismo se aplicará cada vez que la ley ordene la remisión, devolución o envío del proceso o de cualquiera de sus piezas a otro tribunal.



## Título VI. DE LAS NOTIFICACIONES

**Art. 38 (41).** Las resoluciones judiciales sólo producen efecto en virtud de notificación hecha con arreglo a la ley, salvo los casos expresamente exceptuados por ella.

**Art. 39 (42).** Para la validez de la notificación no se requiere el consentimiento del notificado.

**Art. 40 (43).** En toda gestión judicial, la primera notificación a las partes o personas a quienes hayan de afectar sus resultados, deberá hacérseles personalmente, entregándoseles copia íntegra de la resolución y de la solicitud en que haya recaído, cuando sea escrita.

Esta notificación se hará al actor en la forma establecida en el artículo 50.

**Art. 41.** En los lugares y recintos de libre acceso público, la notificación personal se podrá efectuar en cualquier día y a cualquier hora, procurando causar la menor molestia posible al notificado. En los juicios ejecutivos, no podrá efectuarse el requerimiento de pago en público y, de haberse notificado la demanda en un lugar o recinto de libre acceso público, se estará a lo establecido en el N° 1° del artículo 443.

Además, la notificación podrá hacerse en cualquier día, entre las seis y las veintidós horas, en la morada o lugar donde pernocta el notificado o en el lugar donde éste ordinariamente ejerce su industria, profesión o empleo, o en cualquier recinto privado en que éste se encuentre y al cual se permita el acceso del ministro de fe.

Si la notificación se realizare en día inhábil, los plazos comenzarán a correr desde las cero horas del día hábil inmediatamente siguiente, y si se hubiere practicado fuera de la comuna donde funciona el tribunal, los plazos se aumentarán en la forma establecida en los artículos 258 y 259.

Igualmente, son lugares hábiles para practicar la notificación el oficio del secretario, la casa que sirva para despacho del tribunal y la oficina o despacho del ministro de fe que practique la notificación. Los jueces no podrán, sin embargo, ser notificados en el local en que desempeñan sus funciones.

**Art. 42 (45).** Podrá el tribunal ordenar que se haga la notificación en otros lugares que los expresados en el artículo anterior, cuando la persona a quien se trate de notificar no tenga habitación conocida en el lugar en que ha de ser notificada. Esta circunstancia se acreditará por certificado de un ministro de fe que afirme haber hecho las indagaciones posibles, de las cuales dejará testimonio detallado en la respectiva diligencia.

**Art. 43 (46).** La notificación se hará constar en el proceso por diligencia que subscribirán el notificado y el ministro de fe, y si el primero no puede o no quiere firmar, se dejará testimonio de este hecho en la misma diligencia.

La certificación deberá, además, señalar la fecha, hora y lugar donde se realizó la notificación y, de haber sido hecha en forma personal, precisar la manera o el medio con que el ministro de fe comprobó la identidad del notificado.

**Art. 44.** Si buscada en dos días distintos en su habitación, o en el lugar donde habitualmente ejerce su industria, profesión o empleo, no es habida la persona a quien debe notificarse, se acreditará que ella se encuentra en el lugar del juicio y cuál es su morada o lugar donde ejerce su industria, profesión o empleo, bastando para comprobar estas circunstancias la debida certificación del ministro de fe.

Establecidos ambos hechos, el tribunal ordenará que la notificación se haga entregando las copias a que se refiere el artículo 40 a cualquiera persona adulta que se encuentre en la morada o en el lugar donde la persona que se va a notificar ejerce su industria, profesión o empleo. Si nadie hay allí, o si por cualquiera otra causa no es posible entregar dichas copias a las personas que se encuentren en esos lugares, se fijará en la puerta un aviso que dé noticia de la demanda, con especificación exacta de las partes, materia de la causa, juez que conoce en ella y de las resoluciones que se notifican.

En caso que la morada o el lugar donde pernocta o el lugar donde habitualmente ejerce su industria, profesión o empleo, se encuentre en un edificio o recinto al que no se permite libre acceso, el aviso y las copias se entregarán al portero o encargado del edificio o recinto, dejándose testimonio expreso de esta circunstancia.

**Art. 45 (48).** La diligencia de notificación, en el caso del artículo precedente, se extenderá en la forma que determina el artículo 43, siendo obligada a subscribirla la persona que reciba las copias, si puede hacerlo, dejándose testimonio de su nombre, edad, profesión y domicilio.

**Art. 46 (49).** Cuando la notificación se efectúe en conformidad al artículo 44, el ministro de fe deberá dar aviso de ella al notificado, dirigiéndole con tal objeto carta certificada por correo, en el plazo de dos días contado desde la fecha de la notificación o desde que se reabran las oficinas de correo, si la notificación se hubiere efectuado en domingo o festivo. La carta podrá consistir en tarjeta abierta que llevará impreso el nombre y domicilio del receptor y deberá indicar el tribunal, el número de ingreso de la causa y el nombre de las partes. En el testimonio de la notificación deberá expresarse, además, el hecho del envío, la fecha, la oficina de correo donde se hizo y el número de comprobante emitido por tal oficina. Este comprobante deberá ser agregado al expediente a continuación del testimonio. La omisión en el envío de la carta no invalidará la notificación, pero hará responsable al infractor de los daños y perjuicios que se originen y el tribunal, previa audiencia del afectado, deberá imponerle alguna de las medidas que se señalan en los números 2, 3 y 4 del artículo 532 del Código Orgánico de Tribunales.

**Art. 47 (50).** La forma de notificación de que tratan los artículos precedentes se empleará siempre que la ley disponga que se notifique a alguna persona para la validez de ciertos actos, o cuando los tribunales lo ordenen expresamente.

Podrá, además, usarse en todo caso.

**Art. 48 (51).** Las sentencias definitivas, las resoluciones en que se reciba a prueba la causa, o se ordene la comparecencia personal de las partes, se notificarán por medio de cédulas que contengan la copia íntegra de la resolución y los datos necesarios para su acertada inteligencia.

Estas cédulas se entregarán por un ministro de fe en el domicilio del notificado, en la forma establecida en el inciso 2° del artículo 44.

Se pondrá en los autos testimonio de la notificación con expresión del día y lugar, del nombre, edad, profesión y domicilio de la persona a quien se haga la entrega. El procedimiento que establece este artículo podrá emplearse, además, en todos los casos que el tribunal expresamente lo ordene.

**Art. 49 (52).** Para los efectos del artículo anterior, todo litigante deberá, en su primera gestión judicial, designar un domicilio conocido dentro de los límites urbanos del lugar en que funcione el tribunal respectivo, y esta designación se considerará subsistente mientras no haga otra la parte interesada, aun cuando de hecho cambie su morada.

En los juicios seguidos ante los tribunales inferiores el domicilio deberá fijarse en un lugar conocido dentro de la jurisdicción del tribunal correspondiente, pero si el lugar designado se halla a considerable distancia de aquel en que funciona el juzgado, podrá éste ordenar, sin más trámites y sin ulterior recurso, que se designe otro dentro de límites más próximos.

**Artículo 50.-** Las resoluciones no comprendidas en los artículos precedentes se entenderán notificadas a las partes desde que se incluyan en un estado que deberá formarse electrónicamente, el que estará disponible diariamente en la página web del Poder Judicial con las indicaciones que el inciso siguiente expresa.

Se encabezará el estado con la fecha del día en que se forme y se mencionarán por el número de orden que les corresponda en el rol general, expresado en cifras y en letras y, además, por los apellidos del demandante y del demandado o de los primeros que figuren con dicho carácter si son varios, todas las causas en que se haya dictado resolución en aquel día y el número de resoluciones dictadas en cada una de ellas.

Estos estados se mantendrán en la página web del Poder Judicial durante al menos tres días en una forma que impida hacer alteraciones en ellos. De las notificaciones realizadas en conformidad a este artículo se dejará constancia en la carpeta electrónica el mismo día en que se publique el estado.

La notificación efectuada conforme a este artículo será nula en caso que no sea posible la visualización de la resolución referida en el estado diario por problemas técnicos del sistema de tramitación electrónica del Poder Judicial, lo que podrá declararse de oficio o a petición de parte.

**Art. 51 (54).** Para los efectos del artículo precedente, a todo proceso que se inicie se asignará un número de orden en la primera resolución que se dicte y con él figurará en el rol del tribunal, hasta su terminación.

**Art. 52 (55).** Si transcurren seis meses sin que se dicte resolución alguna en el proceso, no se considerarán como notificaciones válidas las anotaciones en el estado diario mientras no se haga una nueva notificación personalmente o por cédula.

**Art. 53 (56).** La forma de notificación de que trata el artículo 50 se hará extensiva a las resoluciones comprendidas en el artículo 48, respecto de las partes que no hayan hecho la designación a que se refiere el artículo 49 y mientras ésta no se haga.

Esta notificación se hará sin necesidad de petición de parte y sin previa orden del tribunal.

**Art. 54 (57).** Cuando haya de notificarse personalmente o por cédula a personas cuya individualidad o residencia sea difícil determinar, o que por su número dificulten considerablemente la práctica de la diligencia, podrá hacerse la notificación por medio de avisos publicados en los diarios del lugar donde se sigue la causa, o de la cabecera de la provincia o de la capital de la región, si allí no los hay. Dichos avisos contendrán los mismos datos que se exigen para la notificación personal; pero si la publicación en esta forma es muy dispendiosa, atendida la cuantía del negocio, podrá disponer el tribunal que se haga en extracto redactado por el secretario.

Para autorizar esta forma de notificación, y para determinar los diarios en que haya de hacerse la publicación y el número de veces que deba repetirse, el cual no podrá bajar de tres, procederá el tribunal con conocimiento de causa.

Cuando la notificación hecha por este medio sea la primera de una gestión judicial, será necesario, además, para su validez, que se inserte el aviso en los números del "Diario Oficial" correspondientes a los días primero o quince de cualquier mes, o al día siguiente, si no se ha publicado en las fechas indicadas.

**Art. 55 (58).** Aunque no se haya verificado notificación alguna o se haya efectuado en otra forma que la legal, se tendrá por notificada una resolución desde que la parte a quien afecte haga en el juicio cualquiera gestión que suponga conocimiento de dicha resolución, sin haber antes reclamado la falta o nulidad de la notificación.

Asimismo, la parte que solicitó la nulidad de una notificación, por el solo ministerio de la ley, se tendrá por notificada de la resolución cuya notificación fue declarada nula, desde que se le notifique la sentencia que declara tal nulidad. En caso que la nulidad de la notificación haya sido declarada por un tribunal superior, esta notificación se tendrá por efectuada al notificársele el "cúmplase" de dicha resolución.

**Art. 56 (59).** Las notificaciones que se hagan a terceros que no sean parte en el juicio, o a quienes no afecten sus resultados, se harán personalmente o por cédula.

**Art. 57.** Las diligencias de notificación que se agreguen a la carpeta electrónica, no contendrán declaración alguna del notificado, salvo que la resolución ordene o, por su naturaleza, requiera esa declaración.

**Art. 58 (61).** Las funciones que en este Título se encomiendan a los secretarios de tribunales, podrán ser desempeñadas bajo la responsabilidad de éstos, por el oficial primero de la secretaría. En aquellos lugares en que no exista receptor judicial, la notificación podrá ser hecha por el Notario Público u Oficial del Registro Civil que exista en la localidad. En todo caso, el juez siempre podrá designar como ministro de fe ad hoc a un empleado del tribunal, para el solo efecto de practicar la notificación.



## Título VII. DE LAS ACTUACIONES JUDICIALES

**Art. 59 (62).** Las actuaciones judiciales deben practicarse en días y horas hábiles.

Son días hábiles los no feriados. Son horas hábiles las que median entre las ocho y las veinte horas.

**Art. 60 (63).** Pueden los tribunales, a solicitud de parte, habilitar para la práctica de actuaciones judiciales días u horas inhábiles, cuando haya causa urgente que lo exija.

Se estimarán urgentes para este caso, las actuaciones cuya dilación pueda causar grave perjuicio a los interesados, o a la buena administración de justicia, o hacer ilusoria una providencia judicial.

El tribunal apreciará la urgencia de la causa y resolverá sin ulterior recurso.

**Art. 61 (64).** De toda actuación deberá dejarse testimonio fidedigno en la carpeta electrónica, con expresión del lugar, día, mes y año en que se verifique, de las formalidades con que se haya procedido, y de las demás indicaciones que la ley o el tribunal dispongan.

A continuación y previa lectura, firmarán todas las personas que hayan intervenido; y si alguna no sabe o se niega a hacerlo, se expresará esta circunstancia. El acta correspondiente se digitalizará e incorporará a la carpeta electrónica inmediatamente.

La autorización del funcionario a quien corresponda dar fe o certificado del acto es esencial para la validez de la actuación en todos aquellos casos en que una ley expresamente lo disponga.

En los casos de contarse con los recursos técnicos necesarios, podrán registrarse las audiencias en que participe el tribunal mediante audio digital, video u otro soporte tecnológico equivalente, el que se agregará a la carpeta electrónica inmediatamente.

**Art. 62 (65).** Siempre que en una actuación haya de tomarse juramento a alguno de los concurrentes, se le interrogará por el funcionario autorizante al tenor de la siguiente fórmula: "¿Juráis por Dios decir verdad acerca de lo que se os va a preguntar?", o bien, "¿Juráis por Dios desempeñar fielmente el cargo que se os confía?", según sea la naturaleza de la actuación. El interrogado deberá responder: "Sí juro".

**Art. 63 (66).** Cuando sea necesaria la intervención de intérprete en una actuación judicial, se recurrirá al intérprete oficial, si lo hay; y en caso contrario, al que designe el tribunal.

Los intérpretes deberán tener las condiciones requeridas para ser peritos, y se les atribuirá el carácter de ministros de fe.

Antes de practicarse la diligencia, deberá el intérprete prestar juramento para el fiel desempeño de su cargo.

**Artículo 64.-** Los plazos que señala este Código son fatales cualquiera sea la forma en que se exprese, salvo aquéllos establecidos para la realización de actuaciones propias del tribunal. En consecuencia, la posibilidad de ejercer un derecho o la oportunidad para ejecutar el acto se extingue al vencimiento del plazo. En estos casos el tribunal, de oficio o a petición de parte, proveerá lo que convenga para la prosecución del juicio, sin necesidad de certificado previo.

Las partes, en cualquier estado del juicio, podrán acordar la suspensión del procedimiento hasta dos veces por instancia, sea o no por períodos iguales, hasta un plazo máximo de noventa días en cada instancia, sin perjuicio de poder acordarla, además, ante la Corte Suprema en caso que, ante dicho tribunal, estuvieren pendientes recursos de casación o de queja en contra de sentencia definitiva. Los plazos que estuvieren corriendo se suspenderán al presentarse el escrito respectivo y continuarán corriendo vencido el plazo de suspensión acordado.

**Art. 65 (68).** Los términos comenzarán a correr para cada parte desde el día de la notificación.

Los términos comunes se contarán desde la última notificación.

**Art. 66 (69).** Los términos de días que establece el presente Código, se entenderán suspendidos durante los feriados, salvo que el tribunal, por motivos justificados, haya dispuesto expresamente lo contrario.

**Art. 67 (70).** Son prorrogables los términos señalados por el tribunal.

Para que pueda concederse la prórroga es necesario:

1° Que se pida antes del vencimiento del término; y 

2° Que se alegue justa causa, la cual será apreciada por el tribunal prudencialmente.

**Art. 68 (71).** En ningún caso podrá la prórroga ampliar el término más allá de los días asignados por la ley.

**Art. 69 (72).** Siempre que se ordene o autorice una diligencia con citación, se entenderá que no puede llevarse a efecto sino pasados tres días después de la notificación de la parte contraria, la cual tendrá el derecho de oponerse o deducir observaciones dentro de dicho plazo, suspendiéndose en tal caso la diligencia hasta que se resuelva el incidente.

Cuando se mande proceder con conocimiento o valiéndose de otras expresiones análogas, se podrá llevar a efecto la diligencia desde que se ponga en noticia del contendor lo resuelto.

**Art. 70 (73).** Todas las actuaciones necesarias para la formación del proceso se practicarán por el tribunal que conozca de la causa, salvo los casos en que se encomienden expresamente por la ley a los secretarios u otros ministros de fe, o en que se permita al tribunal delegar sus funciones, o en que las actuaciones hayan de practicarse fuera del lugar en que se siga el juicio.

**Art. 71 (74).** Todo tribunal es obligado a practicar o a dar orden para que se practiquen en su territorio, las actuaciones que en él deban ejecutarse y que otro tribunal le encomiende.

El tribunal que conozca de la causa dirigirá al del lugar donde haya de practicarse la diligencia la correspondiente comunicación, insertando los escritos, decretos y explicaciones necesarias.

El tribunal a quien se dirija la comunicación ordenará su cumplimiento en la forma que ella indique, y no podrá decretar otras gestiones que las necesarias a fin de darle curso y habilitar al juez de la causa para que resuelva lo conveniente.

**Art. 72 (75).** Las comunicaciones serán firmadas por el juez, en todo caso; y si el tribunal es colegiado, por su presidente. A las mismas personas se dirigirán las comunicaciones que emanen de otros tribunales o funcionarios.

**Art. 73 (76).** En las gestiones que sea necesario hacer ante el tribunal exhortado, podrá intervenir el encargado de la parte que solicitó el exhorto, siempre que en éste se exprese el nombre de dicho encargado o se indique que puede diligenciarlo el que lo presente o cualquiera otra persona.

**Art. 74 (77).** Podrá una misma comunicación dirigirse a diversos tribunales para que se practiquen actuaciones en distintos puntos sucesivamente. Las primeras diligencias practicadas, junto con la comunicación que las motive, se remitirán por el tribunal que haya intervenido en ellas al que deba continuarlas en otro territorio.

**Art. 75 (78).** Toda comunicación para practicar actuaciones fuera del lugar del juicio será dirigida, sin intermedio alguno, al tribunal o funcionario a quien corresponda ejecutarla, aunque no dependa del que reclama su intervención.

**Art. 76 (79).** Cuando hayan de practicarse actuaciones en país extranjero, se dirigirá la comunicación respectiva al funcionario que deba intervenir, por conducto de la Corte Suprema, la cual la enviará al Ministerio de Relaciones Exteriores para que éste a su vez le dé curso en la forma que esté determinada por los tratados vigentes o por las reglas generales adoptadas por el Gobierno.En la comunicación se expresará el nombre de la persona o personas a quienes la parte interesada apodere para practicar las diligencias solicitadas, o se indicará que puede hacerlo la persona que lo presente o cualquiera otra.

Por este mismo conducto y en la misma forma se recibirán las comunicaciones de los tribunales extranjeros para practicar diligencias en Chile.

**Artículo 77.-** Sin perjuicio de lo señalado en el artículo precedente, toda comunicación dirigida por un tribunal a otro deberá ser conducida a su destino por vía del sistema de tramitación electrónica del Poder Judicial, y no siendo posible lo anterior, por el medio de comunicación idóneo más expedito.



## Título VIII. DE LAS REBELDIAS

**Articulo 78.-** Vencido un plazo judicial para la realización de un acto procesal sin que éste se haya practicado por la parte respectiva, el tribunal, de oficio o a petición de parte, declarará evacuado dicho trámite en su rebeldía y proveerá lo que convenga para la prosecución del juicio, sin certificado previo del secretario.

**Art. 79 (82).** Podrá un litigante pedir la rescisión de lo que se haya obrado en el juicio en rebeldía suya, ofreciendo probar que ha estado impedido por fuerza mayor.

Este derecho sólo podrá reclamarse dentro de tres días, contados desde que cesó el impedimento y pudo hacerse valer ante el tribunal que conoce del negocio.

**Art. 80 (83).** Si al litigante rebelde no se le ha hecho saber en persona ninguna de las providencias libradas en el juicio, podrá pedir la rescisión de lo obrado, ofreciendo acreditar que, por un hecho que no le sea imputable, han dejado de llegar a sus manos las copias a que se refieren los artículos 40 y 44, o que ellas no son exactas en su parte substancial.

Este derecho no podrá reclamarse sino dentro de cinco días, contados desde que aparezca o se acredite que el litigante tuvo conocimiento personal del juicio.

**Art. 81 (84).** Los incidentes a que den lugar las disposiciones contenidas en los dos artículos anteriores, no suspenderán el curso de la causa principal y se substanciarán en cuaderno separado.



## Título IX. DE LOS INCIDENTES

**Art. 82 (85).** Toda cuestión accesoria de un juicio que requiera pronunciamiento especial con audiencia de las partes, se tramitará como incidente y se sujetará a las reglas de este Título, si no tiene señalada por la ley una tramitación especial.

**Artículo 83.** La nulidad procesal podrá ser declarada, de oficio o a petición de parte, en los casos que la ley expresamente lo disponga y en todos aquellos en que exista un vicio que irrogue a alguna de las partes un perjuicio reparable sólo con la declaración de nulidad.

La nulidad sólo podrá impetrarse dentro de cinco días, contados desde que aparezca o se acredite que quien deba reclamar de la nulidad tuvo conocimiento del vicio, a menos que se trate de la incompetencia absoluta del tribunal. La parte que ha originado el vicio o concurrido a su materialización o que ha convalidado tácita o expresamente el acto nulo, no podrá demandar la nulidad.

La declaración de nulidad de un acto no importa la nulidad de todo lo obrado. El tribunal, al declarar la nulidad, deberá establecer precisamente cuáles actos quedan nulos en razón de su conexión con el acto anulado.

**Art. 84 (87).** Todo incidente que no tenga conexión alguna con el asunto que es materia del juicio podrá ser rechazado de plano.

Si el incidente nace de un hecho anterior al juicio o coexistente con su principio, como defecto legal en el modo de proponer la demanda, deberá promoverlo la parte antes de hacer cualquiera gestión principal en el pleito.

Si lo promueve después, será rechazado de oficio por el tribunal salvo que se trate de un vicio que anule el proceso, en cuyo caso se estará a lo que establece el artículo 83, o que se trate de una circunstancia esencial para la ritualidad o la marcha del juicio, evento en el cual el tribunal ordenará que se practiquen las diligencias necesarias para que el proceso siga su curso legal.

El juez podrá corregir de oficio los errores que observe en la tramitación del proceso. Podrá asimismo tomar las medidas que tiendan a evitar la nulidad de los actos de procedimiento. No podrá, sin embargo, subsanar las actuaciones viciadas en razón de haberse realizado éstas fuera del plazo fatal indicado por la ley.

**Art. 85 (88).** Todo incidente originado de un hecho que acontezca durante el juicio, deberá promoverse tan pronto como el hecho llegue a conocimiento de la parte respectiva.

Si en el proceso consta que el hecho ha llegado al conocimiento de la parte, y si ésta ha practicado una gestión posterior a dicho conocimiento, el incidente promovido después será rechazado de plano, salvo que se trate de alguno de los vicios o circunstancias a que se refiere el inciso 3° del artículo anterior.

**Art. 86 (89).** Todos los incidentes cuyas causas existan simultáneamente deberán promoverse a la vez. En caso contrario, se observará, respecto de los que se promuevan después, lo dispuesto en el inciso 3° del artículo 84.

**Art. 87 (90).** Si el incidente es de aquellos sin cuya previa resolución no se puede seguir substanciando la causa principal, se suspenderá el curso de ésta, y el incidente se tramitará en la misma pieza de autos.

En el caso contrario, no se suspenderá el curso de la causa principal, y el incidente se substanciará en ramo separado.

**Artículo 88.-** La parte que haya promovido y perdido dos o más incidentes en un mismo juicio, no podrá promover ningún otro sin que previamente deposite en la cuenta corriente del tribunal la cantidad que éste fije. El tribunal de oficio y en la resolución que deseche el segundo incidente determinará el monto del depósito. Este depósito fluctuará entre una y diez unidades tributarias mensuales y se aplicará como multa a beneficio fiscal, si fuere rechazado el respectivo incidente.

El tribunal determinará el monto del depósito considerando la actuación procesal de la parte y si observare mala fe en la interposición de los nuevos incidentes podrá aumentar su cuantía hasta por el duplo. La parte que goce de privilegio de pobreza en el juicio, no estará obligada a efectuar depósito previo alguno.

El incidente que se formule sin haberse efectuado previamente el depósito fijado, se tendrá por no interpuesto y se extinguirá el derecho a promoverlo nuevamente.

En los casos que la parte no obligada a efectuar el depósito previo en razón de privilegio de pobreza interponga nuevos incidentes y éstos le sean rechazados; el juez, en la misma resolución que rechace el nuevo incidente, podrá imponer personalmente al abogado o al mandatario judicial que lo hubiere promovido, por vía de pena, una multa a beneficio fiscal de una a diez unidades tributarias mensuales, si estimare que en su interposición ha existido mala fe o el claro propósito de dilatar el proceso.

Todo incidente que requiera de depósito previo deberá tramitarse en cuaderno separado, sin afectar el curso de la cuestión principal ni de ninguna otra, sin perjuicio de lo que se pueda resolver en el fallo del respectivo incidente.

Las resoluciones que se dicten en virtud de las disposiciones de este artículo, en cuanto al monto de depósitos y multas se refiere, son inapelables.

**Art. 89 (92).** Si se promueve un incidente, se concederán tres días para responder y vencido este plazo, haya o no contestado la parte contraria, resolverá el tribunal la cuestión, si, a su juicio, no hay necesidad de prueba. No obstante, el tribunal podrá resolver de plano aquellas peticiones cuyo fallo se pueda fundar en hechos que consten del proceso, o sean de pública notoriedad, lo que el tribunal consignará en su resolución.

**Art. 90 (93).** Si es necesaria la prueba, se abrirá un término de ocho días para que dentro de él se rinda y se justifiquen también las tachas de los testigos, si hay lugar a ellas.

Dentro de los dos primeros días deberá acompañar cada parte una nómina de los testigos de que piensa valerse, con expresión del nombre y apellido, domicilio y profesión u oficio. Sólo se examinarán testigos que figuren en dicha nómina.

Cuando hayan de practicarse diligencias probatorias fuera del lugar en que se sigue el juicio, podrá el tribunal, por motivos fundados, ampliar una sola vez el término por el número de días que estime necesarios, no excediendo en ningún caso del plazo total de treinta días, contados desde que se recibió el incidente a prueba.

Las resoluciones que se pronuncien en los casos de este artículo son inapelables.

**Art. 91 (94).** Vencido el término de prueba, háyanla o no rendido las partes, y aún cuando éstas no lo pidan, fallará el tribunal inmediatamente o, a más tardar, dentro de tercero día, la cuestión que haya dado origen al incidente.


## Título X. DE LA ACUMULACION DE AUTOS

**Art. 92 (95).** La acumulación de autos tendrá lugar siempre que se tramiten separadamente dos o más procesos que deban constituir un solo juicio y terminar por una sola sentencia, para mantener la continencia, o unidad de la causa. Habrá, por tanto, lugar a ella:

1°. Cuando la acción o acciones entabladas en un juicio sean iguales a las que se hayan deducido en otro, o cuando unas y otras emanen directa e inmediatamente de unos mismos hechos;

2°. Cuando las personas y el objeto o materia de los juicios sean idénticos, aunque las acciones sean distintas; y

3°. En general, siempre que la sentencia que haya de pronunciarse en un juicio deba producir la excepción de cosa juzgada en otro.

**Art. 93 (96).** Habrá también lugar a la acumulación de autos en los casos de procedimiento concursal de liquidación.

De esta acumulación se trata en la Ley de Reorganización y Liquidación de Activos de Empresas y Personas.

**Art. 94 (97).** La acumulación de autos se decretará a petición de parte; pero si los procesos se encuentran en un mismo tribunal, podrá éste ordenarla de oficio.

Se considerará parte legítima para solicitarla todo el que haya sido admitido como parte litigante en cualquiera de los juicios cuya acumulación se pretende.

**Art. 95 (98).** Para que pueda tener lugar la acumulación, se requiere que los juicios se encuentren sometidos a una misma clase de procedimiento y que la substanciación de todos ellos se encuentre en instancias análogas.

**Art. 96 (99).** Si los juicios están pendientes ante tribunales de igual jerarquía, el más moderno se acumulará al más antiguo; pero en el caso contrario, la acumulación se hará sobre aquel que esté sometido al tribunal superior.

**Art. 97 (100).** Siempre que tenga lugar la acumulación, el curso de los juicios que estén más avanzados se suspenderá hasta que todos lleguen a un mismo estado.

**Art. 98 (101).** La acumulación se podrá pedir en cualquier estado del juicio antes de la sentencia de término; y si se trata de juicios ejecutivos, antes del pago de la obligación. Deberá solicitarse ante el tribunal a quien corresponda continuar conociendo en conformidad al artículo 96.

**Art. 99 (102).** Pedida la acumulación, se concederá un plazo de tres días a la otra parte para que exponga lo conveniente sobre ella. Pasado este término, haya o no respuesta, el tribunal resolverá, haciendo traer previamente a la vista todos los procesos cuya acumulación se solicite, si todos están pendientes ante él. En caso contrario, podrá pedir que se le remitan los que se sigan ante otros tribunales.

**Art. 100 (103).** De las resoluciones que nieguen la acumulación o den lugar a ella sólo se concederá apelación en el efecto devolutivo.



## Título XI. DE LAS CUESTIONES DE COMPETENCIA

**Art. 101 (104).** Podrán las partes promover cuestiones de competencia por inhibitoria o por declinatoria.

Las que hayan optado por uno de estos medios, no podrán después abandonarlo para recurrir al otro. Tampoco podrán emplearse los dos simultánea ni sucesivamente.

**Art. 102 (105).** La inhibitoria se intentará ante el tribunal a quien se crea competente, pidiéndole que se dirija al que esté conociendo del negocio para que se inhiba y le remita los autos.

Si el recurrente pretende acreditar con documentos su derecho, deberá acompañarlos a la solicitud de inhibitoria, o pedir en ella los testimonios correspondientes.

**Art. 103 (106).** Con sólo el mérito de lo que exponga la parte y de los documentos que presente o que el tribunal de oficio mande agregar, si lo juzga necesario, se accederá a la solicitud o se negará lugar a ella.

**Art. 104 (107).** Si el tribunal accede, dirigirá al que esté conociendo del negocio la correspondiente comunicación, con inserción de la solicitud de la parte y de los demás documentos que estime necesario para fundar su competencia.

**Art. 105 (108).** Recibida la comunicación, el tribunal requerido oirá a la parte que ante él litigue, y con lo que ella exponga y el mérito que arrojen los documentos que presente o que el tribunal mande agregar de oficio, accederá a la inhibición o negará lugar a ella.

**Art. 106 (109).** Si el tribunal requerido accede a la inhibición y esta sentencia queda ejecutoriada, remitirá los autos al requeriente.

Si la deniega, se pondrá lo resuelto en conocimiento del otro tribunal, y cada uno, con citación de la parte que gestione ante él, remitirá los autos al tribunal a quien corresponda resolver la contienda.

**Art. 107 (112).** Son apelables solamente la resolución que niega lugar a la solicitud de inhibición a que se refiere el artículo 102 y la que pronuncie el tribunal requerido accediendo a la inhibición.

**Art. 108 (113).** Las apelaciones de que trata el artículo anterior se llevarán ante el tribunal a quien correspondería conocer de la contienda de competencia; pero cuando los tribunales dependan de diversos superiores, iguales en jerarquía, conocerá de la apelación el superior del tribunal que haya dictado la sentencia apelada.

**Art. 109 (114).** El superior que conozca de la apelación o que resuelva la contienda de competencia declarará cuál de los tribunales inferiores es competente o que ninguno de ellos lo es.

Para pronunciar resolución, citará a uno y otro litigante, pudiendo pedir los informes que estime necesarios, y aun recibir a prueba el incidente.

Si los tribunales de cuya competencia se trata ejercen jurisdicción de diferente clase, se oirá también al fiscal judicial.

**Art. 110 (115).** Expedida la resolución, el mismo tribunal que la dictó remitirá los autos que ante él obren al tribunal declarado competente, para que éste comience o siga conociendo del negocio, y comunicará lo resuelto al otro tribunal.

**Art. 111 (116).** La declinatoria se propondrá ante el tribunal a quien se cree incompetente para conocer de un negocio que le esté sometido, indicándole cuál es el que se estima competente y pidiéndole se abstenga de dicho conocimiento. Su tramitación se sujetará a las reglas establecidas para los incidentes.

**Art. 112 (117).** Mientras se halle pendiente el incidente de competencia, se suspenderá el curso de la causa principal; pero el tribunal que esté conociendo de ella podrá librar aquellas providencias que tengan el carácter de urgentes.

La apelación de la resolución que desecha la declinatoria de jurisdicción se concederá sólo en el efecto devolutivo.

La tramitación de la causa, en el caso de inhibitoria, continuará después de notificada la resolución denegatoria a que se refiere el inciso 2° del artículo 106, sin perjuicio de que esas gestiones queden sin valor si el tribunal correspondiente declara que el que está conociendo del juicio es incompetente para ello.



## Título XII. DE LAS IMPLICANCIAS Y RECUSACIONES

**Art. 113 (118).** Sólo podrá inhabilitarse a los jueces y a los auxiliares de la Administración de Justicia para que intervengan en un negocio determinado, en los casos y por las causas de implicancia o recusación que señala el Código Orgánico de Tribunales.

Para inhabilitar a los peritos, la parte a quien pueda perjudicar su intervención, deberá expresar y probar alguna de las causas de implicancia o recusación determinadas para los jueces, en cuanto sean aplicables a aquéllos.

Si la recusación afectare a un abogado integrante, el Presidente de la respectiva Corte procederá de inmediato a formar sala, salvo que ello no fuera posible por causa justificada.

**Art. 114 (119).** La declaración de implicancia o de recusación cuando haya de fundarse en causa legal, deberá pedirse antes de toda gestión que ataña al fondo del negocio, o antes de que comience a actuar la persona contra quien se dirige, siempre que la causa alegada exista ya y sea conocida de la parte.

Si la causa es posterior o no ha llegado a conocimiento de la parte, deberá proponerla tan pronto como tenga noticia de ella. No justificándose esta última circunstancia, será desechada la solicitud, a menos que se trate de una implicancia. En este caso, podrá el tribunal imponer a la parte que maliciosamente haya retardado el reclamo de la implicancia una multa que no exceda de un sueldo vital.

**Art. 115 (120).** La implicancia de un juez que desempeñe tribunal unipersonal se hará valer ante él mismo, expresando la causa legal en que se apoya y los hechos en que se funda, acompañando u ofreciendo presentar las pruebas necesarias y pidiéndole se inhiba del conocimiento del negocio.

**Art. 116 (121).** La recusación de los jueces a que se refiere el artículo anterior, y la implicancia y recusación de los miembros de tribunales colegiados se harán valer, en los términos que indica dicho artículo, ante el tribunal que, según la ley, deba conocer de estos incidentes.

**Art. 117 (122).** La implicancia y la recusación de los funcionarios subalternos se reclamarán ante el tribunal que conozca del negocio en que aquéllos deban intervenir, y se admitirán sin más trámite cuando no necesiten fundarse en causa legal.

**Art. 118 (123).** Cuando deba expresarse causa, no se dará curso a la solicitud de implicancia o de recusación de los funcionarios que a continuación se mencionan, a menos que el ocurrente haya sido declarado pobre, si no se acompaña testimonio de haber efectuado un depósito en la cuenta corriente del tribunal que deba conocer de la implicancia o recusación, de las cantidades que en seguida se expresan, para responder a la multa de que habla el artículo 122.

En la implicancia o recusación del Presidente, Ministro o Fiscal de la Corte Suprema, una unidad tributaria mensual. En la del Presidente, Ministros o Fiscales de una Corte de Apelaciones, media unidad tributaria mensual. En la de un juez letrado o de un subrogante legal, juez árbitro, defensor público, relator, perito, secretario o receptor, un cuarto de unidad tributaria mensual.

La consignación ordenada en este artículo se elevará al doble cuando se trate de la segunda solicitud de inhabilitación deducida por la misma parte, al triple en la tercera y así sucesivamente.

**Art. 119 (124).** Si la causa alegada no es legal, o no la constituyen los hechos en que se funda, o si éstos no se especifican debidamente, el tribunal desechará desde luego la solicitud.

En el caso contrario, declarará bastante la causal, y si los hechos en que se funda constan al tribunal o resultan de los antecedentes acompañados o que el mismo tribunal de oficio mande agregar, se declarará, sin más trámites, la implicancia o recusación.

Cuando no conste al tribunal o no aparezca de manifiesto la causa alegada, se procederá en conformidad a las reglas generales, de los incidentes, formándose pieza separada.

**Art. 120 (125).** Una vez aceptada como bastante la causal de inhabilitación, o declarada ésta con arreglo al inciso 2° del artículo anterior, se pondrá dicha declaración en conocimiento del funcionario cuya implicancia o recusación se haya pedido, para que se abstenga de intervenir en el asunto de que se trata mientras no se resuelva el incidente.

**Art. 121 (126).** Si la inhabilitación se refiere a un juez de tribunal unipersonal, el que deba subrogarlo conforme a la ley continuará conociendo en todos los trámites anteriores a la citación para sentencia, y en este estado se suspenderá el curso del juicio hasta que se declare si ha o no lugar a la inhabilitación.

Si ésta se pide para un juez de tribunal colegiado, continuará funcionando el mismo tribunal, constituido legalmente, con exclusión del miembro o miembros que se intente inhibir, y se suspenderá el juicio como en el caso anterior.

Cuando se trate de otros funcionarios, serán reemplazados, mientras dure el incidente, por los que deban subrogarlos según la ley; y si se rechaza la inhibición, el que la haya solicitado pagará al funcionario subrogado los derechos correspondientes a las actuaciones practicadas por el subrogante, sin perjuicio de que éste también los perciba.

**Art. 122 (127).** Si la implicancia o la recusación es desechada, se condenará en las costas al que la haya reclamado, y se le impondrá una multa que no baje de la mitad ni exceda del doble de la suma consignada en conformidad al artículo 118.

Esta multa se elevará al doble cuando se trate de la segunda solicitud de inhabilitación deducida por la misma parte, al triple en la tercera y así sucesivamente.

El tribunal fijará la cuantía de la multa, tomando en cuenta la categoría del funcionario contra quien se haya reclamado, la importancia del juicio, la fortuna del litigante y la circunstancia de haberse procedido o no con malicia.

Sin perjuicio de lo dispuesto en los incisos precedentes, podrán los tribunales, a petición de parte o de oficio, después de haberse rechazado en la causa dos o más recusaciones interpuestas por un mismo litigante, fijar a éste y compartes un plazo razonable para que dentro de él deduzcan todas las que conceptúen procedentes a su derecho, bajo apercibimiento de no ser oídos después respecto de aquellas causales que se funden en hechos o circunstancias que hayan acaecido con anterioridad al decreto que fija dicho plazo.

Las recusaciones que se interpongan por causas sobrevinientes a la fecha de este decreto serán admitidas previa consignación de la multa, y, en caso de ser desestimadas, pueden también las Cortes imponer al recurrente, a más de la multa establecida, otra que no deberá exceder de un sueldo vital por cada instancia de recusación.

**Art. 123 (128).** Paralizado el incidente de implicancia o de recusación por más de diez días, sin que la parte que lo haya promovido haga gestiones conducentes para ponerlo en estado de que sea resuelto, el tribunal lo declarará de oficio abandonado, con citación del recusante.

**Art. 124 (129).** Antes de pedir la recusación de un juez al tribunal que deba conocer del incidente, podrá el recusante ocurrir al mismo recusado, si funciona solo, o al tribunal de que forme parte, exponiéndole la causa en que la recusación se funda y pidiéndole la declare sin más trámite.

Rechazada esta solicitud, podrá deducirse la recusación ante el tribunal correspondiente.

**Artículo 125.-** Producida alguna de las situaciones previstas en el artículo 199 del Código Orgánico de Tribunales respecto de las causales de recusación, la parte a quien, según la presunción de la ley, pueda perjudicar la falta de imparcialidad que se supone en el juez, deberá alegar la inhabilidad correspondiente dentro del plazo de cinco días contados desde que se le notifique la declaración respectiva. Si así no lo hiciere, se considerará renunciada la correspondiente causal de recusación. Durante este plazo, el juez se considerará inhabilitado para conocer de la causa y se estará a lo dispuesto en el artículo 121 de este Código.

**Art. 126 (131).** Las sentencias que se dicten en los incidentes sobre implicancia o recusación serán inapelables, salvo la que pronuncie el juez de tribunal unipersonal desechando la implicancia deducida ante él, aceptando la recusación en el caso del artículo 124 o declarándose de oficio inhabilitado por alguna causal de recusación.

Toda sentencia sobre implicancia o recusación será transcrita de oficio al juez o tribunal a quien afecte.

**Art. 127 (132).** La recusación y la implicancia que deban surtir efecto en diversos juicios de las mismas partes, podrán hacerse valer en una sola gestión.

**Art. 128 (133).** Cuando sean varios los demandantes o los demandados, la implicancia o recusación deducida por alguno de ellos, no podrá renovarse por los otros, a menos de fundarse en alguna causa personal del recusante.



## Título XIII. DEL PRIVILEGIO DE POBREZA

**Art. 129 (137).** En las gestiones para obtener privilegio de pobreza, los derechos que se causen sólo podrán reclamarse en caso de que no se dé lugar a la solicitud.

**Art. 130 (138).** El privilegio de pobreza podrá solicitarse en cualquier estado del juicio y aún antes de su iniciación, y deberá siempre pedirse al tribunal a quien corresponda conocer en única o primera instancia del asunto en que haya de tener efecto.

Podrá tramitarse en una sola gestión para varias causas determinadas y entre las mismas partes, si el conocimiento de todas corresponde al mismo tribunal en primera instancia.

**Art. 131 (139).** El privilegio de pobreza se tramitará en cuaderno separado y se expresarán al solicitarlo los motivos en que se funde. El tribunal ordenará que se rinda información para acreditarlos, con solo la citación de la parte contra quien litigue o haya de litigar el que solicita el privilegio.

**Art. 132 (140).** Si la parte citada no se opone dentro de tercero día a la concesión del privilegio, se rendirá la información y se resolverá con el mérito de ella y de los demás antecedentes acompañados o que el tribunal mande agregar.

Si hay oposición, se tramitará el incidente en conformidad a las reglas generales.

La apelación de la sentencia que acepte el privilegio de pobreza se concederá sólo en el efecto devolutivo.

**Art. 133 (141).** En la gestión de privilegio de pobreza serán oídos los funcionarios judiciales a quienes pueda afectar su concesión, si se presentan oponiéndose antes de que el incidente se resuelva. Cuando sean varios los que deduzcan la oposición, litigarán por una cuerda en los trámites posteriores a la presentación.

**Art. 134 (142).** Serán materia de la información, o de la prueba en su caso, las circunstancias invocadas por el que pide el privilegio, y además la fortuna del solicitante, su profesión o industria, sus rentas, sus deudas, las cargas personales o de familia que le graven, sus aptitudes intelectuales y físicas para ganar la subsistencia, sus gastos necesarios o de lujo, las comodidades de que goce, y cualesquiera otras que el tribunal juzgue conveniente averiguar para formar juicio sobre los fundamentos del privilegio.

**Art. 135 (143).** Se estimará como presunción legal de pobreza la circunstancia de encontrarse preso el que solicita el privilegio, sea por sentencia condenatoria, sea durante la substanciación del juicio criminal.

**Art. 136 (144).** Podrá dejarse sin efecto el privilegio después de otorgado, siempre que se justifiquen circunstancias que habrían bastado para denegarlo.

Podrá también otorgarse el privilegio después de rechazado, si se prueba un cambio de fortuna o de circunstancias que autoricen esta concesión.

**Art. 137 (136).** Cuando el litigante declarado pobre no gestione personalmente ni tenga en el proceso mandatario constituido en forma legal, entrará a representarlo el procurador de pobres, sin que sea necesario mandato expreso.


## Título XIV. DE LAS COSTAS

**Art. 138 (145).** Cuando una de las partes sea condenada a pagar las costas de la causa, o de algún incidente o gestión particular, se procederá a tasarlas en conformidad a las reglas siguientes.

**Art. 139 (146).** Las costas se dividen en procesales y personales.

Son procesales las causadas en la formación del proceso y que correspondan a servicios estimados en los aranceles judiciales.

Son personales las provenientes de los honorarios de los abogados y demás personas que hayan intervenido en el negocio, y de los defensores públicos en el caso del artículo 367 del Código Orgánico de Tribunales.

Los honorarios de los abogados se regularán de acuerdo con el arancel fijado por el respectivo Colegio Provincial de Abogados y a falta de éste, por el del Consejo General del Colegio de Abogados.

El honorario que se regule en conformidad al inciso anterior, pertenecerá a la parte a cuyo favor se decretó la condenación en costas; pero si el abogado lo percibe por cualquier motivo, se imputará al que se haya estipulado o al que deba corresponderle.

**Art. 140 (147).** Sólo se tasarán las costas procesales útiles, eliminándose las que correspondan a diligencias o actuaciones innecesarias o no autorizadas por la ley, y las de actuaciones o incidentes en que haya sido condenada la otra parte.

El tribunal de la causa, en cada instancia, regulará el valor de las personales, y avaluará también las procesales con arreglo a la ley de aranceles. Esta función podrá delegarla en uno de sus miembros, si es colegiado, y en su secretario respecto de las costas procesales.

**Art. 141 (148).** Hecha la tasación de costas, en la forma prevenida por los artículos anteriores, y puesta en conocimiento de las partes, se tendrá por aprobada si ellas nada exponen dentro de tercero día.

**Art. 142 (149).** Si alguna de las partes formula objeciones, podrá el tribunal resolver de plano sobre ellas, o darles la tramitación de un incidente.

**Art. 143 (150).** La tasación de costas, hecha según las reglas precedentes, se entenderá sin perjuicio del derecho de las personas cuyos honorarios se hayan tasado, para exigir de quien corresponda el pago de sus servicios en conformidad a la ley.

**Art. 144 (151).** La parte que sea vencida totalmente en un juicio o en un incidente, será condenada al pago de las costas. Podrá con todo el tribunal eximirla de ellas, cuando aparezca que ha tenido motivos plausibles para litigar, sobre lo cual hará declaración expresa en la resolución.

Lo dispuesto en este artículo se entiende sin perjuicio de lo establecido en otras disposiciones de este Código.

**Art. 145 (152).** Podrá el tribunal de segunda instancia eximir de las costas causadas en ella a la parte contra quien se dicte la sentencia, sea que mantenga o no las que en primera instancia se hayan impuesto, expresándose en este caso los motivos especiales que autoricen la exención.

**Art. 146 (153).** No podrá condenarse al pago de costas cuando se hayan emitido, por los jueces que concurran al fallo en un tribunal colegiado, uno o más votos favorables a la parte que pierde la cuestión resuelta.

**Art. 147 (154).** Cuando la parte que promueve un incidente dilatorio no obtenga resolución favorable, será precisamente condenada en las costas.


## Título XV. DEL DESISTIMIENTO DE LA DEMANDA

**Art. 148 (155).** Antes de notificada una demanda al demandado, podrá el actor retirarla sin trámite alguno, y se considerará como no presentada. Después de notificada, podrá en cualquier estado del juicio desistirse de ella ante el tribunal que conozca del asunto, y esta petición se someterá a los trámites establecidos para los incidentes.

**Art. 149 (156).** Si se hace oposición al desistimiento o sólo se acepta condicionalmente, resolverá el tribunal si continúa o no el juicio, o la forma en que debe tenerse por desistido al actor.

**Art. 150 (157).** La sentencia que acepte el desistimiento, haya o no habido oposición, extinguirá las acciones a que él se refiera, con relación a las partes litigantes y a todas las personas a quienes habría afectado la sentencia del juicio a que se pone fin.

**Art. 151 (158).** El desistimiento de las peticiones que se formulen por vía de reconvención se entenderá aceptado, sin declaración expresa, por el hecho de proponerse; salvo que la parte contraria deduzca oposición dentro del tercero día después de notificada. En este caso se tramitará la oposición como incidente y podrá su resolución reservarse para la sentencia definitiva.


## Título XVI. DEL ABANDONO DEL PROCEDIMIENTO

**Artículo 152.-** El procedimiento se entiende abandonado cuando todas las partes que figuran en el juicio han cesado en su prosecución durante seis meses, contados desde la fecha de la última resolución recaída en alguna gestión útil para dar curso progresivo a los autos.

**Artículo 153.-** El abandono podrá hacerse valer sólo por el demandado, durante todo el juicio y hasta que se haya dictado sentencia ejecutoriada en la causa.

En los procedimientos ejecutivos el ejecutado podrá, además, solicitar el abandono del procedimiento, después de ejecutoriada la sentencia definitiva o en el caso del artículo 472. En estos casos, el plazo para declarar el abandono del procedimiento será de tres años contados desde la fecha de la última gestión útil, hecha en el procedimiento de apremio, destinado a obtener el cumplimiento forzado de la obligación, luego de ejecutoriada la sentencia definitiva o vencido el plazo para oponer excepciones, en su caso.  En el evento que la última diligencia útil sea de fecha anterior, el plazo se contará desde la fecha en que quedó ejecutoriada la sentencia definitiva o venció el plazo para oponer excepciones.  En estos casos, si se declara el abandono del procedimiento sin que medie oposición del ejecutante, éste no será condenado en costas.

**Art. 154 (161).** Podrá alegarse el abandono por vía de acción o de excepción, y se tramitará como incidente.

**Art. 155 (162).** Si, renovado el procedimiento, hace el demandado cualquiera gestión que no tenga por objeto alegar su abandono, se considerará renunciado este derecho.

**Art. 156 (163).** No se entenderán extinguidas por el abandono las acciones o excepciones de las partes; pero éstas perderán el derecho de continuar el procedimiento abandonado y de hacerlo valer en un nuevo juicio.

Subsistirán, sin embargo, con todo su valor los actos y contratos de que resulten derechos definitivamente constituidos.

**Art. 157 (164).** No podrá alegarse el abandono del procedimiento en los procedimientos concursales de liquidación, ni en los de división o liquidación de herencias, sociedades o comunidades.


## Título XVII. DE LAS RESOLUCIONES JUDICIALES

**Art. 158 (165).** Las **resoluciones judiciales** se denominarán sentencias definitivas, sentencias interlocutorias, autos y decretos.

Es **sentencia definitiva** la que pone fin a la instancia, resolviendo la cuestión o asunto que ha sido objeto del juicio.

Es **sentencia interlocutoria** la que falla un incidente del juicio, estableciendo derechos permanentes a favor de las partes, o resuelve sobre algún trámite que debe servir de base en el pronunciamiento de una sentencia definitiva o interlocutoria.

Se llama **auto** la resolución que recae en un incidente no comprendido en el inciso anterior.
 
Se llama **decreto, providencia o proveído** el que, sin fallar sobre incidentes o sobre trámites que sirvan de base para el pronunciamiento de una sentencia, tiene sólo por objeto determinar o arreglar la substanciación del proceso.

**Artículo 159.-** Los tribunales, sólo dentro del plazo para dictar sentencia, podrán dictar de oficio medidas para mejor resolver.  Las que se dicten fuera de este plazo se tendrán por no decretadas. Sin perjuicio de lo establecido en el inciso primero del artículo 431, podrán dictar alguna o algunas de las siguientes medidas:

1a. La agregación de cualquier documento que estimen necesario para esclarecer el derecho de los litigantes;

2a. La confesión judicial de cualquiera de las partes sobre hechos que consideren de influencia en la cuestión y que no resulten probados;

3a. La inspección personal del objeto de la cuestión;

4a. El informe de peritos;

5a. La comparecencia de testigos que hayan declarado en el juicio, para que aclaren o expliquen sus dichos obscuros o contradictorios; y

6a. La presentación de cualesquiera otros autos que tengan relación con el pleito. Esta medida se cumplirá de conformidad a lo establecido en el inciso 3° del artículo 37.

En este último caso y siempre que se hubiese remitido el expediente original, éste quedará en poder del tribunal que decrete esta medida sólo por el tiempo estrictamente necesario para su examen, no pudiendo exceder de ocho días este término si se trata de autos pendientes.

La resolución que se dicte deberá ser notificada por el estado diario a las partes y se aplicará el artículo 433, salvo en lo estrictamente relacionado con dichas medidas. Las medidas decretadas deberán cumplirse dentro del plazo de veinte días, contados desde la fecha de la notificación de la resolución que las decrete. Vencido este plazo, las medidas no no cumplidas se tendrán por no decretadas y el tribunal procederá a dictar sentencia, sin más trámite.

Si en la práctica de alguna de estas medidas aparece de manifiesto la necesidad de esclarecer nuevos hechos indispensables para dictar sentencia, podrá el tribunal abrir un término especial de prueba, no superior a ocho días, que será improrrogable y limitado a los puntos que el mismo tribunal designe. En este evento, se aplicará lo establecido en el inciso segundo del artículo 90. Vencido el término de prueba, el tribunal dictará sentencia sin más trámite.

Las providencias que se decreten en conformidad al presente artículo serán inapelables, salvo las que dicte un tribunal de primera instancia disponiendo informe de peritos o abriendo el término especial de prueba que establece el inciso precedente. En estos casos procederá la apelación en el solo efecto devolutivo.

**Art. 160 (167).** Las sentencias se pronunciarán conforme al mérito del proceso, y no podrán extenderse a puntos que no hayan sido expresamente sometidos a juicio por las partes, salvo en cuanto las leyes manden o permitan a los tribunales proceder de oficio.

**Art. 161 (168).** En los tribunales unipersonales el juez examinará por sí mismo los autos para dictar resolución.

Los tribunales colegiados tomarán conocimiento del proceso por medio del relator o del secretario, sin perjuicio del examen que los miembros del tribunal crean necesario hacer por sí mismos.

**Art. 162 (169).** Las causas se fallarán en los tribunales unipersonales tan pronto como estén en estado y por el orden de su conclusión. El mismo orden se observará para designar las causas en los tribunales colegiados para su vista y decisión.

Exceptúanse las cuestiones sobre deserción de recursos, depósito de personas, alimentos provisionales, competencia, acumulaciones, recusaciones, desahucio, juicios sumarios y ejecutivos, denegación de justicia o de prueba y demás negocios que por la ley, o por acuerdo del tribunal fundado en circunstancias calificadas, deban tener preferencia, las cuales se antepondrán a los otros asuntos desde que estén en estado.

La sentencia definitiva en el juicio ordinario deberá pronunciarse dentro del término de sesenta días, contados desde que la causa quede en estado de sentencia.

Si el juez no dicta sentencia dentro de este plazo, será amonestado por la Corte de Apelaciones respectiva, y si a pesar de esta amonestación no expide el fallo dentro del nuevo plazo que ella le designe, incurrirá en la pena de suspensión de su empleo por el término de treinta días, que será decretada por la misma Corte.

El tribunal dejará constancia en el estado diario electrónico a que se refiere el artículo 50 y en la carpeta electrónica, del hecho de haberse dictado sentencia definitiva, la que será notificada en la forma correspondiente.

**Art. 163 (170).** En los tribunales colegiados se formará el día último hábil de cada semana una tabla de los asuntos que verá el tribunal en la semana siguiente, con expresión del nombre de las partes, en la forma en que aparezca en la carátula del respectivo expediente, del día en que cada uno deba tratarse y del número de orden que le corresponda.

Esta tabla se fijará en lugar visible, y antes de que comience a tratar cada negocio, lo anunciará el tribunal, haciendo colocar al efecto en lugar conveniente el respectivo número de orden, el cual se mantendrá fijo hasta que se pase a otro asunto.

**Art. 164 (171).** Las causas se verán en el día señalado. Si concluida la hora de audiencia, queda pendiente alguna y no se acuerda prorrogar el acto, se continuará en los días hábiles inmediatos hasta su terminación, sin necesidad de ponerla nuevamente en tabla.

**Artículo 165.-** Sólo podrá suspenderse en el día designado al efecto la vista de una causa, o retardarse dentro del mismo día:

1°. Por impedirlo el examen de las causas colocadas en lugar preferente, o la continuación de la vista de otro pleito pendiente del día anterior;

2°. Por falta de miembros del tribunal en número suficiente para pronunciar sentencia;

3°. Por muerte del abogado patrocinante, del procurador o del litigante que gestione por sí en el pleito.

En estos casos, la vista de la causa se suspenderá por quince días contados desde la notificación al patrocinado o mandante de la muerte del abogado o del procurador, o desde la muerte del litigante que obraba por sí mismo, en su caso;
  
4°. Por muerte del cónyuge o conviviente civil o de alguno de los descendientes o ascendientes del abogado defensor, ocurrida dentro de los ocho días anteriores al designado para la vista;

5°. Por solicitarlo alguna de las partes o pedirlo de común acuerdo los procuradores o los abogados de ellas.

Cada parte podrá hacer uso de este derecho por una sola vez. En todo caso, sólo podrá ejercitarse este derecho hasta por dos veces, cualquiera que sea el número de partes litigantes, obren o no por una sola cuerda. La suspensión de común acuerdo procederá por una sola vez.

La sola presentación del escrito extingue el derecho a la suspensión aun si la causa no se ve por cualquier otro motivo. Este escrito pagará en la Corte Suprema un impuesto especial de media unidad tributaria mensual y en las Cortes de Apelaciones, de un cuarto de unidad tributaria mensual. Este pago se hará electrónicamente a través de un sistema informático dispuesto al efecto y se asociará a la causa respectiva mediante el comprobante de pago o código de validación o, en caso que lo anterior no fuere posible por cualquier motivo, a través de estampillas de impuesto fiscal que se pegarán en el escrito respectivo que se presentará materialmente.

Para los efectos del artículo 198 del Código Orgánico de Tribunales, el pago de impuestos para la recusación de abogados integrantes se hará de la misma forma dispuesta en el párrafo anterior.

El derecho a suspender no procederá respecto del amparo;

6°. Por tener alguno de los abogados otra vista o comparecencia a que asistir en el mismo día ante otro tribunal.

El presidente respectivo podrá conceder la suspensión por una sola vez o simplemente retardar la vista, atendidas las circunstancias. En caso que un abogado tenga dos o más vistas en el mismo día y ante el mismo tribunal, en salas distintas, preferirá el amparo, luego la protección y en seguida la causa que se anuncie primero, retardándose o suspendiéndose las demás, según las circunstancias; y

7°. Por ordenarlo así el tribunal, por resolución fundada, al disponer la práctica de algún trámite que sea estrictamente indispensable cumplir en forma previa a la vista de la causa. La orden de traer algún expediente o documento a la vista, no suspenderá la vista de la causa y la resolución se cumplirá terminada ésta.

Las causas que salgan de tabla por cualquier motivo volverán a ella al lugar que tenían.

Los errores, cambios de letras o alteraciones no substanciales de los nombres o apellidos de las partes no impiden la vista de la causa.

Los relatores, en cada tabla, deberán dejar constancia de las suspensiones ejercidas de conformidad a la causal del N° 5°. y de la circunstancia de haberse agotado o no el ejercicio de tal derecho.

**Art. 166 (173).** Cuando haya de integrarse una sala con miembros que no pertenezcan a su personal ordinario, antes de comenzar la vista, se pondrá por conducto del relator o secretario en conocimiento de las partes o de sus abogados el nombre de los integrantes, y se procederá a ver la causa inmediatamente, a menos que en el acto se reclame, de palabra o por escrito, implicancia o recusación contra alguno de ellos.

Formulada la reclamación, se suspenderá la vista y deberá formalizarse aquélla por escrito de tercero día, imponiéndose en caso contrario a la parte reclamante, por este solo hecho, una multa que no baje de medio sueldo vital ni exceda de dos sueldos vitales.

**Art. 167 (174).** Cuando la existencia de un delito haya de ser fundamento preciso de una sentencia civil o tenga en ella influencia notoria, podrán los tribunales suspender el pronunciamiento de ésta hasta la terminación del proceso criminal, si en éste se ha deducido acusación o formulado requerimiento, según el caso.

Esta suspensión podrá decretarse en cualquier estado del juicio, una vez que se haga constar la circunstancia mencionada en el inciso precedente.

Si en el caso de los dos incisos anteriores se forma incidente, se tramitará en pieza separada sin paralizar la marcha del juicio.

Con todo, si en el mismo juicio se ventilan otras cuestiones que puedan tramitarse y resolverse sin aguardar el fallo del proceso criminal, continuará respecto de ellas el procedimiento sin interrupción.

**Art. 168 (176).** En los tribunales colegiados los decretos podrán dictarse por uno solo de sus miembros. Los autos, las sentencias interlocutorias y las definitivas, exigirán la concurrencia de tres de sus miembros a lo menos.

**Art. 169 (192).** Toda resolución, de cualquiera clase que sea, deberá expresar en letras la fecha y lugar en que se expida, y llevará al pie la firma electrónica avanzada del juez o jueces que la dicten o intervengan en el acuerdo.

Cuando después de acordada una resolución y siendo varios los jueces se imposibilite alguno de ellos para firmarla, bastará que se exprese esta circunstancia en el mismo fallo.

**Art. 170 (193).** Las sentencias definitivas de primera o de única instancia y las de segunda que modifiquen o revoquen en su parte dispositiva las de otros tribunales, contendrán:

1°. La designación precisa de las partes litigantes, su domicilio y profesión u oficio;

2°. La enunciación breve de las peticiones o acciones deducidas por el demandante y de sus fundamentos;

3°. Igual enunciación de las excepciones o defensas alegadas por el demandado;

4°. Las consideraciones de hecho o de derecho que sirven de fundamento a la sentencia;

5°. La enunciación de las leyes, y en su defecto de los principios de equidad, con arreglo a los cuales se pronuncia el fallo; y

6°. La decisión del asunto controvertido. Esta decisión deberá comprender todas las acciones y excepciones que se hayan hecho valer en el juicio; pero podrá omitirse la resolución de aquellas que sean incompatibles con las aceptadas.

En igual forma deberán dictarse las sentencias definitivas de segunda instancia que confirmen sin modificación las de primera cuando éstas no reúnen todos o algunos de los requisitos indicados en la enunciación precedente.

Si la sentencia de primera instancia reúne estos requisitos, la de segunda que modifique o revoque no necesita consignar la exposición de las circunstancias mencionadas en los números 1°, 2° y 3° del presente artículo y bastará referirse a ella.

**Art. 171 (194).** En las sentencias interlocutorias y en los autos se expresarán, en cuanto la naturaleza del negocio lo permita, a más de la decisión del asunto controvertido, las circunstancias mencionadas en los números 4° y 5° del artículo precedente.

**Art. 172 (195).** Cuando en un mismo juicio se ventilen dos o más cuestiones que puedan ser resueltas separada o parcialmente, sin que ello ofrezca dificultad para la marcha del proceso, y alguna o algunas de dichas cuestiones o parte de ellas, lleguen al estado de sentencia antes de que termine el procedimiento en las restantes, podrá el tribunal fallar desde luego las primeras.

En este caso se formará cuaderno electrónico separado con las piezas necesarias para dictar fallo y ejecutarlo.

**Art. 173 (196).** Cuando una de las partes haya de ser condenada a la devolución de frutos o a la indemnización de perjuicios, y se ha litigado sobre su especie y monto, la sentencia determinará la cantidad líquida que por esta causa deba abonarse, o declarará sin lugar el pago, si no resultan probados la especie y el monto de lo que se cobra, o, por lo menos, las bases que deban servir para su liquidación al ejecutarse la sentencia.

En el caso de que no se haya litigado sobre la especie y el monto de los frutos o perjuicios, el tribunal reservará a las partes el derecho de discutir esta cuestión en la ejecución del fallo o en otro juicio diverso.

**Art. 174 (197).** Se entenderá firme o ejecutoriada una resolución desde que se haya notificado a las partes, si no procede recurso alguno en contra de ella; y, en caso contrario, desde que se notifique el decreto que la mande cumplir, una vez que terminen los recursos deducidos, o desde que transcurran todos los plazos que la ley concede para la interposición de dichos recursos, sin que se hayan hecho valer por las partes. En este último caso, tratándose de sentencias definitivas, certificará el hecho el secretario del tribunal a continuación del fallo, el cual se considerará firme desde este momento, sin más trámites.

**Art. 175 (198).** Las sentencias definitivas o interlocutorias firmes producen la acción o la excepción de cosa juzgada.

**Art. 176 (199).** Corresponde la acción de cosa juzgada a aquel a cuyo favor se ha declarado un derecho en el juicio, para el cumplimiento de lo resuelto o para la ejecución del fallo en la forma prevenida por el Título XIX de este Libro.

**Art. 177 (200).** La excepción de cosa juzgada puede alegarse por el litigante que haya obtenido en el juicio y por todos aquellos a quienes según la ley aprovecha el fallo, siempre que entre la nueva demanda y la anteriormente resuelta haya:

 1° Identidad legal de personas;
 
 2° Identidad de la cosa pedida; y
 
 3° Identidad de la causa de pedir.

Se entiende por causa de pedir el fundamento inmediato del derecho deducido en juicio.

**Art. 178 (201).** En los juicios civiles podrán hacerse valer las sentencias dictadas en un proceso criminal siempre que condenen al procesado

**Art. 179 (202).** Las sentencias que absuelvan de la acusación o que ordenen el sobreseimiento definitivo, sólo producirán cosa juzgada en materia civil, cuando se funden en alguna de las circunstancias siguientes: 1ª La no existencia del delito o cuasidelito que ha sido materia del proceso. No se entenderán comprendidos en este número los casos en que la absolución o sobreseimiento provengan de la existencia de circunstancias que eximan de responsabilidad criminal; 2ª No existir relación alguna entre el hecho que se persigue y la persona acusada, sin perjuicio de la responsabilidad civil que pueda afectarle por actos de terceros, o por daños que resulten de accidentes, en conformidad a lo establecido en el Título XXXV, Libro IV, del Código Civil; y 3ª No existir en autos indicio alguno en contra del acusado, no pudiendo en tal caso alegarse la cosa juzgada sino respecto de las personas que hayan intervenido en el proceso criminal. Las sentencias absolutorias o de sobreseimiento en materia criminal relativas a los tutores, curadores, albaceas, síndicos, depositarios, tesoreros y demás personas que hayan recibido valores u objetos muebles por un título de que nazca obligación de devolverlos, no producirán en ningún caso cosa juzgada en materia civil.

**Art. 180 (203).** Siempre que la sentencia criminal produzca cosa juzgada en juicio civil, no será lícito en éste tomar en consideración pruebas o alegaciones incompatibles con lo resuelto en dicha sentencia o con los hechos que le sirvan de necesario fundamento.

**Art. 181 (204).** Los autos y decretos firmes se ejecutarán y mantendrán desde que adquieran este carácter sin perjuicio de la facultad del tribunal que los haya pronunciado para modificarlos o dejarlos sin efecto, si se hacen valer nuevos antecedentes que así lo exijan.

Aún sin estos antecedentes, podrá pedirse, ante el tribunal que dictó el auto o decreto su reposición, dentro de cinco días fatales después de notificado. El tribunal se pronunciará de plano y la resolución que niegue lugar a esta solicitud será inapelable; sin perjuicio de la apelación del fallo reclamado, si es procedente el recurso.

**Art. 182 (205).** Notificada una sentencia definitiva o interlocutoria a alguna de las partes, no podrá el tribunal que la dictó alterarla o modificarla en manera alguna. Podrá, sin embargo, a solicitud de parte, aclarar los puntos obscuros o dudosos, salvar las omisiones y rectificar los errores de copia, de referencia o de cálculos numéricos que aparezcan de manifiesto en la misma sentencia.

Lo dispuesto en este artículo no obsta para que el rebelde haga uso del derecho que le confiere el artículo 80.

**Art. 183 (206).** Hecha la reclamación, podrá el tribunal pronunciarse sobre ella sin más trámite o después de oír a la otra parte; y mientras tanto suspenderá o no los trámites del juicio o la ejecución de la sentencia, según la naturaleza de la reclamación.

**Art. 184 (207).** Los tribunales, en el caso del artículo 182, podrán también de oficio rectificar, dentro de los cinco días siguientes a la primera notificación de la sentencia, los errores indicados en dicho artículo.

**Art. 185 (208).** Las aclaraciones, agregaciones o rectificaciones mencionadas en los tres artículos precedentes, podrán hacerse no obstante la interposición de recursos sobre la sentencia a que aquellas se refieren.


## Título XVIII. DE LA APELACION

**Art. 186 (209).** El recurso de apelación tiene por objeto obtener del tribunal superior respectivo que enmiende, con arreglo a derecho, la resolución del inferior.

**Art. 187 (210).** Son apelables todas las sentencias definitivas y las interlocutorias de primera instancia, salvo en los casos en que la ley deniegue expresamente este recurso.

**Art. 188 (211).** Los autos y decretos no son apelables cuando ordenen trámites necesarios para la substanciación regular del juicio; pero son apelables cuando alteran dicha substanciación o recaen sobre trámites que no están expresamente ordenados por la ley. Esta apelación sólo podrá interponerse con el carácter de subsidiaria de la solicitud de reposición y para el caso que ésta no sea acogida.

**Artículo 189.-** La apelación deberá interponerse en el término fatal de cinco días, contados desde la notificación de la parte que entabla el recurso, deberá contener los fundamentos de hecho y de derecho en que se apoya y las peticiones concretas que se formulan.

Este plazo se aumentará a diez días tratándose de sentencias definitivas.

En aquellos casos en que la apelación se interponga con el carácter de subsidiaria de la solicitud de reposición, no será necesario fundamentarla ni formular peticiones concretas, siempre que el recurso de reposición cumpla con ambas exigencias.  En los procedimientos o actuaciones para las cuales la ley establezca la oralidad, se podrá apelar en forma verbal siempre que someramente se señalen los fundamentos de hecho y de derecho del recurso y se formulen peticiones concretas, de todo lo cual deberá dejarse constancia en el acta respectiva.

La normas de los incisos anteriores no se aplicarán en aquellos procedimientos en que las partes, sin tener la calidad de letrados, litiguen personalmente y la ley faculte la interposición verbal del recurso de apelación.  En estos casos el plazo para apelar será de cinco días fatales, salvo disposición especial en contrario.

**Art. 190 (213).** El término para apelar no se suspende por la solicitud de reposición a que se refiere el artículo 181.

Tampoco se suspende por la solicitud de aclaración, agregación o rectificación de la sentencia definitiva o interlocutoria. El fallo que resuelva acerca de dicha solicitud o en que de oficio se hagan rectificaciones conforme al artículo 184, será apelable en todos los casos en que lo sería la sentencia a que se refiera, con tal que la cuantía de la cosa declarada, agregada o rectificada admita el recurso.

**Art. 191 (214).** Cuando la apelación comprenda los efectos suspensivo y devolutivo a la vez, se suspenderá la jurisdicción del tribunal inferior para seguir conociendo de la causa.

Podrá, sin embargo, entender en todos los asuntos en que por disposición expresa de la ley conserve jurisdicción, especialmente en las gestiones a que dé origen la interposición del recurso hasta que se eleven los autos al superior, y en las que se hagan para declarar desierta o prescrita la apelación antes de la remisión del expediente.

**Art. 192 (215).** Cuando la apelación proceda sólo en el efecto devolutivo, seguirá el tribunal inferior conociendo de la causa hasta su terminación, inclusa la ejecución de la sentencia definitiva.

No obstante, el tribunal de alzada a petición del apelante y mediante resolución fundada, podrá dictar orden de no innovar. La orden de no innovar suspende los efectos de la resolución recurrida o paraliza su cumplimiento, según sea el caso. El tribunal podrá restringir estos efectos por resolución fundada. Los fundamentos de las resoluciones que se dicten de conformidad a este inciso no constituyen causal de inhabilidad.

Las peticiones de orden de no innovar serán distribuidas por el Presidente de la Corte, mediante sorteo, entre las salas en que esté dividida y se resolverán en cuenta. Decretada una orden de no innovar, quedará radicado el conocimiento de la apelación respectiva en la sala que la concedió y el recurso gozará de preferencia para figurar en tabla y en su vista y fallo.

**Art. 193 (216).** Cuando se otorga simplemente apelación, sin limitar sus efectos, se entenderá que comprende el devolutivo y el suspensivo.

**Art. 194 (217).** Sin perjuicio de las excepciones expresamente establecidas en la ley, se concederá apelación sólo en el efecto devolutivo:

1°. De las resoluciones dictadas contra el demandado en los juicios ejecutivos y sumarios;

2°. De los autos, decretos y sentencias interlocutorias;

3°. De las resoluciones pronunciadas en el incidente sobre ejecución de una sentencia firme, definitiva o interlocutoria;

4°. De las resoluciones que ordenen alzar medidas precautorias; y

5°. De todas las demás resoluciones que por disposición de la ley sólo admitan apelación en el efecto devolutivo.

**Art. 195 (218).** Fuera de los casos determinados en el artículo precedente, la apelación deberá otorgarse en ambos efectos.

**Art. 196 (219).** Si el tribunal inferior otorga apelación en el efecto devolutivo, debiendo concederla también en el suspensivo, la parte agraviada, dentro del plazo de cinco días contado desde la fecha de la certificación a que se refiere el artículo 200, podrá pedir al superior que desde luego declare admitida la apelación en ambos efectos; sin perjuicio de que pueda solicitarse igual declaración, por vía de reposición, del tribunal que concedió el recurso.

Lo mismo se observará cuando se conceda apelación en ambos efectos, debiendo otorgarse únicamente en el devolutivo, y cuando la apelación concedida sea improcedente. En este último caso podrá también de oficio el tribunal superior declarar sin lugar el recurso.

Las declaraciones que haga el superior en conformidad a los dos incisos anteriores, se comunicarán al inferior para que se abstenga, o siga conociendo del negocio, según los casos.

**Artículo 197.-** La resolución que conceda una apelación se entenderá notificada a las partes conforme al artículo 50. El tribunal remitirá electrónicamente al tribunal de alzada copia fiel de la resolución apelada, del recurso y de todos los antecedentes que fueren pertinentes para un acabado pronunciamiento sobre éste.

Recibidos los antecedentes referidos en el inciso anterior, la Corte de Apelaciones procederá a la asignación de un número de ingreso. Acto seguido, formará un cuaderno electrónico separado para el conocimiento y fallo del recurso cuando él haya sido concedido en el solo efecto devolutivo. En el caso que la apelación fuere concedida en ambos efectos, el tribunal de alzada continuará la tramitación en la carpeta electrónica, la que estará disponible en el sistema de tramitación electrónica del tribunal de alzada correspondiente.

**Art. 198 (221).** Derogado.

**Art. 199 (222).** La apelación de toda resolución que no sea sentencia definitiva se verá en cuenta, a menos que cualquiera de las partes, dentro del plazo de cinco días contado desde la certificación a que se refiere el artículo 200, solicite alegatos.

Vencido este plazo, el tribunal de alzada ordenará traer los autos en relación, si se hubieren solicitado oportunamente alegatos. De lo contrario, el Presidente de la Corte ordenará dar cuenta y procederá a distribuir, mediante sorteo, la causa entre las distintas salas en que funcione el tribunal.

Las Cortes deberán establecer horas de funcionamiento adicional para el conocimiento y fallo de las apelaciones que se vean en cuenta.

**Artículo 200.-** El tribunal de alzada deberá certificar en la carpeta electrónica la recepción de la comunicación a que se refiere el artículo 197 y su fecha.

**Artículo 201.-** Si la apelación se ha interpuesto fuera de plazo o respecto de resolución inapelable o no es fundada o no contiene peticiones concretas, el tribunal correspondiente deberá declararla inadmisible de oficio. La parte apelada, en todo caso, podrá solicitar la declaración pertinente, verbalmente o por escrito.

Del fallo que, en estas materias, dicte el tribunal de alzada podrá pedirse reposición dentro de tercero día.

**Art. 202 (225).** Derogado.

**Art. 203 (226).** Si el tribunal inferior deniega un recurso de apelación que ha debido concederse, la parte agraviada podrá ocurrir al superior respectivo, dentro del plazo de cinco días contado desde la notificación de la negativa, para que declare admisible dicho recurso.

**Art. 204 (227).** El tribunal superior pedirá al inferior informe sobre el asunto en que haya recaído la negativa, y con el mérito de lo informado resolverá si es o no admisible el recurso.

Podrá el tribunal superior ordenar al inferior poner a su disposición la carpeta electrónica correspondiente, siempre que, a su juicio, ello sea necesario para dictar una resolución acertada.

Podrá, asimismo, ordenar que no se innove cuando haya antecedentes que justifiquen esta medida.

**Art. 205 (228).** Si el tribunal superior declara inadmisible el recurso, lo comunicará al inferior.

Si el recurso es declarado admisible, el tribunal superior le dará al proceso la tramitación que corresponda y lo comunicará al inferior según proceda.

**Art. 206 (229).** En el caso del 2° inciso del artículo precedente, quedarán sin efecto las gestiones posteriores a la negativa del recurso y que sean una consecuencia inmediata y directa del fallo apelado.

**Artículo 207.-** En segunda instancia, salvo lo dispuesto en el inciso final del artículo 310 y en los artículos 348 y 385, no se admitirá prueba alguna.

No obstante y sin perjuicio de las demás facultades concedidas por el artículo 159, el tribunal podrá, como medida para mejor resolver, disponer la recepción de prueba testimonial sobre hechos que no figuren en la prueba rendida en autos, siempre que la testimonial no se haya podido rendir en primera instancia y que tales hechos sean considerados por el tribunal como estrictamente necesarios para la acertada resolución del juicio. En este caso, el tribunal deberá señalar determinadamente los hechos sobre que deba recaer y abrir un término especial de prueba por el número de días que fije prudencialmente y que no podrá exceder de ocho días. La lista de testigos deberá presentarse dentro de segundo día de notificada por el estado la resolución respectiva.

**Art. 208 (231).** Podrá el tribunal de alzada fallar las cuestiones ventiladas en primera instancia y sobre las cuales no se haya pronunciado la sentencia apelada por ser incompatibles con lo resuelto en ella, sin que se requiera nuevo pronunciamiento del tribunal inferior.

**Art. 209 (232).** Del mismo modo podrá el tribunal de segunda instancia, previa audiencia del fiscal judicial, hacer de oficio en su sentencia las declaraciones que por la ley son obligatorias a los jueces, aun cuando el fallo apelado no las contenga.

Si en virtud de estas declaraciones se establece la incompetencia del tribunal para entender en la cuestión sometida a su conocimiento, podrá apelarse de la resolución para ante el tribunal superior que corresponda, salvo que la declaración sea hecha por la Corte Suprema.

**Art. 210 (233).** Las resoluciones que recaigan en los incidentes que se promuevan en segunda instancia, se dictarán sólo por el tribunal de alzada y no serán apelables.

**Art. 211 (234).** Derogado.

**Art. 212 (235).** Derogado.

**Art. 213 (438).** Elevado un proceso en apelación, el tribunal superior examinará en cuenta si el recurso es admisible y si ha sido interpuesto dentro del término legal.

Si encuentra mérito el tribunal para considerar inadmisible o extemporáneo el recurso, lo declarará sin lugar desde luego o mandará traer los autos en relación sobre este punto.

****Artículo 214.-** Si el tribunal superior declara no haber lugar al recurso, pondrá el proceso a disposición del inferior para el cumplimiento del fallo. En caso contrario mandará que se traigan los autos en relación.


**Art. 215 (440).** Derogado.

**Art. 216 (441).** Puede el apelado adherirse a la apelación en la forma y oportunidad que se expresa en el artículo siguiente.

Adherirse a la apelación es pedir la reforma de la sentencia apelada en la parte en que la estime gravosa el apelado.

**Artículo 217.-** La adhesión a la apelación puede efectuarse en segunda instancia dentro del plazo de cinco días desde la fecha de la certificación a la que se refiere el artículo 200. El escrito de adhesión a la apelación deberá cumplir con los requisitos que establece el artículo 189. Se aplicará a la adhesión a la apelación lo dispuesto en el artículo 201.

No será, sin embargo, admisible desde el momento en que el apelante haya presentado escrito para desistirse de la apelación.

La hora de presentación de las solicitudes de adhesión y de desistimiento se registrará por el sistema de tramitación electrónica del Poder Judicial, o por el tribunal a través del timbre disponible ante el buzón dispuesto al efecto o mediante la anotación del correspondiente ministro de fe en los casos excepcionales en que se permite la presentación de los escritos en soporte papel.

**Art. 218 (443).** Derogado.

**Art. 219 (444).** Derogado.

**Art. 220 (445).** Las cuestiones accesorias que se susciten en el curso de la apelación, se fallarán de plano por el tribunal, o se tramitarán como incidentes. En este último caso, podrá también el tribunal fallarlas en cuenta u ordenar que se traigan en relación los autos para resolver.

**Art. 221 (446).** La notificación de las resoluciones que se dicten por el tribunal de alzada se practicará en la forma que establece el artículo 50, con excepción de la primera, que debe ser personal.

Podrá, sin embargo, el tribunal ordenar que se haga por otro de los medios establecidos en la ley, cuando lo estime conveniente.

**Art. 222 (447).** En cumplimiento de las obligaciones impuestas por el artículo 373 del Código Orgánico de Tribunales, los relatores darán cuenta de los vicios y omisiones que hayan notado en las causas del día a fin de que el tribunal resuelva si ha de llenarse previamente algún trámite.

Las causas que se ordene tramitar, las suspendidas y las que por cualquier motivo no hayan de verse, serán anunciadas en la tabla antes de comenzar la relación de las demás. Asimismo, en esa oportunidad deberán señalarse aquellas causas que no se verán durante la audiencia, por falta de tiempo. La audiencia se prorrogará, si fuere necesario, hasta ver la última de las causas que resten en la tabla.

**Artículo 223.-** La vista de la causa se iniciará con la relación, la que se efectuará en presencia de los abogados de las partes que hayan asistido y se hubieren anunciado para alegar. No se permitirá el ingreso a la sala de los abogados una vez comenzada la relación. Los Ministros podrán, durante la relación, formular preguntas o hacer observaciones al relator, las que en caso alguno podrán ser consideradas como causales de inhabilidad.

Concluida la relación, se procederá a escuchar, en audiencia pública, los alegatos de los abogados que se hubieren anunciado. Alegará primero el abogado del apelante y en seguida el del apelado. Si son varios los apelantes, hablarán los abogados en el orden en que se hayan interpuesto las apelaciones. Si son varios los apelados, los abogados intervendrán por el orden alfabético de aquéllos.

Los abogados tendrán derecho a rectificar los errores de hecho que observaren en el alegato de la contraria, al término de éste, sin que les sea permitido replicar en lo concerniente a puntos de derecho.

La duración de los alegatos de cada abogado se limitará a media hora. El tribunal, a petición del interesado, podrá prorrogar el plazo por el tiempo que estime conveniente.

Durante los alegatos, el Presidente de la sala podrá invitar a los abogados a que extiendan sus consideraciones a cualquier punto de hecho o de derecho comprendido en el proceso, pero esta invitación no obstará a la libertad del defensor para el desarrollo de su exposición. Una vez finalizados los alegatos, y antes de levantar la audiencia, podrá también pedirles que precisen determinados puntos de hecho o de derecho que considere importantes.

Al término de la audiencia, los abogados podrán dejar a disposición del tribunal una minuta de sus alegatos.

El relator dará cuenta a la sala de los abogados que hubiesen solicitado alegatos o se hubiesen anunciado para alegar y no concurrieren a la audiencia respectiva para oír la relación ni hacer el alegato. El Presidente de la sala oirá al interesado, y, si encontrare mérito para sancionarlo, le aplicará una multa no inferior a una ni superior a cinco unidades tributarias mensuales, la que se duplicará en caso de reiteración de la falta dentro de un mismo año calendario. El sancionado no podrá alegar ante esa misma Corte mientras no certifique el secretario de ella, en el correspondiente expediente, que se ha pagado la multa impuesta.

**Art. 224 (449).** Si la apelación comprende dos o más puntos independientes entre sí y susceptibles de resolución aislada, podrá el tribunal alterar la regla del artículo precedente haciendo que los abogados aleguen separada y sucesivamente sobre cada punto.

**Art. 225 (450).** En la vista de la causa sólo podrá alegar un abogado por cada parte, y no podrán hacerlo la parte y su abogado.

**Art. 226 (451).** Se prohíbe presentar en la vista de la causa defensas escritas.

Se prohíbe igualmente leer en dicho acto tales defensas.

**Art. 227 (452).** Vista la causa, queda cerrado el debate y el juicio en estado de dictarse resolución.

Si, vista la causa, se decreta para mejor resolver, alguna de las diligencias mencionadas en el artículo 159, no por esto dejarán de intervenir en la decisión del asunto los mismos miembros del tribunal que asistieron a la vista en que se ordenó la diligencia.

**Art. 228 (453).** Los tribunales podrán mandar, a petición de parte, informar en derecho.

**Art. 229 (454).** El término para informar en derecho será el que señale el tribunal y no podrá exceder de sesenta días, salvo acuerdo de las partes.

**Artículo 230.-** Los informes en derecho, con las firmas del abogado y de la parte o de su procurador, y el certificado a que se refiere el número 6º del artículo 372 del Código Orgánico de Tribunales se agregarán a la carpeta electrónica para conocimiento de los ministros.



## Título XIX. DE LA EJECUCION DE LAS RESOLUCIONES

***1. De las resoluciones pronunciadas por tribunales chilenos.***

**Art. 231 (236).** La ejecución de las resoluciones corresponde a los tribunales que las hayan pronunciado en primera o en única instancia. Se procederá a ella una vez que las resoluciones queden ejecutoriadas o causen ejecutoria en conformidad a la ley.

No obstante, los tribunales que conozcan de los recursos de apelación, casación o revisión, ejecutarán los fallos que dicten para la substanciación de dichos recursos. Podrán también decretar el pago de las costas adeudadas a los funcionarios que hayan intervenido en ellos, reservando el de las demás costas para que sea decretado por el tribunal de primera instancia.

**Art. 232 (238).** Siempre que la ejecución de una sentencia definitiva haga necesaria la iniciación de un nuevo juicio, podrá éste deducirse ante el tribunal que menciona el inciso 1° del artículo 231, o ante el que sea competente en conformidad a los principios generales establecidos por la ley, a elección de la parte que haya obtenido en el pleito.

Artículo 233.- Cuando se solicite la ejecución de una sentencia ante el tribunal que la dictó, dentro del plazo de un año contado desde que la ejecución se hizo exigible, si la ley no ha dispuesto otra forma especial de cumplirla, se ordenará su cumplimiento con citación de la persona en contra de quien se pide.

Esta resolución se notificará por cédula al apoderado de la parte. El ministro de fe que practique la notificación deberá enviar la carta certificada que establece el artículo 46 tanto al apoderado como a la parte. A esta última, la carta deberá remitírsele al domicilio en que se le haya notificado la demanda. En caso que el cumplimiento del fallo se pida contra un tercero, éste deberá ser notificado personalmente.

El plazo de un año se contará, en las sentencias que ordenen prestaciones periódicas, desde que se haga exigible cada prestación o la última de las que se cobren.

**Art. 234.** En el caso del artículo anterior la parte vencida sólo podrá oponerse alegando algunas de las siguientes excepciones: pago de la deuda, remisión de la misma, concesión de esperas o prórrogas del plazo, novación, compensación, transacción, la de haber perdido su carácter de ejecutoria, sea absolutamente o con relación a lo dispuesto en el artículo anterior, la sentencia que se trate de cumplir, la del artículo 464 número 15 y la del artículo 534, siempre que ellas, salvo las dos últimas, se funden en antecedentes escritos, pero todas en hechos acaecidos con posterioridad a la sentencia de cuyo cumplimiento se trata. También podrá alegarse la falta de oportunidad en la ejecución. Esta excepción y las del artículo 464 N° 15 y del artículo 534 necesitarán, además, para ser admitidas a tramitación, que aparezcan revestidas de fundamento plausible. La oposición sólo podrá deducirse dentro de la citación a que se refiere el artículo precedente.

El tercero en contra de quien se pida el cumplimiento del fallo podrá deducir, además, la excepción de no empecerle la sentencia y deberá formular su oposición dentro del plazo de diez días.

La oposición se tramitará en forma incidental, pero si las excepciones no reúnen los requisitos exigidos por el inciso 1° se rechazará de plano.

Lo dispuesto en este artículo es sin perjuicio de lo prevenido en el artículo 80.

**Art. 235.** Si no ha habido oposición al cumplimiento de la sentencia solicitado conforme al artículo 233 o ella ha sido desestimada por sentencia de primera o segunda instancia, se procederá a cumplirla, siempre que la ley no haya dispuesto otra forma especial, de acuerdo con las reglas siguientes:

1a. Si la sentencia ordena entregar una especie o cuerpo cierto, sea mueble o inmueble, se llevará a afecto la entrega, haciéndose uso de la fuerza pública si es necesario;

2a. Si la especie o cuerpo cierto mueble no es habido, se procederá a tasarlo con arreglo al Título XII del Libro IV y se observarán en seguida las reglas del número siguiente;

3a. Si la sentencia manda pagar una suma de dinero se ordenará, sin más trámite, hacer pago al acreedor con los fondos retenidos, hecha la liquidación del crédito y de las costas causadas o se dispondrá previamente la realización de los bienes que estén garantizando el resultado de la acción de conformidad al Título V del Libro II.

Si no hay bienes que aseguren el resultado de la acción se procederá a embargar y a enajenar bienes suficientes de la parte vencida de acuerdo con las reglas del procedimiento de apremio, sin necesidad de requerimiento y deberá notificarse por cédula el embargo mismo y la resolución que lo ordena;

4a. Si la sentencia obliga a pagar una cantidad de un género determinado, se procederá de conformidad a las reglas del número anterior; pero si es necesario, se practicará previamente su avaluación por un perito con arreglo al Título XII del Libro IV;

5a. Si la sentencia ordena la ejecución o destrucción de una obra material, la subscripción de un instrumento o la constitución de un derecho real o de una obligación, se procederá de acuerdo con el procedimiento de apremio en las obligaciones de hacer; pero se aplicará lo prescrito en el número 3° de este artículo cuando sea necesario embargar y realizar bienes; y

6a. Si la sentencia ha condenado a la devolución de frutos o a la indemnización de perjuicios y, de conformidad a lo establecido en el inciso segundo del artículo 173, se ha reservado al demandante el derecho de discutir esta cuestión en la ejecución del fallo, el actor deberá formular la demanda respectiva en el mismo escrito en que pida el cumplimiento del fallo. Esta demanda se tramitará como incidente y, de existir oposición al cumplimiento del fallo, ambos incidentes se substanciarán conjuntamente y se resolverán en una misma y única sentencia.

En todo lo que no esté previsto en este artículo se aplicarán las reglas que se establecen en el juicio ejecutivo para el embargo y el procedimiento de apremio; pero la sentencia se cumplirá hasta hacer entero pago a la parte vencedora sin necesidad de fianza de resultas, salvo lo dispuesto en el artículo 774 y en otras disposiciones especiales.

**Art. 236.** Si la sentencia ordena el pago de prestaciones periódicas y el deudor retarda el pago de dos o más, podrá el juez compelerlo a prestar seguridades para el pago, tal como la de convertir las prestaciones en los intereses de un capital que se consigna al efecto, en un banco, Caja de Ahorros y otros establecimientos análogos. Este capital se restituirá al deudor tan pronto como cese la obligación.

Esta petición se tramitará en forma incidental.

**Art. 237.** Las sentencias que ordenen prestaciones de dar, hacer o no hacer, y cuyo cumplimiento se solicite después de vencido el plazo de un año, concedido en el artículo 233, se sujetarán a los trámites del juicio ejecutivo.

Se aplicará también este procedimiento cuando se solicite el cumplimiento del fallo ante otro tribunal distinto del indicado en el artículo 233.

En los juicios a que dé lugar la ejecución de las resoluciones a que se refiere este artículo, no se admitirá ninguna excepción que haya podido oponerse en el juicio anterior.

**Art. 238.** Cuando se trate del cumplimiento de resoluciones no comprendidas en los artículos anteriores, corresponderá al juez de la causa dictar las medidas conducentes a dicho cumplimiento, pudiendo al efecto imponer multas que no excedan de una unidad tributaria mensual o arresto hasta de dos meses, determinados prudencialmente por el tribunal, sin perjuicio de repetir el apremio.

**Art. 239.** Las reclamaciones que el obligado a restituir una cosa raíz o mueble tenga derecho a deducir en razón de prestaciones a que esté obligado el vencedor y que no haya hecho valer en el juicio en que se dictó la sentencia que se trata de cumplir, se tramitarán en forma incidental con audiencia de las partes, sin entorpecer el cumplimiento de la sentencia, salvo las excepciones legales.

**Art. 240.** Cumplida una resolución, el tribunal tendrá facultad para decretar las medidas tendientes a dejar sin efecto todo lo que se haga en contravención a lo ejecutado.

El que quebrante lo ordenado cumplir será sancionado con reclusión menor en su grado medio a máximo.

**Art. 241.** Las apelaciones que se deduzcan contra las resoluciones que se dicten en conformidad a lo dispuesto en los artículos precedentes de este Título, se concederán sólo en el efecto devolutivo. Tratándose de juicios de hacienda, estas apelaciones se colocarán de inmediato en tabla y gozarán de preferencia para su vista y fallo.


***2. De las resoluciones pronunciadas por tribunales extranjeros***

**Art. 242 (239).** Las resoluciones pronunciadas en país extranjero tendrán en Chile la fuerza que les concedan los tratados respectivos; y para su ejecución se seguirán los procedimientos que establezca la ley chilena, en cuanto no aparezcan modificados por dichos tratados.

**Art. 243 (240).** Si no existen tratados relativos a esta materia con la nación de que procedan las resoluciones, se les dará la misma fuerza que en ella se dé a los fallos pronunciados en Chile.

**Art. 244 (241).** Si la resolución procede de un país en que no se da cumplimiento a los fallos de los tribunales chilenos, no tendrá fuerza en Chile.

**Art. 245 (242).** En los casos en que no pueda aplicarse ninguno de los tres artículos precedentes, las resoluciones de tribunales extranjeros tendrán en Chile la misma fuerza que si se hubieran dictado por tribunales chilenos, con tal que reúnan las circunstancias siguientes:

1a. Que no contengan nada contrario a las leyes de la República. Pero no se tomarán en consideración las leyes de procedimiento a que haya debido sujetarse en Chile la substanciación del juicio;

2a. Que tampoco se opongan a la jurisdicción nacional;

3a. Que la parte en contra de la cual se invoca la sentencia haya sido debidamente notificada de la acción. Con todo, podrá ella probar que, por otros motivos, estuvo impedida de hacer valer sus medios de defensa.

4a. Que estén ejecutoriadas en conformidad a las leyes del país en que hayan sido pronunciadas.

**Art. 246 (243).** Las reglas de los artículos precedentes son aplicables a las resoluciones expedidas por jueces árbitros. En este caso se hará constar su autenticidad y eficacia por el visto-bueno u otro signo de aprobación emanado de un tribunal superior ordinario del país donde se haya dictado el fallo.

**Art. 247 (244).** En todos los casos a que se refieren los artículos precedentes, la resolución que se trate de ejecutar se presentará a la Corte Suprema en copia legalizada o apostillada.

**Art. 248 (245).** En los casos de jurisdicción contenciosa, se dará conocimiento de la solicitud a la parte contra quien se pide la ejecución, la cual tendrá para exponer lo que estime conveniente un término igual al de emplazamiento para contestar demandas.Con la contestación de la parte o en su rebeldía, y con previa audiencia del fiscal judicial, el tribunal declarará si debe o no darse cumplimiento a la resolución.

**Art. 249 (246).** En los asuntos de jurisdicción no contenciosa, el tribunal resolverá con sólo la audiencia del fiscal judicial.

**Art. 250 (247).** Si el tribunal lo estima necesario, podrá abrir un término de prueba antes de resolver, en la forma y por el tiempo que este Código establece para los incidentes.

**Art. 251 (248).** Mandada cumplir una resolución pronunciada en país extranjero, se pedirá su ejecución al tribunal a quien habría correspondido conocer del negocio en primera o en única instancia, si el juicio se hubiera promovido en Chile.



## Título XX. DE LAS MULTAS

**Art. 252 (249).** Todas las multas que este Código establece o autoriza, se impondrán a beneficio fiscal enterándose en la cuenta corriente del tribunal respectivo y se entregarán anualmente a los respectivos Consejos del Colegio de Abogados, para que con ellas atiendan de preferencia a los fines que señalan la letra m) del artículo 12 y las letras j) y k) del artículo 13 de la Ley N° 4.409, de 11 de Septiembre de 1928.

Las multas deberán pagarse dentro de los quince días siguientes a la fecha de notificación de la respectiva resolución. El incumplimiento se comunicará a la Tesorería General de la República y a la Contraloría General de la República para los efectos de su cobranza y de su inclusión en la lista de deudores fiscales.



