# Libro Segundo. DEL JUICIO ORDINARIO {.unnumbered}

## Título I. DE LA DEMANDA

**Art. 253 (250).** Todo juicio ordinario comenzará por demanda del actor, sin perjuicio de lo dispuesto en el Título IV de este Libro.

**Art. 254 (251).** La demanda debe contener:

1°. La designación del tribunal ante quien se entabla;

2°. El nombre, domicilio y profesión u oficio del demandante y de las personas que lo representen, y la naturaleza de la representación;

3°. El nombre, domicilio y profesión u oficio del demandado;

4°. La exposición clara de los hechos y fundamentos de derecho en que se apoya; y

5°. La enunciación precisa y clara, consignada en la conclusión de las peticiones que se sometan al fallo del tribunal.

**Artículo 255.-** Los documentos acompañados a la demanda deberán impugnarse dentro del término de emplazamiento, cualquiera sea su naturaleza.

**Art. 256 (253).** Puede el juez de oficio no dar curso a la demanda que no contenga las indicaciones ordenadas en los tres primeros números del artículo 254, expresando el defecto de que adolece.

**Art. 257 (254).** Admitida la demanda, se conferirá traslado de ella al demandado para que la conteste.

**Artículo 258.-**  El término de emplazamiento para contestar la demanda será de dieciocho días si el demandado es notificado en la comuna donde funciona el tribunal.

Se aumentará este término en tres días más si el demandado se encuentra en el mismo territorio jurisdiccional pero fuera de los límites de la comuna que sirva de asiento al tribunal.

**Art. 259 (256).** Si el demandado se encuentra en un territorio jurisdiccional diverso o fuera del territorio de la República, el término para contestar la demanda será de dieciocho días, y a más el aumento que corresponda al lugar en que se encuentre. Este aumento será determinado en conformidad a una tabla que cada cinco años formará la Corte Suprema con tal objeto, tomando en consideración las distancias y las facilidades o dificultades que existan para las comunicaciones.

Esta tabla se formará en el mes de Noviembre del año que preceda al del vencimiento de los cinco años indicados, para que se ponga en vigor en toda la República desde el 1° de Marzo siguiente; se publicará en el "Diario Oficial", y se fijará a lo menos, dos meses antes de su vigencia, en el portal de internet del Poder Judicial y en los oficios de todos los secretarios de Cortes y Juzgados de Letras.

**Art. 260 (257).** Si los demandados son varios, sea que obren separada o conjuntamente, el término para contestar la demanda correrá para todos a la vez, y se contará hasta que expire el último término parcial que corresponda a los notificados.

En los casos en que proceda la pluralidad de demandantes de acuerdo al artículo 18, el plazo para contestar la demanda, determinado según lo dispuesto en los dos artículos anteriores, se aumentará en un día por cada tres demandantes sobre diez que existan en el proceso. Con todo, este plazo adicional no podrá exceder de treinta días.

**Art. 261 (258).** Notificada la demanda a cualquiera de los demandados y antes de la contestación, podrá el demandante hacer en ella las ampliaciones o rectificaciones que estime convenientes.

Estas modificaciones se considerarán como una demanda nueva para los efectos de su notificación, y sólo desde la fecha en que esta diligencia se practique correrá el término para contestar la primitiva demanda.


## Título II. DE LA CONCILIACION

**Art. 262.** En todo juicio civil, en que legalmente sea admisible la transacción, con excepción de los juicios o procedimientos especiales de que tratan los Títulos I, II, III, V y XVI del Libro III, una vez agotados los trámites de discusión y siempre que no se trate de los casos mencionados en el artículo 313, el juez llamará a las partes a conciliación y les propondrá personalmente bases de arreglo.

Para tales efectos, las citará a una audiencia para un día no anterior al quinto ni posterior al decimoquinto contado desde la fecha de notificación de la resolución.  Con todo, en los procedimientos que contemplan una audiencia para recibir la contestación de la demanda, se efectuará también en ella la diligencia de conciliación, evacuado que sea dicho trámite.

El precedente llamado a conciliación no obsta a que el juez pueda, en cualquier estado de la causa, efectuar la misma convocatoria, una vez evacuado el trámite de contestación de la demanda.

**Art. 263.** El juez obrará como amigable componedor. Tratará de obtener un avenimiento total o parcial en el litigio. Las opiniones que emita no lo inhabilitan para seguir conociendo de la causa.

**Art. 264.** A los comparendos de conciliación deberán concurrir las partes por sí o por apoderado. No obstante, el juez podrá exigir la comparecencia personal de las partes, sin perjuicio de la asistencia de sus abogados.

En los procesos en que hubiere pluralidad de partes, la audiencia se llevará a efecto aunque no asistan todas.  La conciliación operará entre aquellas que la acuerden y continuará el juicio con las que no hubieren concurrido o no hubieren aceptado la conciliación.

**Art. 265.** Si los interesados lo piden, la audiencia se suspenderá hasta por media hora para deliberar. Si el tribunal lo estima necesario postergará la audiencia para dentro de tercero día, salvo que las partes acuerden un plazo mayor, y se dejará de ello constancia. A la nueva audiencia éstas concurrirán sin nueva notificación.

**Art. 266.** El juez de oficio ordenará agregar aquellos antecedentes y medios probatorios que estime pertinentes.

**Art. 267.** De la conciliación total o parcial se levantará acta, que consignará sólo las especificaciones del arreglo; la cual subscribirán el juez, las partes que lo deseen y el secretario, y se estimará como sentencia ejecutoriada para todos los efectos legales.

**Art. 268.** Si se rechaza la conciliación, o no se efectúa el comparendo, el secretario certificará este hecho de inmediato, y quedará la carpeta electrónica a disposición del juez para que éste, examinándolos por sí mismo, proceda enseguida a dar cumplimiento a lo señalado en el artículo 318.



## Título III. DE LA JACTANCIA

**Art. 269 (259).** Cuando alguna persona manifieste corresponderle un derecho de que no esté gozando, todo aquél a quien su jactancia pueda afectar, podrá pedir que se la obligue a deducir demanda dentro del plazo de diez días, bajo apercibimiento, si no lo hace, de no ser oída después sobre aquel derecho. Este plazo podrá ampliarse por el tribunal hasta treinta días, habiendo motivo fundado.

**Art. 270 (260).** Se entenderá haber jactancia siempre que la manifestación del jactancioso conste por escrito, o se haya hecho de viva voz, a lo menos, delante de dos personas hábiles para dar testimonio en juicio civil.

Habrá también lugar a deducir demanda de jactancia contra el que haya gestionado como parte en un proceso criminal de que puedan emanar acciones civiles contra el acusado, para el ejercicio de estas acciones.

**Art. 271 (261).** La demanda de jactancia se someterá a los trámites establecidos para el juicio sumario.

Si se da lugar a ella, y vence el plazo concedido al jactancioso para deducir su acción sin que cumpla lo ordenado, deberá la parte interesada solicitar que se declare por el tribunal el apercibimiento a que se refiere el artículo 269. Esta solicitud se tramitará como incidente.

**Art. 272 (262).** La acción de jactancia prescribe en seis meses, contados desde que tuvieron lugar los hechos en que pueda fundarse.


## Título IV. DE LAS MEDIDAS PREJUDICIALES

**Art. 273 (263).** El juicio ordinario podrá prepararse, exigiendo el que pretende demandar de aquel contra quien se propone dirigir la demanda:

1° Declaración jurada acerca de algún hecho relativo a su capacidad para parecer en juicio, o a su personería o al nombre y domicilio de sus representantes;

2° La exhibición de la cosa que haya de ser objeto de la acción que se trata de entablar;

3° La exhibición de sentencias, testamentos, inventarios, tasaciones, títulos de propiedad u otros instrumentos públicos o privados que por su naturaleza puedan interesar a diversas personas;

4° Exhibición de los libros de contabilidad relativos a negocios en que tenga parte el solicitante, sin perjuicio de lo dispuesto en los artículos 42 y 43 del Código de Comercio; y

5° El reconocimiento jurado de firma, puesta en instrumento privado.

La diligencia expresada en el número 5° se decretará en todo caso; las de los otros cuatro sólo cuando, a juicio del tribunal, sean necesarias para que el demandante pueda entrar en el juicio.

**Art. 274 (264).** Si, decretada la diligencia a que se refiere el número 1° del artículo anterior, se rehúsa prestar la declaración ordenada o ésta no es categórica, en conformidad a lo mandado, podrán imponerse al desobediente multas que no excedan de dos sueldos vitales, o arrestos hasta de dos meses, determinados prudencialmente por el tribunal; sin perjuicio de repetir la orden y el apercibimiento.

**Art. 275 (265).** La exhibición, en el caso del número 2° del artículo 273, se hará mostrando el objeto que deba exhibirse, o autorizando al interesado para que lo reconozca y dándole facilidades para ello, siempre que el objeto se encuentre en poder de la persona a quien se ordene la exhibición.

Si el objeto se halla en poder de terceros, cumplirá la persona a quien se ordene la exhibición, expresando el nombre y residencia de dichos terceros, o el lugar donde el objeto se encuentre.

**Art. 276 (266).** Si se rehúsa hacer la exhibición en los términos que indica el artículo precedente, podrá apremiarse al desobediente con multa o arresto en la forma establecida por el artículo 274, y aun decretarse allanamiento del local donde se halle el objeto cuya exhibición se pide.

Iguales apremios podrán decretarse contra los terceros que, siendo meros tenedores del objeto, se nieguen a exhibirlo.

**Art. 277 (267).** Siempre que se dé lugar a las medidas mencionadas en los números 3° y 4° del artículo 273, y la persona a quien incumba su cumplimiento desobedezca, existiendo en su poder los instrumentos o libros a que las medidas se refieren, perderá el derecho de hacerlos valer después, salvo que la otra parte los haga también valer en apoyo de su defensa, o si se justifica o aparece de manifiesto que no los pudo exhibir antes, o si se refieren a hechos distintos de aquellos que motivaron la solicitud de exhibición. Lo cual se entiende sin perjuicio de lo dispuesto en el artículo precedente y en el párrafo 2°, Título II, del Libro I del Código de Comercio.

**Art. 278 (268).** Si se rehúsa el reconocimiento de firma decretado en el caso del número 5° del artículo 273, se procederá en conformidad a las reglas establecidas para el reconocimiento judicial de documentos en el Juicio Ejecutivo.


**Art. 279 (269).** Podrán solicitarse como medidas prejudiciales las precautorias de que trata el Título V de este Libro, existiendo para ello motivos graves y calificados, y concurriendo las circunstancias siguientes:

 1a. Que se determine el monto de los bienes sobre que deben recaer las medidas precautorias; y
 
 2a. Que se rinda fianza u otra garantía suficiente, a juicio del tribunal, para responder por los perjuicios que se originen y multas que se impongan.

**Art. 280 (270).** Aceptada la solicitud a que se refiere el artículo anterior, deberá el solicitante presentar su demanda en el término de diez días y pedir que se mantengan las medidas decretadas. Este plazo podrá ampliarse hasta treinta días por motivos fundados.

Si no se deduce demanda oportunamente, o no se pide en ella que continúen en vigor las medidas precautorias decretadas, o al resolver sobre esta petición el tribunal no mantiene dichas medidas, por este solo hecho quedará responsable el que las haya solicitado de los perjuicios causados, considerándose doloso su procedimiento.

**Art. 281 (271).** Puede pedirse prejudicialmente la inspección personal del tribunal, informe de peritos nombrados por el mismo tribunal, o certificado del ministro de fe, cuando exista peligro inminente de un daño o perjuicio, o se trate de hechos que puedan fácilmente desaparecer.

Para la ejecución de estas medidas se dará previamente conocimiento a la persona a quien se trata de demandar, si se encuentra en el lugar del asiento del tribunal que las decreta, o donde deban ejecutarse. En los demás casos se procederá con intervención del defensor de ausentes.

**Art. 282 (272).** Si aquel a quien se intenta demandar expone ser simple tenedor de la cosa de que procede la acción o que es objeto de ella, podrá también ser obligado:

1°. A declarar bajo juramento el nombre y residencia de la persona en cuyo nombre la tiene; y

2°. A exhibir el título de su tenencia; y si expresa no tener título escrito, a declarar bajo juramento que carece de él.

En caso de negativa para practicar cualquiera de las diligencias mencionadas en este artículo, se le podrá apremiar con multa o arresto en la forma dispuesta por el artículo 274.

**Art. 283 (273).** Siempre que el actor lo exija, se dejará en el proceso copia de las piezas que se presenten, o de su parte conducente, y una razón de la clase y estado actual de los objetos exhibidos.

**Art. 284 (274).** Si hay motivo fundado para temer que una persona se ausente en breve tiempo del país, podrá exigírsele como medida prejudicial que absuelva posiciones sobre hechos calificados previamente de conducentes por el tribunal, el que, sin ulterior recurso, señalará día y hora para la práctica de la diligencia.

Si se ausenta dicha persona dentro de los treinta días subsiguientes al de la notificación sin absolver las posiciones, o sin dejar apoderado con autorización e instrucciones bastantes para hacerlo durante la secuela del juicio, se le dará por confesa en el curso de éste, salvo que aparezca suficientemente justificada la ausencia sin haber cumplido la orden del tribunal.

**Art. 285 (275).** En el caso del inciso 1° del artículo anterior, podrá también pedirse que aquel cuya ausencia se teme, constituya en el lugar donde va a entablarse el juicio apoderado que le represente y que responda por las costas y multas en que sea condenado, bajo apercibimiento de nombrársele un curador de bienes.

**Art. 286 (276).** Se podrá, asimismo, solicitar antes de la demanda el examen de aquellos testigos cuyas declaraciones, por razón de impedimentos graves, haya fundado temor de que no puedan recibirse oportunamente. Las declaraciones versarán sobre los puntos que indique el actor, calificados de conducentes por el tribunal.

Para practicar esta diligencia, se dará previamente conocimiento a la persona a quien se trata de demandar, sólo cuando se halle en el lugar donde se expidió la orden o donde deba tomarse la declaración; y en los demás casos se procederá con intervención del defensor de ausentes.

**Art. 287 (277).** Para decretar las medidas de que trata este Título, deberá el que las solicite expresar la acción que se propone deducir y someramente sus fundamentos.

**Art. 288 (278).** Toda persona que fundadamente tema ser demandada podrá solicitar las medidas que mencionan el número 5° del artículo 273 y los artículo 281, 284 y 286, para preparar su defensa.

**Art. 289 (279).** Las diligencias expresadas en este Título pueden decretarse sin audiencia de la persona contra quien se piden, salvo los casos en que expresamente se exige su intervención.


## Título V. DE LAS MEDIDAS PRECAUTORIAS

**Art. 290 (280).** Para asegurar el resultado de la acción, puede el demandante en cualquier estado del juicio, aun cuando no esté contestada la demanda, pedir una o más de las siguientes medidas:

1a. El secuestro de la cosa que es objeto de la demanda;

2a. El nombramiento de uno o más interventores;

3a. La retención de bienes determinados; y

4a. La prohibición de celebrar actos o contratos sobre bienes determinados.

**Art. 291 (281).** Habrá lugar al secuestro judicial en el caso del artículo 901 del Código Civil, o cuando se entablen otras acciones con relación a cosa mueble determinada y haya motivo de temer que se pierda o deteriore en manos de la persona que, sin ser poseedora de dicha cosa, la tenga en su poder.

**Art. 292 (282).** Son aplicables al secuestro las disposiciones que el Párrafo 2° del Título I del Libro III establece respecto del depositario de los bienes embargados.

**Art. 293 (283).** Hay lugar al nombramiento de interventor:

 1°. En el caso del inciso 2° del artículo 902 del Código Civil;
 
 2°. En el del que reclama una herencia ocupada por otro, si hay el justo motivo de temor que el citado inciso expresa;
 
 3°. En el del comunero o socio que demanda la cosa común, o que pide cuentas al comunero o socio que administra;
 
 4°. Siempre que haya justo motivo de temer que se destruya o deteriore la cosa sobre que versa el juicio, o que los derechos del demandante puedan quedar burlados; y
 
 5°. En los demás casos expresamente señalados por las leyes.

**Art. 294 (284).** Las facultades del interventor judicial se limitarán a llevar cuenta de las entradas y gastos de los bienes sujetos a intervención, pudiendo para el desempeño de este cargo imponerse de los libros, papeles y operaciones del demandado.

Estará, además, el interventor obligado a dar al interesado o al tribunal noticia de toda malversación o abuso que note en la administración de dichos bienes; y podrá en este caso decretarse el depósito y retención de los productos líquidos en un establecimiento de crédito o en poder de la persona que el tribunal designe, sin perjuicio de las otras medidas más rigurosas que el tribunal estime necesario adoptar.

**Art. 295 (285).** La retención de dineros o cosas muebles podrá hacerse en poder del mismo demandante, del demandado o de un tercero, con relación a los bienes que son materia del juicio, y también respecto de otros bienes determinados del demandado, cuando sus facultades no ofrezcan suficiente garantía, o haya motivo racional para creer que procurará ocultar sus bienes, y en los demás casos determinados por la ley.

Podrá el tribunal ordenar que los valores retenidos se trasladen a un establecimiento de crédito o de la persona que el tribunal designe cuando lo estime conveniente para la seguridad de dichos valores.

**Art. 296 (286).** La prohibición de celebrar actos o contratos podrá decretarse con relación a los bienes que son materia del juicio, y también respecto de otros bienes determinados del demandado, cuando sus facultades no ofrezcan suficiente garantía para asegurar el resultado del juicio.

Para que los objetos que son materia del juicio se consideren comprendidos en el número 4° del artículo 1464 del Código Civil, será necesario que el tribunal decrete prohibición respecto de ellos.

**Art. 297 (287).** Cuando la prohibición recaiga sobre bienes raíces se inscribirá en el registro del Conservador respectivo, y sin este requisito no producirá efecto respecto de terceros.

Cuando verse sobre cosas muebles, sólo producirá efecto respecto de los terceros que tengan conocimiento de ella al tiempo del contrato; pero el demandado será en todo caso responsable de fraude, si ha procedido a sabiendas.

**Art. 298 (288).** Las medidas de que trata este Título se limitarán a los bienes necesarios para responder a los resultados del juicio; y para decretarlas deberá el demandante acompañar comprobantes que constituyan a lo menos presunción grave del derecho que se reclama. Podrá también el tribunal, cuando lo estime necesario y no tratándose de medidas expresamente autorizadas por la ley, exigir caución al actor para responder de los perjuicios que se originen.

**Art. 299 (289).** En casos graves y urgentes podrán los tribunales conceder las medidas precautorias de que trata este Título, aun cuando falten los comprobantes requeridos, por un término que no exceda de diez días, mientras se presentan dichos comprobantes, exigiendo caución para responder por los perjuicios que resulten. Las medidas así decretadas quedarán de hecho canceladas si no se renuevan en conformidad al artículo 280.

**Art. 300 (290).** Estas providencias no excluyen las demás que autorizan las leyes.

**Art. 301 (291).** Todas estas medidas son esencialmente provisionales. En consecuencia, deberán hacerse cesar siempre que desaparezca el peligro que se ha procurado evitar o se otorguen cauciones suficientes.

**Art. 302 (292).** El incidente a que den lugar las medidas de que trata este Título se tramitará en conformidad a las reglas generales y por cuerda separada.

Podrán, sin embargo, llevarse a efecto dichas medidas antes de notificarse a la persona contra quien se dictan, siempre que existan razones graves para ello y el tribunal así lo ordene. Transcurridos cinco días sin que la notificación se efectúe, quedarán sin valor las diligencias practicadas. El tribunal podrá ampliar este plazo por motivos fundados.

La notificación a que se refiere este artículo podrá hacerse por cédula, si el tribunal así lo ordena.


## Título VI. DE LAS EXCEPCIONES DILATORIAS

**Art. 303 (293).** Sólo son admisibles como excepciones dilatorias:

1a. La incompetencia del tribunal ante quien se haya presentado la demanda;

2a. La falta de capacidad del demandante, o de personería o representación legal del que comparece en su nombre;

3a. La litis pendencia;

4a. La ineptitud del libelo por razón de falta de algún requisito legal en el modo de proponer la demanda;

5a. El beneficio de excusión; y

6a. En general las que se refieran a la corrección del procedimiento sin afectar al fondo de la acción deducida.

**Art. 304 (294).** Podrán también oponerse y tramitarse del mismo modo que las dilatorias la excepción de cosa juzgada y la de transacción; pero, si son de lato conocimiento, se mandará contestar la demanda, y se reservarán para fallarlas en la sentencia definitiva.

**Art. 305 (295).** Las excepciones dilatorias deben oponerse todas en un mismo escrito y dentro del término de emplazamiento fijado por los artículos 258 a 260.

Si así no se hace, se podrán oponer en el progreso del juicio sólo por vía de alegación o defensa, y se estará a lo dispuesto en los artículos 85 y 86.

Las excepciones 1a. y 3a. del artículo 303 podrán oponerse en segunda instancia en forma de incidente.

**Art. 306 (296).** Todas las excepciones propuestas conjuntamente se fallarán a la vez, pero si entre ellas figura la de incompetencia y el tribunal la acepta, se abstendrá de pronunciarse sobre las demás. Lo cual se entiende sin perjuicio de lo dispuesto por el artículo 208.

**Art. 307 (297).** Las excepciones dilatorias se tramitarán como incidentes.

La resolución que las deseche será apelable sólo en el efecto devolutivo.

**Art. 308 (298).** Desechadas las excepciones dilatorias o subsanados por el demandante los defectos de que adolezca la demanda, tendrá diez días el demandado para contestarla, cualquiera que sea el lugar en donde le haya sido notificada.


## Título VII. DE LA CONTESTACION Y DEMAS TRAMITES HASTA EL ESTADO DE PRUEBA O DE SENTENCIA

**Art. 309 (299).** La contestación a la demanda debe contener:

1°. La designación del tribunal ante quien se presente;

2°. El nombre, domicilio y profesión u oficio del demandado;

3°. Las excepciones que se oponen a la demanda y la exposición clara de los hechos y fundamentos de derecho en que se apoyan; y

4°. La enunciación precisa y clara, consignada en la conclusión, de las peticiones que se sometan al fallo del tribunal.

**Art. 310 (300).** No obstante lo dispuesto en el artículo anterior, las excepciones de prescripción, cosa juzgada, transacción y pago efectivo de la deuda, cuando ésta se funde en un antecedente escrito, podrán oponerse en cualquier estado de la causa; pero no se admitirán si no se alegan por escrito antes de la citación para sentencia en primera instancia, o de la vista de la causa en segunda.

Si se formulan en primera instancia, después de recibida la causa a prueba, se tramitarán como incidentes, que pueden recibirse a prueba, si el tribunal lo estima necesario, y se reservará su resolución para definitiva.

Si se deducen en segunda, se seguirá igual procedimiento, pero en tal caso el tribunal de alzada se pronunciará sobre ellas en única instancia.

**Art. 311 (301).** De la contestación se comunicará traslado al actor por el término de seis días, y de la réplica al demandado por igual término.

**Art. 312 (302).** En los escritos de réplica y dúplica podrán las partes ampliar, adicionar o modificar las acciones y excepciones que hayan formulado en la demanda y contestación, pero sin que puedan alterar las que sean objeto principal del pleito.

**Art. 313 (303).** Si el demandado acepta llanamente las peticiones del demandante, o si en sus escritos no contradice en materia substancial y pertinente los hechos sobre que versa el juicio, el tribunal mandará citar a las partes para oír sentencia definitiva, una vez evacuado el traslado de la réplica.

Igual citación se dispondrá cuando las partes pidan que se falle el pleito sin más trámite.


## Título VIII. DE LA RECONVENCION

**Art. 314 (304).** Si el demandado reconviene al actor, deberá hacerlo en el escrito de contestación, sujetándose a las disposiciones de los artículos 254 y 261; y se considerará, para este efecto, como demandada la parte contra quien se deduzca la reconvención.

**Art. 315 (305).** No podrá deducirse reconvención sino cuando el tribunal tenga competencia para conocer de ella, estimada como demanda, o cuando sea admisible la prórroga de jurisdicción. Podrá también deducirse aun cuando por su cuantía la reconvención deba ventilarse ante un juez inferior.

Para estimar la competencia, se considerará el monto de los valores reclamados por vía de reconvención separadamente de los que son materia de la demanda.

**Art. 316 (306).** La reconvención se substanciará y fallará conjuntamente con la demanda principal, sin perjuicio de lo establecido en el artículo 172.

De la réplica de la reconvención se dará traslado al demandante por seis días.

No se concederá, sin embargo, en la reconvención aumento extraordinario de término para rendir prueba fuera de la República cuando no deba concederse en la cuestión principal.

**Art. 317 (307).** Contra la reconvención hay lugar a las excepciones dilatorias enumeradas en el artículo 303, las cuales se propondrán dentro del término de seis días y en la forma expresada en el artículo 305.

Acogida una excepción dilatoria, el demandante reconvencional deberá subsanar los defectos de que adolezca la reconvención dentro de los diez días siguientes a la fecha de notificación de la resolución que haya acogido la excepción. Si así no lo hiciere, se tendrá por no presentada la reconvención, para todos los efectos legales, por el solo ministerio de la ley.


## Título IX. DE LA PRUEBA EN GENERAL.

**Art. 318 (308).** Concluídos los trámites que deben preceder a la prueba, ya se proceda con la contestación expresa del demandado o en su rebeldía, el tribunal examinará por sí mismo los autos y si estima que hay o puede haber controversia sobre algún hecho substancial y pertinente en el juicio, recibirá la causa a prueba y fijará en la misma resolución los hechos substanciales controvertidos sobre los cuales deberá recaer.

Sólo podrán fijarse como puntos de pruebas los hechos substanciales controvertidos en los escritos anteriores a la resolución que ordena recibirla.

**Art. 319.** Las partes podrán pedir reposición, dentro de tercero día, de la resolución a que se refiere el artículo anterior. En consecuencia, podrán solicitar que se modifiquen los hechos controvertidos fijados, que se eliminen algunos o que se agreguen otros.

El tribunal se pronunciará de plano sobre la reposición o la tramitará como incidente.

La apelación en contra de la resolución del artículo 318 sólo podrá interponerse en el carácter de subsidiaria de la reposición pedida y para el caso de que ésta no sea acogida. La apelación se concederá sólo en el efecto devolutivo.

**Art. 320 (309).** Desde la primera notificación de la resolución a que se refiere el artículo 318, y hasta el quinto día de la última, cuando no se haya pedido reposición en conformidad al artículo anterior y en el caso contrario, dentro de los cinco días siguientes a la notificación por el estado de la resolución que se pronuncie sobre la última solicitud de reposición, cada parte deberá presentar una minuta de los puntos sobre que piense rendir prueba de testigos, enumerados y especificados con claridad y precisión.

Deberá también acompañar una nómina de los testigos de que piensa valerse, con expresión del nombre y apellido, domicilio, profesión u oficio. La indicación del domicilio deberá contener los datos necesarios a juicio del juzgado, para establecer la identificación del testigo.

Si habiéndose pedido reposición ya se hubiere presentado lista de testigos y minuta de puntos por alguna de las partes, no será necesario presentar nuevas lista ni minuta, salvo que, como consecuencia de haberse acogido el recurso, la parte que las presenta estime pertinente modificarlas.

**Art. 321 (310).** No obstante lo dispuesto en el artículo anterior, es admisible la ampliación de la prueba cuando dentro del término probatorio ocurre algún hecho substancialmente relacionado con el asunto que se ventila.

Será también admisible la ampliación a hechos verificados y no alegados antes de recibirse a prueba la causa, con tal que jure el que los aduce que sólo entonces han llegado a su conocimiento.

**Art. 322 (311).** Al responder la otra parte el traslado de la solicitud de ampliación, podrá también alegar hechos nuevos que reúnan las condiciones mencionadas en el artículo anterior, o que tengan relación con los que en dicha solicitud se mencionan.

El incidente de ampliación se tramitará en conformidad a las reglas generales, en ramo separado, y no suspenderá el término probatorio.

Lo dispuesto en este artículo se entiende sin perjuicio de lo que el artículo 86 establece.

**Art. 323 (312).** Cuando haya de rendirse prueba en un incidente, la resolución que lo ordene determinará los puntos sobre que debe recaer, y su recepción se hará en conformidad a las reglas establecidas para la prueba principal.

La referida resolución se notificará por el estado.

**Art. 324 (313).** Toda diligencia probatoria debe practicarse previo decreto del tribunal que conoce en la causa, notificado a las partes.

**Art. 325 (314).** En los tribunales colegiados podrán practicarse las diligencias probatorias ante uno solo de sus miembros comisionado al efecto por el tribunal.

**Art. 326 (315).** Es apelable la resolución en que explícita o implícitamente se niegue el trámite de recepción de la causa a prueba, salvo el caso del inciso 2° del artículo 313. Es apelable sólo en el efecto devolutivo la que acoge la reposición a que se refiere el artículo 319.

Son inapelables la resolución que dispone la práctica de alguna diligencia probatoria y la que da lugar a la ampliación de la prueba sobre hechos nuevos alegados durante el término probatorio.


## Título X. DEL TERMINO PROBATORIO

**Art. 327. Todo término probatorio es común para las partes y dentro de él deberán solicitar toda diligencia de prueba que no hubieren pedido con anterioridad a su iniciación.

En los casos contemplados en los artículos 310, 321 y 322 el tribunal, de estimar necesaria la prueba, concederá un término especial de prueba que se regirá por las normas del artículo 90, limitándose a quince días el plazo total que establece en su inciso tercero y sin perjuicio de lo establecido en el artículo 431.

**Art. 328 (317).** Para rendir prueba dentro del territorio jurisdiccional del tribunal en que se sigue el juicio tendrán las partes el término de veinte días.

Podrá, sin embargo, reducirse este término por acuerdo unánime de las partes.

**Art. 329 (318).** Cuando haya de rendirse prueba en otro territorio jurisdiccional o fuera de la República, se aumentará el término ordinario a que se refiere el artículo anterior con un número de días igual al que concede el artículo 259 para aumentar el de emplazamiento.

**Art. 330 (319).** El aumento extraordinario para rendir prueba dentro de la República se concederá siempre que se solicite, salvo que haya justo motivo para creer que se pide maliciosamente con el solo propósito de demorar el curso del juicio.

**Art. 331 (320).** No se decretará el aumento extraordinario para rendir prueba fuera de la República sino cuando concurran las circunstancias siguientes:

1a. Que del tenor de la demanda, de la contestación o de otra pieza del expediente aparezca que los hechos a que se refieren las diligencias probatorias solicitadas han acaecido en el país en que deben practicarse dichas diligencias, o que allí existen los medios probatorios que se pretende obtener;
 
2a. Que se determine la clase y condición de los instrumentos de que el solicitante piensa valerse y el lugar en que se encuentran; y
 
3a. Que, tratándose de prueba de testigos, se exprese su nombre y residencia o se justifique algún antecedente que haga presumible la conveniencia de obtener sus declaraciones.

**Art. 332 (321).** El aumento extraordinario para rendir prueba deberá solicitarse antes de vencido el término ordinario, determinando el lugar en que dicha prueba debe rendirse.

**Art. 333 (322).** Todo aumento del término ordinario continuará corriendo después de éste sin interrupción y sólo durará para cada localidad el número de días fijado en la tabla respectiva.

**Art. 334 (323).** Se puede, durante el término ordinario, rendir prueba en cualquier parte de la República y fuera de ella.

**Art. 335 (324).** Vencido el término ordinario, sólo podrá rendirse prueba en aquellos lugares para los cuales se haya otorgado aumento extraordinario del término.

**Art. 336 (325).** El aumento extraordinario para rendir prueba dentro de la República se otorgará con previa citación; el que deba producir efecto fuera del país se decretará con audiencia de la parte contraria.

Los incidentes a que dé lugar la concesión de aumento extraordinario se tramitarán en pieza separada y no suspenderán el término probatorio.

Con todo no se contarán en el aumento extraordinario los días transcurridos mientras dure el incidente sobre concesión del mismo.

**Art. 337 (326).** La parte que haya obtenido aumento extraordinario del término para rendir prueba dentro o fuera de la República, y no la rinda, o sólo rinda una impertinente, será obligada a pagar a la otra parte los gastos que ésta haya hecho para presenciar las diligencias pedidas, sea personalmente, sea por medio de mandatarios.

Esta condenación se impondrá en la sentencia definitiva y podrá el tribunal exonerar de ella a la parte que acredite no haberla rendido por motivos justificados.

**Art. 338 (327).** Siempre que se solicite aumento extraordinario para rendir prueba fuera de la República, exigirá el tribunal, para dar curso a la solicitud, que se deposite en la cuenta corriente del tribunal una cantidad cuyo monto no podrá fijarse en menos de medio sueldo vital ni en más de dos sueldos vitales.

Sin perjuicio de lo que dispone el artículo anterior, se mandará aplicar al Fisco la cantidad consignada si resulta establecida en el proceso alguna de las circunstancias siguientes:

1a. Que no se ha hecho diligencia alguna para rendir la prueba pedida;

2a. Que los testigos señalados, en el caso del artículo 331, no tenían conocimiento de los hechos, ni se han hallado en situación de conocerlos; y

3a. Que los testigos o documentos no han existido nunca en el país en que se ha pedido que se practiquen las diligencias probatorias.

**Art. 339 (328).** El término de prueba no se suspenderá en caso alguno, salvo que todas las partes lo pidan. Los incidentes que se formulen durante dicho término o que se relacionen con la prueba, se tramitarán en cuaderno separado.

Si durante él ocurren entorpecimientos que imposibiliten la recepción de la prueba, sea absolutamente, sea respecto de algún lugar determinado, podrá otorgarse por el tribunal un nuevo término especial por el número de días que haya durado el entorpecimiento y para rendir prueba sólo en el lugar a que dicho entorpecimiento se refiera.

No podrá usarse de este derecho si no se reclama del obstáculo que impide la prueba en el momento de presentarse o dentro de los tres días siguientes.

Deberá concederse un término especial de prueba por el número de días que fije prudencialmente el tribunal, y que no podrá exceder de ocho, cuando tenga que rendirse nueva prueba, de acuerdo con la resolución que dicte  el tribunal de alzada, acogiendo la apelación subsidiaria a que se refiere el artículo 319. Para hacer uso de este derecho no se necesita la reclamación ordenada en el inciso anterior. La prueba ya producida y que no esté afectada por la resolución del tribunal de alzada tendrá pleno valor.

**Art. 340 (329).** Las diligencias de prueba de testigos sólo podrán practicarse dentro del término probatorio.

Sin embargo, las diligencias iniciadas en tiempo hábil y no concluidas en él por impedimento cuya remoción no haya dependido de la parte interesada, podrán practicarse dentro de un breve término que el tribunal señalará, por una sola vez, para este objeto. Este derecho no podrá reclamarse sino dentro del término probatorio o de los tres días siguientes a su vencimiento.

Siempre que el entorpecimiento que imposibilite la recepción de la prueba sea la inasistencia del juez de la causa, deberá el secretario, a petición verbal de cualquiera de las partes, certificar el hecho en el proceso y con el mérito de este certificado fijará el tribunal nuevo día para la recepción de la prueba.


## Título XI. DE LOS MEDIOS DE PRUEBA EN PARTICULAR
 
***1. Disposiciones generales.***

**Art. 341 (330).** Los medios de prueba de que puede hacerse uso en juicio son:

Instrumentos;
 
Testigos;
 
Confesión de parte;
 
Inspección personal del tribunal;
 
Informes de peritos; y Presunciones.


***2. De los instrumentos.***

**Art. 342 (331).** Serán considerados como instrumentos públicos en juicio, siempre que en su otorgamiento se hayan cumplido las disposiciones legales que dan este carácter:

1°. Los documentos originales;

2°. Las copias dadas con los requisitos que las leyes prescriban para que hagan fe respecto de toda persona, o, a lo menos, respecto de aquella contra quien se hacen valer;

3°. Las copias que, obtenidas sin estos requisitos, no sean objetadas como inexactas por la parte contraria dentro de los tres días siguientes a aquel en que se le dio conocimiento de ellas;

4°. Las copias que, objetadas en el caso del número anterior, sean cotejadas y halladas conforme con sus originales o con otras copias que hagan fe respecto de la parte contraria; y

5°. Los testimonios que el tribunal mande agregar durante el juicio, autorizados por su secretario u otro funcionario competente y sacados de los originales o de copias que reúnan las condiciones indicadas en el número anterior.

6°. Los documentos electrónicos suscritos mediante firma electrónica avanzada.

**Art. 343 (332).** Cuando las copias agregadas sólo tengan una parte del instrumento original, cualquiera de los interesados en el pleito podrá exigir que se agregue el todo o parte de lo omitido, a sus expensas, sin perjuicio de lo que se resuelva sobre pago de costas.

**Art. 344 (333).** El cotejo de instrumentos se hará por el funcionario que haya autorizado la copia presentada en el juicio, por el secretario del tribunal o por otro ministro de fe que dicho tribunal designe.

**Art. 345 (334).** Los instrumentos públicos otorgados fuera de Chile deberán presentarse debidamente legalizados, y se entenderá que lo están cuando en ellos conste el carácter público y la verdad de las firmas de las personas que los han autorizado, atestiguadas ambas circunstancias por los funcionarios que, según las leyes o la práctica de cada país, deban acreditarlas.

La autenticidad de las firmas y el carácter de estos funcionarios se comprobará en Chile por alguno de los medios siguientes:

1°. El atestado de un agente diplomático o consular chileno, acreditado en el país de donde el instrumento procede, y cuya firma se compruebe con el respectivo certificado del Ministerio de Relaciones Exteriores;
 
2°. El atestado de un agente diplomático o consular de una nación amiga acreditado en el mismo país, a falta de funcionario chileno, certificándose en este caso la firma por conducto del Ministerio de Relaciones Exteriores del país a que pertenezca el agente o del Ministro Diplomático de dicho país en Chile, y además por el Ministerio de Relaciones Exteriores de la República en ambos casos; y
 
3°. El atestado del agente diplomático acreditado en Chile por el Gobierno del país en donde se otorgó el instrumento, certificándose su firma por el Ministerio de Relaciones Exteriores de la República.

**Artículo 345 bis.-** Los instrumentos públicos otorgados en un Estado Parte de la Convención de La Haya que Suprime la Exigencia de Legalización de Documentos Públicos Extranjeros, no deberán ser sometidos al procedimiento de legalización, si respecto de éstos se ha otorgado apostillas por la autoridad designada por el Estado de que dimana dicho instrumento.

Las certificaciones oficiales que hayan sido asentadas sobre documentos privados, tales como menciones de registro, comprobaciones para la certeza de una fecha y autenticaciones de firmas, podrán presentarse legalizadas o con apostillas otorgadas, con arreglo al artículo precedente y a éste, respectivamente. Pero en estos casos la legalización o apostilla sólo acreditará la autenticidad de la certificación, sin otorgar al instrumento el carácter de público.

Según lo dispuesto por la Convención a que se refiere el inciso primero, no podrán otorgarse apostillas respecto de los documentos expedidos por  agentes diplomáticos o consulares y los documentos administrativos que se refieren directamente a una operación mercantil o aduanera.

**Art. 346 (335).** Los instrumentos privados se tendrán por reconocidos:

1°. Cuando así lo ha declarado en el juicio la persona a cuyo nombre aparece otorgado el instrumento o la parte contra quien se hace valer;

2°. Cuando igual declaración se ha hecho en un instrumento público o en otro juicio diverso;

3°. Cuando, puestos en conocimiento de la parte contraria, no se alega su falsedad o falta de integridad dentro de los seis días siguientes a su presentación, debiendo el tribunal, para este efecto, apercibir a aquella parte con el reconocimiento tácito del instrumento si nada expone dentro de dicho plazo; y 

4°. Cuando se declare la autenticidad del instrumento por resolución judicial.

**Art. 347 (336).** Los instrumentos extendidos en lengua extranjera se mandarán traducir por el perito que el tribunal designe, a costa del que los presente, sin perjuicio de lo que se resuelva sobre costas en la sentencia.

Si al tiempo de acompañarse se agrega su traducción, valdrá ésta; salvo que la parte contraria exija, dentro de seis días, que sea revisada por un perito, procediéndose en tal caso como lo dispone el inciso anterior.

**Art. 348 (337).** Los instrumentos podrán presentarse en cualquier estado del juicio hasta el vencimiento del término probatorio en primera instancia, y hasta la vista de la causa en segunda instancia.

La agregación de los que se presenten en segunda instancia, no suspenderá en ningún caso la vista de la causa; pero el tribunal no podrá fallarla, sino después de vencido el término de la citación, cuando haya lugar a ella.

**Artículo 348 bis.** Presentado un documento electrónico, el Tribunal citará para el 6° día a todas las partes a una audiencia de percepción documental. En caso de no contar con los medios técnicos electrónicos necesarios para su adecuada percepción, apercibirá a la parte que presentó el documento con tenerlo por no presentado de no concurrir a la audiencia con dichos medios.

Tratándose de documentos que no puedan ser transportados al tribunal, la audiencia tendrá lugar donde éstos se encuentren, a costa de la parte que los presente.

En caso que el documento sea objetado, en conformidad con las reglas generales, el Tribunal podrá ordenar una prueba complementaria de autenticidad, a costa de la parte que formula la impugnación, sin perjuicio de lo que se resuelva sobre pago de costas. El resultado de la prueba complementaria de autenticidad será suficiente para tener por reconocido o por objetado el instrumento, según corresponda.

Para los efectos de proceder a la realización de la prueba complementaria de autenticidad, los peritos procederán con sujeción a lo dispuesto por los artículos 417 a 423.

En el caso de documentos electrónicos privados, para los efectos del artículo 346, N°3, se entenderá que han sido puestos en conocimiento de la parte contraria en la audiencia de percepción.

En el caso que los documentos electrónicos acompañados puedan ser percibidos directamente en la carpeta electrónica, el tribunal podrá omitir la citación a audiencia de percepción, debiéndose entender que han sido puestos en conocimiento de la parte contraria desde que se notifica la resolución que los tiene por acompañados bajo el apercibimiento correspondiente.

**Art. 349 (338).** Podrá decretarse, a solicitud de parte, la exhibición de instrumentos que existan en poder de la otra parte o de un tercero, con tal que tengan relación directa con la cuestión debatida y que no revistan el carácter de secretos o confidenciales.

Los gastos que la exhibición haga necesarios serán de cuenta del que la solicite, sin perjuicio de lo que se resuelva sobre pago de costas.

Si se rehúsa la exhibición sin justa causa, podrá apremiarse al desobediente en la forma establecida por el artículo 274; y si es la parte misma, incurrirá además en el apercibimiento establecido por el artículo 277.

Cuando la exhibición haya de hacerse por un tercero, podrá éste exigir que en su propia casa u oficina se saque testimonio de los instrumentos por un ministro de fe.

**Art. 350 (339).** Podrá pedirse el cotejo de letras siempre que se niegue por la parte a quien perjudique o se ponga en duda la autenticidad de un documento privado o la de cualquier documento público que carezca de matriz.

En este cotejo procederán los peritos con sujeción a lo dispuesto por los artículos 417 hasta 423 inclusive.

**Art. 351 (340).** La persona que pida el cotejo designará el instrumento o instrumentos indubitados con que debe hacerse.

**Art. 352 (341).** Se considerarán indubitados para el cotejo:

1°. Los instrumentos que las partes acepten como tales, de común acuerdo;

2°. Los instrumentos públicos no tachados de apócrifos o suplantados; y

3°. Los instrumentos privados cuya letra o firma haya sido reconocida de conformidad a los números 1° y 2° del artículo 346.

**Art. 353 (342).** El tribunal hará por sí mismo la comprobación después de oír a los peritos revisores y no tendrá que sujetarse al dictamen de éstos.

**Art. 354 (343).** El cotejo de letras no constituye por sí solo prueba suficiente; pero podrá servir de base para una presunción judicial.

**Art. 355 (344).** En el incidente sobre autenticidad de un instrumento o sobre suplantaciones hechas en él, se admitirán como medios probatorios, tanto el cotejo de que tratan los cinco artículos precedentes, como los que las leyes autoricen para la prueba del fraude.

En la apreciación de los diversos medios de prueba opuestos al mérito de un instrumento, el tribunal se sujetará a las reglas generales establecidas en el presente Título, y con especialidad a las consignadas en el Párrafo 8°.

***3. De los testigos de las tachas.***

**Art. 356 (345).** Es hábil para testificar en juicio toda persona a quien la ley no declare inhábil.

**Art. 357 (346).** No son hábiles para declarar como testigos:

1°. Los menores de catorce años. Podrán, sin embargo, aceptarse las declaraciones sin previo juramento y estimarse como base para una presunción judicial, cuando tengan discernimiento suficiente;

2°. Los que se hallen en interdicción por causa de demencia;

3°. Los que al tiempo de declarar, o al de verificarse los hechos sobre que declaran, se hallen privados de la razón, por ebriedad u otra causa;

4°. Los que carezcan del sentido necesario para percibir los hechos declarados al tiempo de verificarse éstos;

5°. Los sordos o sordomudos que no puedan darse a entender claramente;

6°. Los que en el mismo juicio hayan sido cohechados, o hayan cohechado o intentado cohechar a otros, aun cuando no se les haya procesado criminalmente;

7°. Los vagos sin ocupación u oficio conocido;

8°. Los que en concepto del tribunal sean indignos de fe por haber sido condenados por delito; y

9°. Los que hagan profesión de testificar en juicio.

**Art. 358 (347).** Son también inhábiles para declarar:

1°. El cónyuge y los parientes legítimos hasta el cuarto grado de consanguinidad y segundo de afinidad de la parte que los presenta como testigos;

2°. Los ascendientes, descendientes y hermanos ilegítimos, cuando haya reconocimiento del parentesco que produzca efectos civiles respecto de la parte que solicite su declaración;

3°. Los pupilos por sus guardadores y viceversa;

4°. Los criados domésticos o dependientes de la parte que los presente.

Se entenderá por dependiente, para los efectos de este artículo, el que preste habitualmente servicios retribuidos al que lo haya presentado por testigo, aunque no viva en su casa;

5°. Los trabajadores y labradores dependientes de la persona que exige su testimonio;

6°. Los que a juicio del tribunal carezcan de la imparcialidad necesaria para declarar por tener en el pleito interés directo o indirecto; y

7°. Los que tengan íntima amistad con la persona que los presenta o enemistad respecto de la persona contra quien declaren.

La amistad o enemistad deberán ser manifestadas por hechos graves que el tribunal calificará según las circunstancias.

Las inhabilidades que menciona este artículo no podrán hacerse valer cuando la parte a cuyo favor se hallan establecidas, presente como testigos a las mismas personas a quienes podrían aplicarse dichas tachas.

**Art. 359 (348).** Toda persona, cualquiera que sea su estado o profesión, está obligada a declarar y a concurrir a la audiencia que el tribunal señale con este objeto.

Cuando se exija la comparecencia de un testigo a sabiendas de que es inútil su declaración, podrá imponer el tribunal a la parte que la haya exigido una multa de un décimo a medio sueldo vital.

**Art. 360 (349).** No serán obligados a declarar:

1°. Los eclesiásticos, abogados, escribanos, procuradores, médicos y matronas, sobre hechos que se les hayan comunicado confidencialmente con ocasión de su estado, profesión u oficio;

2°. Las personas expresadas en los números 1°, 2° y 3° del artículo 358; y

3°. Los que son interrogados acerca de hechos que afecten el honor del testigo o de las personas mencionadas en el número anterior, o que importen un delito de que pueda ser criminalmente responsable el declarante o cualquiera de las personas referidas.

**Art. 361 (350).** Podrán declarar en el domicilio que fijen dentro del territorio jurisdiccional del tribunal:

1°. El Presidente de la República, los Ministros de Estado, los Senadores y Diputados, los Subsecretarios; los Delegados Presidenciales Regionales, Delegados Presidenciales Provinciales y los Alcaldes, dentro del territorio de su jurisdicción; los jefes superiores de Servicios, los miembros de la Corte Suprema o de alguna Corte de Apelaciones, los Fiscales Judiciales de estos Tribunales, los Jueces Letrados, el Fiscal Nacional y los fiscales regionales; los Oficiales Generales en servicio activo o en retiro, los Oficiales Superiores y los Oficiales Jefes;

2°. Derogado;

3°. Eliminado.

4°. Las mujeres, siempre que por su estado o posición no puedan concurrir sin grave molestia; y

5°. Los que por enfermedad u otro impedimento, calificado por el tribunal, se hallen en la imposibilidad de hacerlo.

Para este efecto, dentro del tercer día hábil siguiente a su notificación, las personas mencionadas propondrán al tribunal el lugar y la fecha, comprendida dentro del término probatorio, de realización de la audiencia respectiva. El juez los fijará sin más trámite si el interesado así no lo hiciere ni comunicare su renuncia al derecho que le confiere este artículo.

Con todo, los miembros y fiscales judiciales de las Cortes y los jueces letrados que ejerzan sus funciones en el asiento de éstas, no declararán sin previo permiso de la Corte Suprema, tratándose de algún miembro o fiscal judicial de este tribunal, o de la respectiva Corte de Apelaciones en los demás casos. Este permiso se concederá siempre que no parezca que sólo se trata de establecer, respecto del juez o fiscal judicial presentado como testigo, una causa de recusación.

**Art. 362 (351).** No están obligados a declarar ni a concurrir a la audiencia judicial los chilenos o extranjeros que gocen en el país de inmunidad diplomática, en conformidad a los tratados vigentes sobre la materia.

Estas personas declararán por informe, si consintieran a ello voluntariamente. Al efecto, se les dirigirá un oficio respetuoso, por medio del Ministerio respectivo.

**Art. 363 (352).** Antes de examinar a cada testigo, se le hará prestar juramento al tenor de la fórmula siguiente: "¿Juráis por Dios decir verdad acerca de lo que se os va a preguntar?". El interrogado responderá:
 "Sí juro", conforme a lo dispuesto en el artículo 62.

**Art. 364 (353).** Los testigos de cada parte serán examinados separada y sucesivamente, principiando por los del demandante, sin que puedan unos presenciar las declaraciones de los otros.

El tribunal adoptará las medidas conducentes para evitar que los testigos que vayan declarando puedan comunicarse con los que no hayan prestado declaración.

**Art. 365 (354).** Los testigos serán interrogados personalmente por el juez, y si el tribunal es colegiado, por uno de sus ministros a presencia de las partes y de sus abogados, si concurren al acto.

Las preguntas versarán sobre los datos necesarios para establecer si existen causas que inhabiliten al testigo para declarar y sobre los puntos de prueba que se hayan fijado. Podrá también el tribunal exigir que los testigos rectifiquen, esclarezcan o precisen las aseveraciones hechas.

**Art. 366 (355).** Cada parte tendrá derecho para dirigir, por conducto del juez, las interrogaciones que estime conducentes a fin de establecer las causales de inhabilidad legal que puedan oponerse a los testigos, y a fin de que éstos rectifiquen, esclarezcan o precisen los hechos sobre los cuales se invoca su testimonio.

En caso de desacuerdo entre las partes sobre la conducencia de las preguntas resolverá el tribunal y su fallo será apelable sólo en lo devolutivo.

**Art. 367 (356).** Los testigos deben responder de una manera clara y precisa a las preguntas que se les hagan, expresando la causa por qué afirman los hechos aseverados. No se les permitirá llevar escrita su declaración.

**Art. 368 (357).** La declaración constituye un solo acto que no puede interrumpirse sino por causas graves y urgentes.

**Art. 369 (358).** El tribunal, atendido el número de testigos y el de los puntos de prueba, señalará una o más audiencias para el examen de los que se encuentren en el departamento.

Procurará también, en cuanto sea posible, que todos los testigos de cada parte sean examinados en la misma audiencia.

**Art. 370 (359).** Las declaraciones se consignarán por escrito, conservándose en cuanto sea posible las expresiones de que se haya valido el testigo, reducidas al menor número de palabras. Después de leídas por el receptor en alta voz y ratificadas por el testigo, serán firmadas por el juez, el declarante, si sabe, y las partes, si también saben y se hallan presentes, autorizándolas un receptor, que servirá también como actuario en las incidencias que ocurran durante la audiencia de prueba.

**Art. 371 (360).** Si han de declarar testigos que residan fuera del territorio jurisdiccional en que se sigue el juicio, se practicará su examen por el tribunal que corresponda, a quien se remitirá copia, en la forma que señala el artículo 77, de los puntos de prueba fijados.

El examen se practicará en la forma que establecen los artículos anteriores, pudiendo las partes hacerse representar por encargados, en conformidad al artículo 73.

**Art. 372 (361).** Serán admitidos a declarar solamente hasta seis testigos, por cada parte, sobre cada uno de los hechos que deban acreditarse.

Sólo se examinarán testigos que figuren en la nómina a que se refiere el inciso final del artículo 320. Podrá, con todo, el tribunal admitir otros testigos en casos muy calificados, y jurando la parte que no tuvo conocimiento de ellos al tiempo de formar la nómina de que trata el inciso anterior.

**Art. 373 (362).** Solamente podrán oponerse tachas a los testigos antes de que presten su declaración. En el caso del inciso final del artículo anterior, podrán también oponerse dentro de los tres días subsiguientes al examen de los testigos.

Sólo se admitirán las tachas que se funden en alguna de las inhabilidades mencionadas en los artículos 357 y 358, y con tal que se expresen con la claridad y especificación necesarias para que puedan ser fácilmente comprendidas.

**Art. 374 (363).** Opuesta la tacha y antes de declarar el testigo, podrá la parte que lo presenta pedir que se omita su declaración y que se reemplace por la de otro testigo hábil de los que figuran en la nómina respectiva.

**Art. 375 (364).** Las tachas opuestas por las partes no obstan al examen de los testigos tachados; pero podrán los tribunales repeler de oficio a los que notoriamente aparezcan comprendidos en alguna de las que señala el artículo 357.

La apelación que se interponga en este caso se concederá sólo en el efecto devolutivo.

**Art. 376 (365).** Cuando el tribunal lo estime necesario para resolver el juicio, recibirá las tachas a prueba, la cual se rendirá dentro del término concedido para la cuestión principal. Pero si éste está vencido o lo que de él reste no sea suficiente, se ampliará para el solo efecto de rendir la prueba de tachas hasta completar diez días, pudiendo además solicitarse el aumento extraordinario que concede el artículo 329 en los casos a que él se refiere.

**Art. 377 (366).** Son aplicables a la prueba de tachas las disposiciones que reglamentan la prueba de la cuestión principal.

**Art. 378 (367).** No se admitirá prueba de testigos para inhabilitar a los que hayan declarado sobre las tachas deducidas. Lo cual no obsta para que el tribunal acepte otros medios probatorios, sin abrir término especial, y tome en cuenta las incapacidades que contra los mismos testigos aparezcan en el proceso.

**Art. 379 (368).** Las resoluciones que ordenan recibir prueba sobre las tachas opuestas son inapelables.

No obstante lo dispuesto en el inciso anterior, la legalidad de las tachas y su comprobación serán apreciadas y resueltas en la sentencia definitiva.

**Art. 380 (369).** Siempre que lo pida alguna de las partes, mandará el tribunal que se cite a las personas designadas como testigos en la forma establecida por el artículo 56, indicándose en la citación el juicio en que debe prestarse la declaración y el día y hora de la comparecencia.

El testigo que legalmente citado no comparezca podrá ser compelido por medio de la fuerza a presentarse ante el tribunal que haya expedido la citación, a menos que compruebe que ha estado en imposibilidad de concurrir.

Si compareciendo se niega sin justa causa a declarar, podrá ser mantenido en arresto hasta que preste su declaración.

Todo lo cual se entiende sin perjuicio de la responsabilidad penal que pueda afectar al testigo rebelde.

**Art. 381 (370).** Tiene el testigo derecho para reclamar de la persona que lo presenta, el abono de los gastos que le imponga la comparecencia.

Se entenderá renunciado este derecho si no se ejerce en el plazo de veinte días, contados desde la fecha en que se presta la declaración.

En caso de desacuerdo, estos gastos serán regulados por el tribunal sin forma de juicio y sin ulterior recurso.

**Art. 382 (372).** Si el testigo no supiere el idioma castellano, será examinado por medio de un intérprete mayor de dieciocho años, quien prometerá bajo juramento desempeñar bien y fielmente el cargo.

Por conducto del intérprete se interrogará al testigo y se recibirán sus contestaciones, las cuales serán consignadas en el idioma del testigo, si éste no entendiere absolutamente el castellano. En tal caso, se pondrá al pie de la declaración la traducción que de ella haga el intérprete.

Si el testigo fuere sordo, las preguntas le serán dirigidas por escrito; y si fuere mudo, dará por escrito sus contestaciones.

Si no fuere posible proceder de esta manera, la declaración del testigo será recibida por intermedio de una o más personas que puedan entenderse con él por medio de la lengua de señas, por signos, o que comprendan a los sordos o sordomudos. Estas personas prestarán previamente el juramento de que trata el inciso primero.

**Art. 383 (373).** Los testimonios de oídas, esto es, de testigos que relatan hechos que no han percibido por sus propios sentidos y que sólo conocen por el dicho de otras personas, únicamente podrán estimarse como base de una presunción judicial.

Sin embargo, es válido el testimonio de oídas cuando el testigo se refiere a lo que oyó decir a alguna de las partes, en cuanto de este modo se explica o esclarece el hecho de que se trata.

**Art. 384 (374).** Los tribunales apreciarán la fuerza probatoria de las declaraciones de los testigos conforme a las reglas siguientes:

1a. La declaración de un testigo imparcial y verídico constituye una presunción judicial cuyo mérito probatorio será apreciado en conformidad al artículo 426;

2a. La de dos o más testigos contestes en el hecho y en sus circunstancias esenciales, sin tacha, legalmente examinados y que den razón de sus dichos, podrá constituir prueba plena cuando no haya sido desvirtuada por otra prueba en contrario;

3a. Cuando las declaraciones de los testigos de una parte sean contradictorias con las de los testigos de la otra, tendrán por cierto lo que declaren aquellos que, aun siendo en menor número, parezca que dicen la verdad por estar mejor instruidos de los hechos, o por ser de mejor fama, más imparciales y verídicos, o por hallarse más conformes en sus declaraciones con otras pruebas de proceso;

4a. Cuando los testigos de una y otra parte reúnan iguales condiciones de ciencia, de imparcialidad y de veracidad, tendrán por cierto lo que declare el mayor número;

5a. Cuando los testigos de una y otra parte sean iguales en circunstancias y en número, de tal modo que la sana razón no pueda inclinarse a dar más crédito a los unos que a los otros, tendrán igualmente por no probado el hecho; y

6a. Cuando sean contradictorias las declaraciones de los testigos de una misma parte, las que favorezcan a la parte contraria se considerarán presentadas por ésta, apreciándose el mérito probatorio de todas ellas en conformidad a las reglas precedentes.


***4. De la confesión en juicio.***

**Art. 385 (375).** Fuera de los casos expresamente previstos por la ley, todo litigante está obligado a declarar bajo juramento, contestada que sea, la demanda, sobre hechos pertenecientes al mismo juicio, cuando lo exija el contendor o lo decrete el tribunal en conformidad al artículo 159.

Esta diligencia se podrá solicitar en cualquier estado del juicio y sin suspender por ella el procedimiento, hasta el vencimiento del término probatorio en primera instancia, y hasta antes de la vista de la causa en segunda. Este derecho sólo lo podrán ejercer las partes hasta por dos veces en primera instancia y una vez en segunda; pero, si se alegan hechos nuevos durante el juicio, podrá exigirse una vez más.

**Art. 386 (376).** Los hechos acerca de los cuales se exija la confesión podrán expresarse en forma asertiva o en forma interrogativa, pero siempre en términos claros y precisos, de manera que puedan ser entendidos sin dificultad.

**Art. 387 (377).** Mientras la confesión no sea prestada, se mantendrán en reserva las interrogaciones sobre que debe recaer.

**Art. 388 (378).** Si el tribunal no comete al secretario o a otro ministro de fe la diligencia, mandará citar para día y hora determinados al litigante que ha de prestar la declaración.

Siempre que alguna de las partes lo pida, debe el tribunal recibir por sí mismo la declaración del litigante.

Si el litigante se encuentra fuera del territorio del tribunal que conoce de la causa, será tomada su declaración por el tribunal competente, quien procederá en conformidad a los dos incisos anteriores.

**Art. 389 (379).** Están exentos de comparecer ante el tribunal a prestar la declaración de que tratan los artículos precedentes:

1º. El Presidente de la República, los Ministros de Estado, los Senadores y Diputados, los Delegados Presidenciales Regionales dentro de la región en que ejercen sus funciones; los miembros de la Corte Suprema o de alguna Corte de Apelaciones, los Fiscales Judiciales de estos tribunales, el Fiscal Nacional y los fiscales regionales;

2º. Los que por enfermedad o por cualquier otro impedimento calificado por el tribunal se hallen en imposibilidad de comparecer a la audiencia en que hayan de prestar la declaración; y

3º. Las mujeres, en caso que el tribunal estime prudente eximirlas de esta asistencia.

Cuando haya de prestar esta declaración alguna de las personas exceptuadas en los números precedentes, el juez se trasladará a casa de ella con el objeto de recibir la declaración o comisionará para este fin al secretario.

En los tribunales colegiados se comisionará para esta diligencia a alguno de los ministros del mismo o al secretario.

Si la persona que haya de prestar declaración en la forma prevenida en este artículo, se encuentra fuera del territorio del tribunal que conoce de la causa, encargará éste la diligencia al juez competente de la residencia actual del litigante. El juez exhortado practicará por sí mismo la diligencia o la cometerá a su secretario.

No se podrá comisionar al secretario para tomar la confesión cuando la parte haya solicitado que se preste ante el tribunal.

**Art. 390 (380).** Antes de interrogar al litigante, se le tomará juramento de decir verdad en conformidad al artículo 363.

**Art. 391 (381).** La declaración deberá prestarse inmediatamente, de palabra y en términos claros y precisos. Si el confesante es sordo o sordo-mudo, podrá escribir su confesión delante del tribunal o ministro de fe encargado de recibirla o, en su caso, se aplicará lo dispuesto en el artículo 382.

Si se trata de hechos personales, deberá prestarse afirmándolos o negándolos. Podrá, sin embargo, el tribunal admitir la excusa de olvido de los hechos, en casos calificados, cuando ella se funde en circunstancias verosímiles y notoriamente aceptables.

En todo caso podrá el confesante añadir las circunstancias necesarias para la recta y cabal inteligencia de lo declarado.

**Art. 392 (382).** Puede todo litigante presenciar la declaración del contendor y hacer al tribunal las observaciones que estime conducentes para aclarar, explicar o ampliar las preguntas que han de dirigírsele.

Puede también, antes que termine la diligencia y después de prestada la declaración, pedir que se repita si hay en las respuestas dadas algún punto obscuro o dudoso que aclarar.

**Art. 393 (383).** Si el litigante citado ante el tribunal para prestar declaración no comparece, se le volverá a citar bajo los apercibimientos que expresan los artículos siguientes.

**Art. 394 (384).** Si el litigante no comparece al segundo llamado, o si, compareciendo, se niega a declarar o da respuestas evasivas, se le dará por confeso, a petición de parte, en todos aquellos hechos que estén categóricamente afirmados en el escrito en que se pidió la declaración.

Si no están categóricamente afirmados los hechos, podrán los tribunales imponer al litigante rebelde una multa que no baje de medio sueldo vital ni exceda de un sueldo vital, o arrestos hasta por treinta días sin perjuicio de exigirle la declaración. Si la otra parte lo solicita, podrá también suspenderse el pronunciamiento de la sentencia hasta que la confesión se preste.

Cuando el interrogado solicite un plazo razonable para consultar sus documentos antes de responder, podrá otorgársele, siempre que haya fundamento plausible para pedirlo y el tribunal lo estime indispensable, o consienta en ello el contendor. La resolución del tribunal que conceda plazo será inapelable.

**Art. 395 (385).** Lo dicho en el artículo 370 es aplicable a la declaración de los litigantes.

**Art. 396 (386).** Podrá exigirse confesión al procurador de la parte sobre hechos personales de él mismo en el juicio aun cuando no tenga poder para absolver posiciones.

**Art. 397 (387).** El procurador es obligado a hacer comparecer a su mandante para absolver posiciones en el término razonable que el tribunal designe y bajo el apercibimiento indicado en el artículo 394.

La comparecencia se verificará ante el tribunal de la causa si la parte se encuentra en el lugar del juicio; en el caso contrario, ante el juez competente del territorio jurisdiccional en que resida o ante el respectivo agente diplomático o consular chileno, si ha salido del territorio de la República.

**Art. 398 (388).** La confesión extrajudicial es sólo base de presunción judicial, y no se tomará en cuenta, si es puramente verbal, sino en los casos en que sería admisible la prueba de testigos.

La confesión extrajudicial que se haya prestado a presencia de la parte que la invoca, o ante el juez incompetente, pero que ejerza jurisdicción, se estimará siempre como presunción grave para acreditar los hechos confesados. La misma regla se aplicará a la confesión prestada en otro juicio diverso; pero si éste se ha seguido entre las mismas partes que actualmente litigan, podrá dársele el mérito de prueba completa, habiendo motivos poderosos para estimarlo así.

**Art. 399 (389).** Los tribunales apreciarán la fuerza probatoria de la confesión judicial en conformidad a lo que establece el artículo 1713 del Código Civil y demás disposiciones legales.

Si los hechos confesados no son personales del confesante o de la persona a quien representa, producirá también prueba la confesión.

**Art. 400 (390).** La confesión tácita o presunta que establece el artículo 394, producirá los mismos efectos que la confesión expresa.

**Art. 401 (391).** En general el mérito de la confesión no puede dividirse en perjuicio del confesante.

Podrá, sin embargo, dividirse:

1° Siempre que comprenda hechos diversos enteramente desligados entre sí; y
 
2° Cuando, comprendiendo varios hechos ligados entre sí o que se modifiquen los unos a los otros, el contendor justifique con algún medio legal de prueba la falsedad de las circunstancias que, según el confesante, modifican o alteran el hecho confesado.

**Art. 402 (392).** No se recibirá prueba alguna contra los hechos personales claramente confesados por los litigantes en el juicio.

Podrá, sin embargo, admitirse prueba en este caso y aun abrirse un término especial para ella, si el tribunal lo estima necesario y ha expirado el probatorio de la causa, cuando el confesante alegue, para revocar su confesión, que ha padecido error de hecho y ofrezca justificar esta circunstancia.

Lo dispuesto en el inciso precedente se aplicará también al caso en que los hechos confesados no sean personales del confesante.

	
***5. De la inspección personal del tribunal.***

**Art. 403 (405).** Fuera de los casos expresamente señalados por la ley, la inspección personal del tribunal sólo se decretará cuando éste la estime necesaria; y se designará día y hora para practicarla, con la debida anticipación, a fin de que puedan concurrir las partes con sus abogados.

La inspección podrá verificarse aún fuera del territorio señalado a la jurisdicción del tribunal.

**Art. 404 (406).** Pueden las partes pedir que en el acto del reconocimiento se oigan informes de peritos, y lo decretará el tribunal si, a su juicio, esta medida es necesaria para el éxito de la inspección y ha sido solicitada con la anticipación conveniente. La designación de los peritos se hará en conformidad a las reglas del párrafo siguiente.

**Art. 405 (407).** Se llevará a efecto la inspección con la concurrencia de las partes y peritos que asistan, o sólo por el tribunal en ausencia de aquéllas.

Si el tribunal es colegiado, podrá comisionar para que practique la inspección a uno o más de sus miembros.

**Art. 406 (408).** La parte que haya solicitado la inspección depositará antes de proceder a ella, en manos del secretario del tribunal, la suma que éste estime necesaria para costear los gastos que se causen. Cuando la inspección sea decretada de oficio u ordenada por la ley, el depósito se hará por mitad entre demandantes y demandados.

**Art. 407 (409).** De la diligencia de inspección se levantará acta, en la cual se expresarán las circunstancias o hechos materiales que el tribunal observe, sin que puedan dichas observaciones reputarse como una opinión anticipada sobre los puntos que se debaten.

Podrán también las partes pedir, durante la diligencia, que se consignen en el acta las circunstancias o hechos materiales que consideren pertinentes.

**Art. 408 (410).** La inspección personal constituye prueba plena en cuanto a las circunstancias o hechos materiales que el tribunal establezca en el acta como resultado de su propia observación.

	
***6. Del informe de peritos.***

**Art. 409 (411).** Se oirá informe de peritos en todos aquellos casos en que la ley así lo disponga, ya sea que se valga de estas expresiones o de otras que indiquen la necesidad de consultar opiniones periciales.

**Art. 410 (412).** Cuando la ley ordene que se resuelva un asunto en juicio práctico o previo informe de peritos, se entenderán cumplidas estas disposiciones agregando el reconocimiento y dictamen pericial en conformidad a las reglas de este párrafo, al procedimiento que corresponda usar, según la naturaleza de la acción deducida.

**Art. 411 (413).** Podrá también oírse el informe de peritos:

1°. Sobre puntos de hecho para cuya apreciación se necesiten conocimientos especiales de alguna ciencia o arte; y

2°. Sobre puntos de derecho referentes a alguna legislación extranjera.

Los gastos y honorarios que en estos casos se originen por la diligencia misma o por la comparecencia de la otra parte al lugar donde debe practicarse, serán de cargo del que la haya solicitado; salvo que el tribunal estime necesaria la medida para el esclarecimiento de la cuestión, y sin perjuicio de lo que en definitiva se resuelva sobre pago de costas. El tribunal, de oficio o a petición de parte, podrá ordenar que previamente se consigne una cantidad prudencial para responder a los gastos y honorarios referidos.

La resolución por la cual se fije el monto de la consignación será notificada por cédula al que solicitó el informe de peritos. Si dicha parte deja transcurrir diez días, contados desde la fecha de la notificación, sin efectuar la consignación, se la tendrá por desistida de la diligencia pericial solicitada, sin más trámite.

**Artículo 412.-**  El reconocimiento de peritos podrá decretarse de oficio en cualquier estado del juicio, pero las partes sólo podrán solicitarlo dentro del término probatorio.

Decretado el informe de peritos, no se suspenderá por ello el procedimiento.

**Art. 413 (415).** Salvo acuerdo expreso de las partes, no podrán ser peritos:

1°. Los que sean inhábiles para declarar como testigos en el juicio; y

2°. Los que no tengan título profesional expedido por autoridad competente, si la ciencia o arte cuyo conocimiento se requiera está reglamentada por la ley y hay en el territorio jurisdiccional dos o más personas tituladas que puedan desempeñar el cargo.

**Art. 414 (416).** Para proceder al nombramiento de peritos, el tribunal citará a las partes a una audiencia, que tendrá lugar con sólo las que asistan y en la cual se fijará primeramente por acuerdo de las partes, o en su defecto por el tribunal, el número de peritos que deban nombrarse, la calidad, aptitudes o títulos que deban tener y el punto o puntos materia del informe.

Si las partes no se ponen de acuerdo sobre la designación de las personas, hará el nombramiento el tribunal, no pudiendo recaer en tal caso en ninguna de las dos primeras personas que hayan sido propuestas por cada parte.

La apelación que se deduzca en los casos del inciso 1° de este artículo no impedirá que se proceda a la designación de los peritos de conformidad al inciso 2°.

Sólo después de hecha esta designación, se llevará adelante el recurso.

**Art. 415 (417).** Se presume que no están de acuerdo las partes cuando no concurren todas a la audiencia de que trata el artículo anterior; y en tal caso habrá lugar a lo dispuesto en el 2° inciso del mismo artículo.

**Art. 416 (418).** Cuando el nombramiento se haga por el tribunal, lo hará de entre los peritos de la especialidad requerida que figuren en las listas a que se refiere el artículo siguiente y la designación se pondrá en conocimiento de las partes para que dentro de tercero día deduzcan oposición, si tienen alguna incapacidad legal que reclamar contra el nombrado. Vencido este plazo sin que se formule oposición, se entenderá aceptado el nombramiento.

**Artículo 416 bis.-** Las listas de peritos indicadas en el artículo precedente serán propuestas cada dos años por la Corte de Apelaciones respectiva, previa determinación del número de peritos que en su concepto deban figurar en cada especialidad.

En el mes de octubre del final del bienio correspondiente, se elevarán estas nóminas a la Corte Suprema, la cual formará las definitivas, pudiendo suprimir o agregar nombres sin expresar causa.

Para formar las listas, cada Corte de Apelaciones convocará a concurso público, al que podrán postular quienes posean y acrediten conocimientos especiales de alguna ciencia, arte o especialidad, para lo cual tendrán especialmente en cuenta la vinculación de los candidatos con la docencia y la investigación universitarias. El procedimiento para los concursos, su publicidad y la formación de las nóminas de peritos serán regulados mediante un Auto Acordado de la Corte Suprema, que se publicará en el Diario Oficial.

**Art. 417 (419).** El perito que acepte el cargo deberá declararlo así, jurando desempeñarlo con fidelidad.

De esta declaración, que habrá de hacerse verbalmente o por escrito en el acto de la notificación o dentro de los tres días inmediatos, se dejará testimonio en los autos.

El perito encargado de practicar un reconocimiento deberá citar previamente a las partes para que concurran si quieren.

**Art. 418 (420).** Cuando sean varios los peritos procederán unidos a practicar el reconocimiento, salvo que el tribunal los autorice para obrar de otra manera.

**Art. 419 (421).** Las partes podrán hacer en el acto del reconocimiento las observaciones que estimen oportunas. Podrán también pedir que se hagan constar los hechos y circunstancias que juzguen pertinentes; pero no tomarán parte en las deliberaciones de los peritos, ni estarán en ellas presentes.

De todo lo obrado se levantará acta, en la cual se consignarán los acuerdos celebrados por los peritos.

**Art. 420 (422).** Los tribunales señalarán en cada caso el término dentro del cual deben los peritos evacuar su encargo; y podrán, en caso de desobediencia, apremiarlos con multas, prescindir del informe o decretar el nombramiento de nuevos peritos, según los casos.

**Art. 421 (423).** Cuando los peritos discorden en sus dictámenes, podrá el tribunal disponer que se nombre un nuevo perito, si lo estima necesario para la mejor ilustración de las cuestiones que deban resolver.

El nuevo perito será nombrado y desempeñará su cargo en conformidad a las reglas precedentes.

**Art. 422 (424).** Si no resulta acuerdo del nuevo perito con los anteriores, el tribunal apreciará libremente las opiniones de todos ellos, tomando en cuenta los demás antecedentes del juicio.

**Art. 423 (425).** Los peritos podrán emitir sus informes conjunta o separadamente.

**Art. 424 (426).** Los incidentes a que dé lugar el nombramiento de los peritos y el desempeño de sus funciones se tramitarán en ramo separado.

**Art. 425 (427).** Los tribunales apreciarán la fuerza probatoria del dictamen de peritos en conformidad a las reglas de la sana crítica.

	
***7. De las presunciones***

**Art. 426 (428).** Las presunciones como medios probatorios, se regirán por las disposiciones del artículo 1712 del Código Civil.

Una sola presunción puede constituir plena prueba cuando, a juicio del tribunal, tenga caracteres de gravedad y precisión suficientes para formar su convencimiento.

**Art. 427 (429).** Sin perjuicio de las demás circunstancias que, en concepto del tribunal o por disposición de la ley, deban estimarse como base de una presunción, se reputarán verdaderos los hechos certificados en el proceso por un ministro de fe, a virtud de orden de tribunal competente, salvo prueba en contrario.

Igual presunción existirá a favor de los hechos declarados verdaderos en otro juicio entre las mismas partes.

	
***8. De la apreciación comparativa de los medios de prueba***

**Art. 428 (431).** Entre dos o más pruebas contradictorias, y a falta de ley que resuelva el conflicto, los tribunales preferirán la que crean más conforme con la verdad.

**Art. 429 (432).** Para que pueda invalidarse con prueba testimonial una escritura pública, se requiere la concurrencia de cinco testigos, que reúnan las condiciones expresadas en la regla segunda del artículo 384, que acrediten que la parte que se dice haber asistido personalmente al otorgamiento, o el escribano, o alguno de los testigos instrumentales, ha fallecido con anterioridad o ha permanecido fuera del lugar en el día del otorgamiento y en los setenta días subsiguientes.

Esta prueba, sin embargo, queda sujeta a la calificación del tribunal, quien la apreciará según las reglas de la sana crítica.

La disposición de este artículo sólo se aplicará cuando se trate de impugnar la autenticidad de la escritura misma, pero no las declaraciones consignadas en una escritura pública auténtica.


## Título XII. DE LOS PROCEDIMIENTOS POSTERIORES A LA PRUEBA

**Art. 430 (433).** Vencido el término de prueba, y dentro de los diez días siguientes, las partes podrán hacer por escrito las observaciones que el examen de la prueba les sugiera.

**Artículo 431.-** No será motivo para suspender el curso del juicio ni será obstáculo para la dictación del fallo el hecho de no haberse devuelto la prueba rendida fuera del tribunal, o el de no haberse practicado alguna otra diligencia de prueba pendiente, a menos que el tribunal, por resolución fundada, la estime estrictamente necesaria para la acertada resolución de la causa.  En este caso, la reiterará como medida para mejor resolver y se estará a lo establecido en el artículo 159.

En todo caso, si dicha prueba se recibiera por el tribunal una vez dictada la sentencia, ella se agregará al expediente para que sea considerada en segunda instancia, si hubiere lugar a ésta.

**Artículo 432.-** Vencido el plazo a que se refiere el artículo 430, se hayan o no presentado escritos y existan o no diligencias pendientes, el tribunal citará para oír sentencia.

En contra de esta resolución sólo podrá interponerse recurso de reposición, el que deberá fundarse en error de hecho y deducirse dentro de tercero día. La resolución que resuelva la reposición será inapelable.

**Art. 433 (437).** Citadas las partes para oír sentencia, no se admitirán escritos ni pruebas de ningún género.

Lo cual se entiende sin perjuicio de lo dispuesto por los artículos 83, 84, 159 y 290. Los plazos establecidos en los artículos 342 N° 3, 346 N° 3 y 347 que hubieren comenzado a correr al tiempo de la citación para oír sentencia, continuarán corriendo sin interrupción y la parte podrá dentro de ellos, ejercer su derecho de impugnación. De producirse ésta, se tramitará en cuaderno separado y se fallará en la sentencia definitiva, sin perjuicio de lo dispuesto en el artículo 431.



